const database = [
    { author: "mimi_crocheeatelie", content: "@donaeva_souza @jucolem" },
    {
        author: "mimi_crocheeatelie",
        content: "@juliasouza6522 @atelierlucrocheebijus",
    },
    { author: "mimi_crocheeatelie", content: "@evorinha @juliagramt" },
    { author: "mimi_crocheeatelie", content: "@nanath_assis @esdrasmourao" },
    {
        author: "mimi_crocheeatelie",
        content: "@maxizainesouzade @lana_souza_reis",
    },
    { author: "mimi_crocheeatelie", content: "@mimirmiranda @michelesa27" },
    { author: "mimi_crocheeatelie", content: "@_gabis_souza_ @zelia6401" },
    { author: "_gabis_souza_", content: "@zelia6401 @mimi_crocheeatelie" },
    { author: "isamelo31", content: "@luiztorri @monicasmelo" },
    { author: "isamelo31", content: "@rdmlx @adriano.floresta" },
    { author: "mel.guolo", content: "@simoneguolo @gabriel.alves23" },
    { author: "heloisa.brand", content: "@robsilvmaraninchi @izadorapf" },
    { author: "vaniaventola", content: "@anapaula.v.rossi @pri_fchaves" },
    { author: "ringneck.kiwi", content: "@josianit @tillarissa" },
    { author: "helo.bonim", content: "@fe.bonim @isa.bonim" },
    { author: "ringneck.kiwi", content: "@klausphotograph @giovannaf_b" },
    { author: "ringneck.kiwi", content: "@piusdayasmin @mingauringneck" },
    { author: "ringneck.kiwi", content: "@pliniothebird @jornaldopassarinho" },
    { author: "isa.bonim", content: "@helo.bonim @fe.bonim" },
    { author: "ringneck.kiwi", content: "@anjinhosdacarminha @carminhakoenig" },
    { author: "paaty_almeida_", content: "@eeve_xtina @mayseretta" },
    { author: "paaty_almeida_", content: "@rumildabarbosa @elisrosin" },
    { author: "sueslem_paula", content: "@su_sueline @j.reis30" },
    { author: "isa.bonim", content: "@isinha.rivas @gi_cavenaghi" },
    { author: "isa.bonim", content: "@morais_paty @raphaela_crestani" },
    { author: "sobczaack", content: "@shirosatto @pamelasatto" },
    {
        author: "lhbelina",
        content: "@moboratto @rafaelaamboni @bailey_bassethound",
    },
    { author: "laisdecosta", content: "@drbertoldi @sufelippini" },
    { author: "sobczaack", content: "@rcarla.satto @sattolola" },
    { author: "ferracimlarissa", content: "@joselucasressoni @joao_ressoni" },
    { author: "rafacorreia2530", content: "@caiocalou @edna_cassia" },
    { author: "lulypontel", content: "@anamprosa @adriane.rosa.969" },
    { author: "mayarapostal", content: "@kahoana @cleidepostal" },
    { author: "oswaldinho_chihuahua", content: "@thatapchaves @amandasnc" },
    { author: "mayarapostal", content: "@thaislynebittarello @jessicawilian" },
    {
        author: "vaniaventola",
        content: "@vivianefagundes27 @karlamolinarimundim",
    },
    { author: "mairafrv", content: "@valeriafbrandaop @mariliafveiga" },
    { author: "joanaxpoa", content: "@guzinskiana @linaritter" },
    {
        author: "oswaldinho_chihuahua",
        content: "@peixethedog @bruce.john_chihuahuas",
    },
    { author: "emilia_thayna13", content: "@dixx_eu_raiane @pvd_raianezinha" },
    {
        author: "emilia_thayna13",
        content: "@periquita_enjoada @periquito.fofinho",
    },
    { author: "rafacorreia2530", content: "@nayfeliciana @tainara.rosa1997" },
    { author: "mimitokuda", content: "@gabitkda @ineskeiko" },
    { author: "mimitokuda", content: "@gabitkda @ineskeiko" },
    { author: "emilia_thayna13", content: "@raiane.barbosa.16906 @r4faela.n" },
    { author: "mimitokuda", content: "@gabitkda @ineskeiko" },
    { author: "maria_gabi2009", content: "@tatydocecake @edu_flores89" },
    {
        author: "calopsitas_apollo",
        content: "@hannah.doguinha_ @clarlie_y_lolla",
    },
    { author: "emilia_thayna13", content: "@jaquelinegr2588 @janailson.joao" },
    { author: "paola_decosta", content: "@laisdecosta @carolsfronza" },
    { author: "rafaellaoam", content: "@thaisnm_ @luizakarez" },
    {
        author: "calopsitas_apollo",
        content: "@minha_cria_veterinarios @eu.filipa.psita",
    },
    { author: "rafaellaoam", content: "@aurea_carol_ @_sahsxx" },
    {
        author: "crystal._calopsita",
        content: "@carolinemunielly @benjamincalopsita_",
    },
    { author: "emilia_thayna13", content: "@camillymaria__ @millasofia395" },
    { author: "rafaellaoam", content: "@yagalorrane @zaragadan" },
    { author: "rafaellaoam", content: "@nayaraamed @dansalvess" },
    { author: "rafaellaoam", content: "@mariaclara_og @dansalvess" },
    {
        author: "calopsitas_apollo",
        content: "@calopsitta_gigi @catarina_helena_calopsita",
    },
    { author: "vitiregina", content: "@ivanybentomarques @bibizinhamt" },
    { author: "camillytawany853", content: "@petter_miranha @emy_rocha_" },
    { author: "rafaellaoam", content: "@mihh__rodrigues @mariaclarabdo" },
    { author: "rafaellaoam", content: "@gabilvrs @wanessa2609" },
    { author: "adrianavasconcellosp", content: "@diario_calopsitas @mporpeta" },
    {
        author: "claudiarabello_",
        content: "@roberta_palhares @amorsocrescevblp4",
    },
    { author: "rafaellaoam", content: "@ivojackk @monnye_gomide" },
    { author: "zeca_psita_", content: "@ticoebarto @belinho0206" },
    { author: "zeca_psita_", content: "@philipesilv @_vmaaia" },
    {
        author: "adrianavasconcellosp",
        content: "@calopsitas.brasil @psitashouse",
    },
    { author: "joanaxpoa", content: "@gtanikad8 @drub1n" },
    {
        author: "crystal._calopsita",
        content: "@lulu_almeida_08 @nanda_almeida_012",
    },
    { author: "calopsitas_apollo", content: "@babyyy_elijah @pituco_florzinha" },
    { author: "rafaellaoam", content: "@pvdyduayer @alexandreroque13" },
    { author: "zeca_psita_", content: "@lisa.calopsitas @criadouro_mw" },
    { author: "zeca_psita_", content: "@mariaduda6894 @melpsita1414" },
    { author: "zeca_psita_", content: "@cookieoltiel @periquita_enjoada" },
    { author: "zeca_psita_", content: "@criadourodupaes @psitas.daleiry" },
    {
        author: "rafaellaoam",
        content: "@joao_carlos_coronelpmmg @matosmoreiraandrea",
    },
    { author: "emilia_thayna13", content: "@silvanapaiva873 @00__amannda" },
    {
        author: "calopsitas_apollo",
        content: "@psitas_limfas @amorinhaacalopsita",
    },
    { author: "vitiregina", content: "@celia.m.oliveira.98 @guilherme.mica" },
    { author: "wanessa2609", content: "@rafaellaoam e @gabilvrs" },
    { author: "zeca_psita_", content: "@dopamina.saboaria @daniicosta12" },
    { author: "maria_gabi2009", content: "@pa.lopes_ @ths.minyas" },
    {
        author: "calopsitas_apollo",
        content: "@calopsitas_charlie_e_lola @budgteils",
    },
    { author: "calopsitas_apollo", content: "@kikoesuaturma19 @nego_psita1" },
    {
        author: "calopsitas_apollo",
        content: "@calopsitas_ze_e_amora @calopsita_tiquinh0",
    },
    { author: "jessis.lopes", content: "@bella.albuquerque.rosa @flavnin" },
    {
        author: "zeca_psita_",
        content: "@bulldogfrancesjack @biel_nenem_lele_linguica",
    },
    {
        author: "calopsitas_apollo",
        content: "@pequeno.titoo @piriquito254calopicita",
    },
    {
        author: "calopsitas_apollo",
        content: "@calopsitabibinhaebananinha @the_5_birdmigos",
    },
    { author: "cinco_psitas", content: "@psita.senior @pituco_pisita" },
    { author: "maria_gabi2009", content: "@limaa.stee @roberta_leticya_moraes" },
    { author: "cinco_psitas", content: "@psitashouse @companheirosdeasas" },
    { author: "cinco_psitas", content: "@_fredcalopsita_ @anto.bartolomeu" },
    {
        author: "maria_gabi2009",
        content: "@josethegomesdealmeida @josi_vini_almeida",
    },
    { author: "cinco_psitas", content: "@familia.pius @tatis.psitas" },
    { author: "cinco_psitas", content: "@gaudencio_agp @euoelvispsita" },
    { author: "paulacmb", content: "@licssan @antoninhoo" },
    { author: "zeca_psita_", content: "@beautiful_cute_lady_ @bolinha_e_dodo" },
    { author: "isa_k_14", content: "@eliannekeller" },
    { author: "isa_k_14", content: "@brendanacleto_" },
    {
        author: "carolinemunielly",
        content: "@lulu_almeida_08 @nanda_almeida_012",
    },
    { author: "maria_gabi2009", content: "@karenmarta_15 @rafaelricardomarta" },
    { author: "claravicsora", content: "@w3b_eloize @pedrotsora" },
    { author: "gabrielabocciat", content: "@alinunessz @edivinityz" },
    {
        author: "wanessa2609",
        content: "Sua linda, minha artista fantástica, phodastica",
    },
    { author: "cinco_psitas", content: "@isa.psitas @diario.das.4.jabutis" },
    {
        author: "ana.karolina71",
        content: "@me_sophia_gabriela_ @luizagabrielly_1425",
    },
    { author: "teddy_o_chede", content: "@rafagastaldello @apolo_caopanheiro" },
    { author: "teddy_o_chede", content: "@thaynagarbellotti @historiadecao" },
    {
        author: "sabrinafernandesdesantana",
        content: "@geovanaa_zz @taliita_cerqueira",
    },
    { author: "laura.tinti", content: "@dubarbosa.arq @ferpenna" },
    { author: "zoeypapagaiadocongo", content: "@diariodeaves @cacauacacatua" },
    {
        author: "bunnyxxmilly",
        content: "@julia_kjkkl @hyozin_.miojin quero uma da lolita véi",
    },
    { author: "sun.piusitas", content: "@_juliana_proenca @th_tasteofhoney" },
    { author: "sun.piusitas", content: "@_juliana_proenca @th_tasteofhoney" },
    { author: "_marisanogueira", content: "@cacaualecrim , @irinanogueira" },
    { author: "_marisanogueira", content: "@kitygrejo , @raimi_oficial" },
    {
        author: "marina_cristina.pilz",
        content: "@ricardoluiz.carneiro @grazielaseidel",
    },
    { author: "kiko.brasileiro", content: "@kanky_13 @katie_the_bull" },
    { author: "kiko.brasileiro", content: "@anny_kallyne20 @kyrashihtzu_" },
    { author: "kiko.brasileiro", content: "@emilia_thayna13 @wiwuwgevi" },
    { author: "kiko.brasileiro", content: "@emilia_thayna13 @julia_ferreira.13" },
    { author: "kiko.brasileiro", content: "@julia_ferreira.13 @tony.hamsterr" },
    { author: "kiko.brasileiro", content: "@tony.hamsterr @emilia_thayna13" },
    { author: "kiko.brasileiro", content: "@taniathayna2011 @batistadavan" },
    { author: "kiko.brasileiro", content: "@batalhas_e_vitorias @batistadavan" },
    { author: "emilia_thayna13", content: "@david_luan_araujo @camillymaria__" },
    { author: "emilia_thayna13", content: "@00__amannda @taniathayna2011" },
    {
        author: "emilia_thayna13",
        content: "@taniathayna2011 @raiane.barbosa.16906",
    },
    { author: "emilia_thayna13", content: "@tony_hamste @periquita_enjoada" },
    { author: "emilia_thayna13", content: "@021_felipee__ @janetef020" },
    { author: "emilia_thayna13", content: "@190_veronica @fernandaa06" },
    { author: "emilia_thayna13", content: "@po.liana736 @pose_do_brow2019" },
    { author: "emilia_thayna13", content: "@arthurbarbosa2019 @kiko.brasileiro" },
    { author: "emilia_thayna13", content: "@arthurbarbosa2019 @kiko.brasileiro" },
    { author: "emilia_thayna13", content: "@maroc_arodrigues @paulofhellipe" },
    {
        author: "isabelapedrosodasilva",
        content: "@gabrielaalmeidagpedroso @cecilia.nogueira687",
    },
    {
        author: "isabelapedrosodasilva",
        content: "@psita.senior @psitas_lua_e_juju",
    },
    { author: "isabelapedrosodasilva", content: "@anto.bartolomeu @psita_fenix" },
    { author: "isabelapedrosodasilva", content: "@lunapenabranca @psitashouse" },
    {
        author: "isabelapedrosodasilva",
        content: "@pituco_pisita @pequenograndeboris_",
    },
    { author: "isabelapedrosodasilva", content: "@tatis.psitas @isa.psitas" },
    { author: "isabelapedrosodasilva", content: "@sextetodeasas @harry_psita" },
    { author: "isabelapedrosodasilva", content: "@psitamel @lulu_de_lua" },
    {
        author: "isabelapedrosodasilva",
        content: "@ringneck_messi @messicalopsita",
    },
    { author: "estherfitti", content: "@luiza.fittipaldi @felipe.monteiro.562" },
    { author: "estherfitti", content: "@cristianofittipald @sylvia.fittipaldi" },
    { author: "estherfitti", content: "@genipedrosafittipaldi @pedrosa.katia" },
    { author: "estherfitti", content: "@tamirisfitt @fittipaldi_henrique" },
    { author: "estherfitti", content: "@jacquelinefalmeida @sergiofonseca8588" },
    { author: "kiko.brasileiro", content: "@su_koki__ @periquita_enjoada" },
    { author: "kiko.brasileiro", content: "@su_koki__ @periquita_enjoada" },
    { author: "kiko.brasileiro", content: "@su_koki_ @periquita_enjoada" },
    { author: "kiko.brasileiro", content: "@periquita_enjoada @mickey.pequines" },
    { author: "kiko.brasileiro", content: "@su_koki__ @sublime.natureza" },
    { author: "kiko.brasileiro", content: "@pandorababyrott @romario_aks" },
    { author: "kiko.brasileiro", content: "@yorks_and_the_west @winnie.baby_" },
    { author: "kiko.brasileiro", content: "@chowchowbsbsbsb @one_crazy_doodle" },
    { author: "kiko.brasileiro", content: "@wellizimmer @puku_bird" },
    {
        author: "kiko.brasileiro",
        content: "@ursinhos____carinhosos @uragano_dea",
    },
    { author: "kiko.brasileiro", content: "@ursoezaiaeshelby @pittyeursinha" },
    { author: "kiko.brasileiro", content: "@ursinhaamoraa @ursinhachowchow" },
    {
        author: "kiko.brasileiro",
        content: "@criadouro.mandarim @criadourosantacristina",
    },
    { author: "andrielekleitzke", content: "@vaniraknopp @suelenewald" },
    { author: "andrielekleitzke", content: "@regisleitzke @eduardaa_ewald" },
    { author: "andrielekleitzke", content: "@cristian_knopp @krolownatalia" },
    { author: "gabrielabocciat", content: "@sofiaalizama @miin_vict" },
    { author: "gabrielabocciat", content: "@pedriin__4 @caiosouzak3" },
    { author: "gabrielabocciat", content: "@bernardo29_sz @luttx_" },
    { author: "gabrielabocciat", content: "@soares_caroline00 @anninha_l.r" },
    { author: "gabrielabocciat", content: "@teixeira_rafs @isa_vrq" },
    { author: "gabrielabocciat", content: "@kesia_vazzzz @lczp_zacchia" },
    { author: "gabrielabocciat", content: "@bragagiuu @ogbielzxn" },
    { author: "rafaellaoam", content: "@diego_diur @yduayer" },
    { author: "rafaellaoam", content: "@yarabvs @immoonl" },
    { author: "rafaellaoam", content: "@luiza_carvalho8 @_ojuliana" },
    { author: "nina.epipoca", content: "@fc_messi.e.dudu @mporpeta" },
    { author: "nina.epipoca", content: "@o_mundodasaves @diario_calopsitas" },
    { author: "nina.epipoca", content: "@messicalopsita @vida_de_calopsita0" },
    {
        author: "nina.epipoca",
        content: "@calopsitas_vitoria_es @calopsitas_mansa",
    },
    { author: "nina.epipoca", content: "@calopze @casamaistres" },
    { author: "nina.epipoca", content: "@calopsita_thoor @calo.psitalindas" },
    { author: "nina.epipoca", content: "@calopsita.18 @catarinasbaby" },
    {
        author: "nina.epipoca",
        content: "@bolinha_e_caio @calopsita_diegoemanoel",
    },
    { author: "calopze", content: "@malusfm @juliocesar.marino" },
    { author: "calopze", content: "@lee_ticiaaah @geni.sales.127" },
    { author: "calopze", content: "@guilherme.fari.75839923 @fiona_acalop" },
    { author: "calopze", content: "@calopsita_silver_thoco @tomcandido13" },
    { author: "calopze", content: "@roselamulticolorida @ninocalopsita2022" },
    { author: "calopze", content: "@calopsita_messiesol @calop.fofa1nick" },
    { author: "megan.retriever", content: "@flaviamabueno @giijensbz" },
    { author: "megan.retriever", content: "@veh.bueno @jose_bananinha" },
    {
        author: "kiko.brasileiro",
        content: "@calopsitaslolaecharlie @calopscleiton_7l",
    },
    { author: "kiko.brasileiro", content: "@calopscleiton_7l @bebepsita" },
    { author: "kiko.brasileiro", content: "@calopsita._.tico @psitamel" },
    { author: "kiko.brasileiro", content: "@amorporcalopsita94 @bebepsita" },
    { author: "kiko.brasileiro", content: "@ferret.diego @tadeu.lulu" },
    { author: "kiko.brasileiro", content: "@juca_frajolinha @pandorababyrott" },
    {
        author: "kiko.brasileiro",
        content: "@juca_frajolinha @tayguer_2021americanbully",
    },
    {
        author: "kiko.brasileiro",
        content: "@tayguer_2021americanbully @_tangostar_",
    },
    {
        author: "kiko.brasileiro",
        content: "@tartaruga_beli_e_bile @tsukitai_hime0",
    },
    {
        author: "kiko.brasileiro",
        content: "@mari.e.tata.ofc @familia_calopsitaa",
    },
    { author: "kiko.brasileiro", content: "@nina_dog_20 @ninyca16" },
    { author: "kiko.brasileiro", content: "@nina_tico_calopsitas @ninyca16" },
    { author: "kiko.brasileiro", content: "@nina_dog_20 @nina_tico_calopsitas" },
    { author: "kiko.brasileiro", content: "@nickinho_apsita @nina_lhasaapso_" },
    { author: "kiko.brasileiro", content: "@ninacalopst @apollo_jaack" },
    {
        author: "kiko.brasileiro",
        content: "@king_apollored @vida_de_calopsitas_",
    },
    { author: "kiko.brasileiro", content: "@yorks_and_the_west @yasx_hk" },
    { author: "kiko.brasileiro", content: "@yorks_and_the_west @yasx_hk" },
    { author: "kiko.brasileiro", content: "@myn_cristine @tony.hamsterr" },
    { author: "kiko.brasileiro", content: "@yellowbirbb @zoey.ragdoll" },
    { author: "kiko.brasileiro", content: "@emilia_thayna13 @nt.norma" },
    { author: "kiko.brasileiro", content: "@zulema_bordie @pandorah.50" },
    { author: "kiko.brasileiro", content: "@marllyn5573 @budgies_8" },
    { author: "kiko.brasileiro", content: "@emilia_thayna13 @taniathayna2011" },
    { author: "kiko.brasileiro", content: "@emilia_thayna13 @tadeu.lulu" },
    { author: "kiko.brasileiro", content: "@winnie.baby_ @chowchowbsbsbsb" },
    {
        author: "kiko.brasileiro",
        content: "@korella.mix.official @chicletinhodapandora",
    },
    { author: "kiko.brasileiro", content: "@batistadavan @babyy_minos_" },
    { author: "kiko.brasileiro", content: "@lupita_bastos @bata.ta0309" },
    { author: "kiko.brasileiro", content: "@deaativsadohrnduens @lizzie281020" },
    { author: "kiko.brasileiro", content: "@pomeranian.jon @jon_restorick_art" },
    { author: "kiko.brasileiro", content: "@miaucademia @jonsnowthespitz" },
    { author: "kiko.brasileiro", content: "@jonespug1 @jonsnowthespitz" },
    { author: "kiko.brasileiro", content: "@jonsnowthespitz @jose_luan_244" },
    { author: "kiko.brasileiro", content: "@jose_luan_244 @lhasa.horacio" },
    { author: "kiko.brasileiro", content: "@hope_maya_dog @scooby.cm" },
    { author: "kiko.brasileiro", content: "@scooby_dyou @scotth_pitbul" },
    { author: "kiko.brasileiro", content: "@emilia_thayna13 @jack_ring_neck_" },
    { author: "kiko.brasileiro", content: "@libon55 @lilica_psita" },
    { author: "kiko.brasileiro", content: "@chihuahua.lilipaz20 @lilica_psita" },
    { author: "kiko.brasileiro", content: "@luninha.lindaaa @one_crazy_doodle" },
    { author: "kiko.brasileiro", content: "@lilyadotada @lilica_psita" },
    { author: "kiko.brasileiro", content: "@_shihtzu_liz_ @liz.calopsita1888" },
    { author: "kiko.brasileiro", content: "@carlos_gabriel.26 @gabriiel___011" },
    { author: "kiko.brasileiro", content: "@gabriiel___011 @gaboandre.07" },
    { author: "kiko.brasileiro", content: "@emilia_thayna13 @kanky_13" },
    { author: "kiko.brasileiro", content: "@emilia_thayna13 @mmanu_ferreira.11" },
    { author: "kiko.brasileiro", content: "@roselamulticolorida @guineaapiig" },
    { author: "isshimoto", content: "@leucostaj @pandoraaaamstaff_" },
    { author: "ninadestro", content: "@dehcg @tatalvess" },
    {
        author: "kiko.brasileiro",
        content: "@yasx_hk @joaopedroleitedeoliveira2008",
    },
    { author: "kiko.brasileiro", content: "@emilia_thayna13 @one_crazy_doodle" },
    { author: "kiko.brasileiro", content: "@wanessa2609 @one_crazy_doodle" },
    { author: "kiko.brasileiro", content: "@wanessa2609 @one_crazy_doodle" },
    {
        author: "kiko.brasileiro",
        content: "@osbulldogs.fofa_bolota @senhoritadog",
    },
    { author: "kiko.brasileiro", content: "@icarocalopsita @shihtzu_tokyo_20" },
    { author: "kiko.brasileiro", content: "@will__lola @music_ehsasi88" },
    { author: "kiko.brasileiro", content: "@calopsitaslolaecharlie @luizgvs" },
    { author: "kiko.brasileiro", content: "@julia_ferreira.13 @emilia_thayna13" },
    { author: "kiko.brasileiro", content: "@julia_ferreira.13 @emilia_thayna13" },
    { author: "_nataliaanunes", content: "@carolcnunis @sonia.nunes.7739814" },
    { author: "isa_k_14", content: "@alessandra1822021" },
    { author: "isa_k_14", content: "@brendanacleto_" },
    { author: "nicolepmota_", content: "@jmots_ @gilbertoportapilla" },
    { author: "nicolepmota_", content: "@rosisilvamota @marcolamota" },
    {
        author: "nicolepmota_",
        content: "@luciana_elivelto_monteiro @fernandaaasz3",
    },
    { author: "dudaxx__0", content: "@keanu_reeves_anao @edna.ldo51" },
    { author: "aanacmarques", content: "@carlos.zoo @nataliamarques.eng" },
    {
        author: "aanacmarques",
        content: "@marcosdmarques_ @raphaela_sobrancelhas",
    },
    { author: "aanacmarques", content: "@raphaelagraciane @gracianejaqueline" },
    { author: "emilia_thayna13", content: "@kiko.brasileiro @julia_ferreira.13" },
    { author: "batistadavan", content: "@emilia_thayna13 @arthurbarbosa2019" },
    { author: "batistadavan", content: "@julia_ferreira.13 @tony.hamsterr" },
    { author: "batistadavan", content: "@tony_hamste @tony.hamsterr" },
    { author: "batistadavan", content: "@yoon__a0213 @tony.hamsterr" },
    { author: "batistadavan", content: "@julia_ferreira.13 @emilia_thayna13" },
    {
        author: "rrroseskt_ted_e_lolo_yorkshire",
        content: "@prici.marques @rosangela.mafs",
    },
    { author: "prici.marques", content: "@sofia.yorkfofa @neusarborin" },
    { author: "prici.marques", content: "@borinsueli @jeferson_nardelli" },
    { author: "prici.marques", content: "@gleme99 @luzaccariotto" },
    { author: "tres.psitas", content: "@luanroier @nandadavanzo" },
    { author: "tres.psitas", content: "@evelyncrt @evibvbatista" },
    { author: "tres.psitas", content: "@paulacfortuna @paulagonzatto" },
    { author: "tres.psitas", content: "@karenserafini91 @stefanifavaro" },
    { author: "tres.psitas", content: "@paulofgraffoliveira @erikadavanzo" },
    { author: "tres.psitas", content: "@andreiadavanzo @carla_davanzo" },
    { author: "tres.psitas", content: "@zoeypapagaiadocongo @zoologico_pet" },
    { author: "tres.psitas", content: "@alvocalopsita @calopsitassuzuki" },
    { author: "tres.psitas", content: "@peninhascrazy @peninhasdeamor" },
    { author: "tres.psitas", content: "@caju_psitas @blu.calopsita" },
    { author: "tres.psitas", content: "@araras_blogueirinhas @psitasdabea" },
    { author: "tres.psitas", content: "@cookieoltiel @juca.ringneck" },
    { author: "tres.psitas", content: "@sun.piusitas @calopsitascamaradas" },
    { author: "cookie_calopsita_", content: "@be_macedo @viniciusjoaquimpania" },
    { author: "cookie_calopsita_", content: "@tres.psitas @piupets" },
    {
        author: "filhos_de_penas10",
        content: "@fabio.gomes.395017 @fabio_lira_123",
    },
    {
        author: "filhos_de_penas10",
        content: "@zoeypapagaiadocongo @zoe_calopsita_",
    },
    { author: "filhos_de_penas10", content: "@thaismelo112 @marcelocalopsita" },
    { author: "filhos_de_penas10", content: "@marcela.paiva.395 @tatianemelo97" },
    { author: "filhos_de_penas10", content: "@familia.pius @belpsita" },
    { author: "filhos_de_penas10", content: "@amorinhapsita30 @amor_de_blue" },
    {
        author: "filhos_de_penas10",
        content: "@perolafilhadepena @brunavasconcelos2011hotmailcom",
    },
    { author: "filhos_de_penas10", content: "@bruce_opastoralemao @brun4mello" },
    { author: "filhos_de_penas10", content: "@chiquinhomello @turma.do.buero" },
    { author: "filhos_de_penas10", content: "@alex__cockatiel @mundo_psita" },
    {
        author: "filhos_de_penas10",
        content: "@amigo.depenasepelos @amendoimbicotinha",
    },
    { author: "filhos_de_penas10", content: "@samia.antonio.77 @marcelo_e_ruth" },
    { author: "filhos_de_penas10", content: "@antonia094156 @lana_melo_1023" },
    { author: "filhos_de_penas10", content: "@layla.hering @lulu_de_lua" },
    { author: "filhos_de_penas10", content: "@luluzinhacalopsita @loves.psitas" },
    {
        author: "filhos_de_penas10",
        content: "@lolaporquinha_ @familiapsitacidea",
    },
    {
        author: "filhos_de_penas10",
        content: "@vida_com_psita @familia_penudinhos",
    },
    { author: "filhos_de_penas10", content: "@amorinhapsita30 @peninhasdeamor" },
    { author: "filhos_de_penas10", content: "@messicalopsita @kiwi.mestre" },
    { author: "filhos_de_penas10", content: "@lunacalopsita_ @psita.lily" },
    { author: "filhos_de_penas10", content: "@babypisita2021 @baby_bencao_2021" },
    {
        author: "filhos_de_penas10",
        content: "@matheusaraujo366 @marieagatinhasiames",
    },
    { author: "filhos_de_penas10", content: "@matheuss.euu @mamae_anthonyy" },
    { author: "filhos_de_penas10", content: "@anto.bartolomeu @antoniokaua0907" },
    {
        author: "filhos_de_penas10",
        content: "@lucianosilva3597 @leticiaalvees20",
    },
    { author: "filhos_de_penas10", content: "@filhosdepenas3 @leticiaalvees20" },
    {
        author: "filhos_de_penas10",
        content: "@cantinho_das_aves_mg @rinthegalah",
    },
    { author: "filhos_de_penas10", content: "@ringneck_messi @ringspet_love" },
    { author: "filhos_de_penas10", content: "@ricoperiquito @rio.calops" },
    { author: "filhos_de_penas10", content: "@pipa_teteu_calops @harry_psita" },
    {
        author: "filhos_de_penas10",
        content: "@lusineteximenes123 @gislane_ximenees",
    },
    {
        author: "filhos_de_penas10",
        content: "@renatamelo.mesquita @tamirispaiva44",
    },
    { author: "filhos_de_penas10", content: "@thaismelo584 @thaismello121" },
    {
        author: "filhos_de_penas10",
        content: "@babynicolas8366 @samia.antonio.77",
    },
    { author: "filhos_de_penas10", content: "@criadouro_r.s @criadourowings" },
    {
        author: "filhos_de_penas10",
        content: "@leandraloiola2013 @calopsitas_lelo.branco",
    },
    {
        author: "filhos_de_penas10",
        content: "@joaoechicafofinhus @joaopedro.calopsita",
    },
    {
        author: "filhos_de_penas10",
        content: "@theo_o_calopsita @calopsita_thoor",
    },
    { author: "filhos_de_penas10", content: "@amazona_verde @amarelinha6454" },
    {
        author: "filhos_de_penas10",
        content: "@amanda_parrots @calopsita.amarela",
    },
    { author: "filhos_de_penas10", content: "@piueozzy @olaf_calopsita_1" },
    { author: "filhos_de_penas10", content: "@thecalopsita @turma.do.buero" },
    {
        author: "filhos_de_penas10",
        content: "@alexandreadrianna @andreiasoares2809",
    },
    { author: "filhos_de_penas10", content: "@_saras2109 @janilmamelo" },
    { author: "filhos_de_penas10", content: "@abelcalopsita @leno_abel" },
    { author: "filhos_de_penas10", content: "@belinha_psita_ @psitandogram" },
    {
        author: "filhos_de_penas10",
        content: "@bela_e_falcao_calopsita @belchior_calopsita",
    },
    { author: "filhos_de_penas10", content: "@pet_rosela @pets.damila" },
    { author: "filhos_de_penas10", content: "@lunacalopsita_ @pets_da_dodo_" },
    { author: "filhos_de_penas10", content: "@calopsita.gaspar @galvao.bird_" },
    {
        author: "filhos_de_penas10",
        content: "@coelhinho_apolo @coelhos_nina_e_nick",
    },
    { author: "filhos_de_penas10", content: "@coelha_sophia @floquinho.coelho" },
    {
        author: "filhos_de_penas10",
        content: "@marcelocalopsita @calopsitas_da_mah",
    },
    { author: "filhos_de_penas10", content: "@mporpeta @clhoe_maya" },
    { author: "filhos_de_penas10", content: "@jhon.lua @alvocalopsita" },
    { author: "filhos_de_penas10", content: "@psitashouse @caju_psitas" },
    { author: "filhos_de_penas10", content: "@pdi.calopsitas @faroldasaves" },
    { author: "filhos_de_penas10", content: "@avesdabia @aves.do.amor" },
    {
        author: "filhos_de_penas10",
        content: "@_criadouro_o_mundo_das_aves @cantinho_das_aves_mg",
    },
    {
        author: "filhos_de_penas10",
        content: "@o_mundodasaves @familia_calopsita_omaki",
    },
    {
        author: "filhos_de_penas10",
        content: "@chaguinha.m.o @fabio.gomes.395017",
    },
    { author: "filhos_de_penas10", content: "@fa_bio904 @plantelfamiliapaixao" },
    {
        author: "filhos_de_penas10",
        content: "@jaqueline.melo296 @pandora_rosela",
    },
    { author: "filhos_de_penas10", content: "@kfelixart @ringneck.kiwi" },
    {
        author: "filhos_de_penas10",
        content: "@zoeypapagaiadocongo @o_mundodasaves",
    },
    {
        author: "filhos_de_penas10",
        content: "@marcela.paiva.395 @brunavasconcelos2011hotmailcom",
    },
    { author: "filhos_de_penas10", content: "@marcelo_e_ruth @samia.antonio.77" },
    {
        author: "filhos_de_penas10",
        content: "@avesdabia @recantodasaves_miriamvieira",
    },
    { author: "filhos_de_penas10", content: "@lana_melo_1023 @luno123343" },
    {
        author: "filhos_de_penas10",
        content: "@theo_o_calopsita @calopsita_thoor",
    },
    { author: "thaismelo112", content: "@leticiaalvees20 @liliane.oliveira32" },
    { author: "thaismelo112", content: "@tatianemelo97 @suelen_martins_lira" },
    { author: "thaismelo112", content: "@lyalimaa12 @leidiane_melo08" },
    { author: "thaismelo112", content: "@marcelo_e_ruth @samia.antonio.77" },
    { author: "thaismelo112", content: "@avesdabia @abelcalopsita" },
    { author: "thaismelo112", content: "@cleitynopitbull @camposelainne" },
    { author: "thaismelo112", content: "@fabio.gomes.395017 @chaguinha.m.o" },
    { author: "thaismelo112", content: "@janilmamelo @jake___oliveira" },
    {
        author: "thaismelo112",
        content: "@jaqueline.melo296 @jamile.rodrigues.923724",
    },
    { author: "thaismelo112", content: "@janariamarques @janaina_tupper" },
    {
        author: "thaismelo112",
        content: "@anna_iris_pessoa @ana_carla_vasconcelos",
    },
    {
        author: "thaismelo112",
        content: "@princesa_ana_e_mamae @anaflaviaparentt",
    },
    { author: "thaismelo112", content: "@marcosfelipe_adv @andreiasoares2809" },
    { author: "thaismelo112", content: "@andressa.pp @andreyvo9" },
    { author: "thaismelo112", content: "@antonioricardomesquita @bialbuque" },
    {
        author: "thaismelo112",
        content: "@filhos_de_penas10 @marieagatinhasiames",
    },
    { author: "thaismelo112", content: "@baby__ricky @baby_bencao_2021" },
    { author: "thaismelo112", content: "@_lauraavitoriaa_ @babypisita2021" },
    {
        author: "thaismelo112",
        content: "@marcela.paiva.395 @brunavasconcelos2011hotmailcom",
    },
    {
        author: "thaismelo112",
        content: "@antoniasousa1525 @antonio__rodrigues002",
    },
    { author: "thaismelo112", content: "@renan_mouta739 @mariaritaoliveiira_" },
    {
        author: "thaismelo112",
        content: "@cantinho_das_aves_mg @riziaalvesfeijao",
    },
    {
        author: "thaismelo112",
        content: "@thaisximenes_tata @peninhasdeamorpsita",
    },
    { author: "thaismelo112", content: "@messicalopsita @mesquitaalex784" },
    { author: "thaismelo112", content: "@amanda__beads @amanda_vasconcellos_96" },
    { author: "thaismelo112", content: "@marcelo_e_ruth @marcelolira771" },
    {
        author: "thaismelo112",
        content: "@samia.antonio.77 @antonioricardomesquita",
    },
    {
        author: "thaismelo112",
        content: "@antonia.elineuda.7 @antoniamariapereiravasconcelos",
    },
    { author: "thaismelo112", content: "@ronaldomesquita954 @renatomelo111" },
    { author: "thaismelo112", content: "@rebasilio00 @renatamelo.mesquita" },
    { author: "thaismelo112", content: "@renata.mesquita.3388 @renatopaiva6" },
    { author: "thaismelo112", content: "@renatavasconcelos06 @renan9271" },
    { author: "cidinhaorozco", content: "@orozcopat74 @marianasbonfim" },
    {
        author: "eleonora.montanheri",
        content: "@keniamontanheri @laura_pereiira12",
    },
    {
        author: "eleonora.montanheri",
        content: "@keniamontanheri @laura_pereiira12",
    },
    {
        author: "eleonora.montanheri",
        content: "@keniamontanheri @laura_pereiira12",
    },
    {
        author: "eleonora.montanheri",
        content: "@keniamontanheri @laura_pereiira12",
    },
    {
        author: "eleonora.montanheri",
        content: "@keniamontanheri @laura_pereiira12",
    },
    {
        author: "eleonora.montanheri",
        content: "@keniamontanheri @laura_pereiira12",
    },
    {
        author: "eleonora.montanheri",
        content: "@keniamontanheri @laura_pereiira12",
    },
    {
        author: "eleonora.montanheri",
        content: "@keniamontanheri @laura_pereiira12",
    },
    {
        author: "eleonora.montanheri",
        content: "@keniamontanheri @laura_pereiira12",
    },
    { author: "cicasmelo", content: "@abmrafaella @kelvingomes720" },
    { author: "barbara_camboim", content: "@joaop.felix @_bruna.melo29" },
    { author: "barbara_camboim", content: "@itsgideo @monteirogleydson" },
    { author: "barbara_camboim", content: "@natieleholanda @jehmcalheiros" },
    { author: "barbara_camboim", content: "@tizziana1 @diegocamboim" },
    { author: "barbara_camboim", content: "@krol.gsantos @budaemcaos" },
    {
        author: "barbara_camboim",
        content: "@bichosdavanessa @isabel.fernandes63",
    },
    { author: "bichosdavanessa", content: "@goodjr9 @micamercia" },
    { author: "bichosdavanessa", content: "@jorgeandreps @tinacastro43" },
    { author: "bichosdavanessa", content: "@sarah_barros82 @isabel.fernandes63" },
    { author: "bichosdavanessa", content: "@tyfontan @lorenamaiapsi" },
    { author: "bichosdavanessa", content: "@donamariapaiva @adolfaferry" },
    { author: "bichosdavanessa", content: "@alexrocha__ @saulodetarso_" },
    { author: "bichosdavanessa", content: "@priscila7764 @everson.alyson" },
    { author: "bichosdavanessa", content: "@natieleholanda @natanny_luizjr" },
    { author: "bichosdavanessa", content: "@iamjulietslayer @kellymoraes09" },
    { author: "bichosdavanessa", content: "@kelcymary @keylabraboadv" },
    { author: "bichosdavanessa", content: "@betasaiac @larabmd" },
    { author: "bichosdavanessa", content: "@anafiguereido @biulynha" },
    { author: "bichosdavanessa", content: "@coisadecarol @carollianas" },
    { author: "bichosdavanessa", content: "@edlainny_claudia @jamycarvalho" },
    {
        author: "bichosdavanessa",
        content: "@psicologoeriferreira @italoferreirapsi",
    },
    { author: "bichosdavanessa", content: "@piuduartesanches @daianarosecc" },
    { author: "bichosdavanessa", content: "@emanuela.ferry @flora_fandes" },
    { author: "bichosdavanessa", content: "@gatodionisio @cintiam1" },
    { author: "bichosdavanessa", content: "@roseanefortunatoc @estefaneollima" },
    { author: "bichosdavanessa", content: "@hemimart @floquinho_oficial14" },
    { author: "bichosdavanessa", content: "@negapretahu @cidocagalvaosaulino" },
    { author: "bichosdavanessa", content: "@layonmelo_ @larissaferry2" },
    { author: "sarah_barros82", content: "@bichosdavanessa @isabel.fernandes63" },
    { author: "bichosdavanessa", content: "@iamjulietslayer @bhn3t0" },
    { author: "bichosdavanessa", content: "@poly_med_lp @karlakviana" },
    { author: "bichosdavanessa", content: "@samia_reis @mhelenaxavier" },
    { author: "bichosdavanessa", content: "@helenamoraes1088 @roberliagomes" },
    { author: "thaismelo112", content: "@rafaelly.9040 @roger_maiaa" },
    { author: "thaismelo112", content: "@fabio.gomes.395017 @fabio_lira_123" },
    { author: "thaismelo112", content: "@samia.antonio.77 @marcelo_e_ruth" },
    { author: "thaismelo112", content: "@marcelolira771 @marcelo_e_ruth" },
    {
        author: "thaismelo112",
        content: "@brunavasconcelos2011hotmailcom @leticiaalvees20",
    },
    { author: "thaismelo112", content: "@lyalimaa12 @liliane.oliveira32" },
    { author: "thaismelo112", content: "@leidiane_melo08 @bessa_patricia24" },
    {
        author: "thaismelo112",
        content: "@brinquedoscalopsita @claraloiola.sobrancelhas",
    },
    { author: "thaismelo112", content: "@baby_bencao_2021 @babypisita2021" },
    { author: "thaismelo112", content: "@turma.do.buero @thaisximenes_tata" },
    { author: "thaismelo112", content: "@paiva.toinha @thayara_95" },
    { author: "thaismelo112", content: "@_thayscordeiro @thayara_95" },
    { author: "thaismelo112", content: "@thamy.lima28 @_thayscordeiro" },
    {
        author: "thaismelo112",
        content: "@brunavasconcelos2011hotmailcom @marcela.paiva.395",
    },
    { author: "thaismelo112", content: "@amanda__beads @_dyegonogueira" },
    { author: "thaismelo112", content: "@filhos_de_penas10 @fabio_lira_123" },
    { author: "thaismelo112", content: "@samia.antonio.77 @marcelo_e_ruth" },
    { author: "thaismelo112", content: "@anna_iris_pessoa @_inaratm" },
    { author: "thaismelo112", content: "@isis_miaa @irmaos_de_asas" },
    { author: "thaismelo112", content: "@suelen_martins_lira @chaguinha.m.o" },
    { author: "thaismelo112", content: "@saimu_lima @sabrinna__vasconcelos" },
    { author: "thaismelo112", content: "@zoeemanuelleof @wanessasouzaof" },
    { author: "thaismelo112", content: "@niellyaraujoo @ramir_ralison" },
    { author: "thaismelo112", content: "@cantinho_das_aves_mg @tatianemelo97" },
    { author: "thaismelo112", content: "@marcosfelipe_adv @andreiasoares2809" },
    { author: "thaismelo112", content: "@anderson_silva_mel0 @camposelainne" },
    { author: "thaismelo112", content: "@turma.do.buero @lyalimaa12" },
    { author: "thaismelo112", content: "@thaisximenes_tata @thaisalbuquerquex" },
    { author: "thaismelo112", content: "@filhos_de_penas10 @fabio_lira_123" },
    { author: "thaismelo112", content: "@toinogato2 @talespaiva16" },
    { author: "thaismelo112", content: "@bialbuque @marcela.paiva.395" },
    {
        author: "thaismelo112",
        content: "@brunavasconcelos2011hotmailcom @perolafilhadepena",
    },
    { author: "thaismelo112", content: "@marcela.paiva.395 @babypisita2021" },
    { author: "thaismelo112", content: "@_lauraavitoriaa_ @baby_bencao_2021" },
    { author: "thaismelo112", content: "@amanda__beads @loiola2302" },
    { author: "thaismelo112", content: "@amirtonalves @anacamila_myla" },
    { author: "thaismelo112", content: "@abelcalopsita @riziaalvesfeijao" },
    { author: "thaismelo112", content: "@andressa.pp @andreyvo9" },
    { author: "filhos_de_penas10", content: "@chiquinhomello @branca8681" },
    {
        author: "filhos_de_penas10",
        content: "@branca8681 @recantodasaves_miriamvieira",
    },
    {
        author: "filhos_de_penas10",
        content: "@brunavasconcelos2011hotmailcom @marcelocalopsita",
    },
    {
        author: "filhos_de_penas10",
        content: "@fabio.gomes.395017 @fabio_lira_123",
    },
    {
        author: "filhos_de_penas10",
        content: "@mariocalopsita @marieagatinhasiames",
    },
    { author: "filhos_de_penas10", content: "@marcelo_e_ruth @antonia094156" },
    { author: "filhos_de_penas10", content: "@anto.bartolomeu @lana_melo_1023" },
    { author: "filhos_de_penas10", content: "@zoeypapagaiadocongo @flap_pet" },
    { author: "filhos_de_penas10", content: "@piu_pipi @papagaiotheozinho" },
    { author: "filhos_de_penas10", content: "@thaismelo112 @fabio_lira_123" },
    { author: "filhos_de_penas10", content: "@andreiasoares2809 @_saras2109" },
    { author: "filhos_de_penas10", content: "@alex__cockatiel @faroldasaves" },
    {
        author: "filhos_de_penas10",
        content: "@familia_cookiando @familiapsitacidea",
    },
    { author: "filhos_de_penas10", content: "@filhos_de_penas @filhosdepenas3" },
    { author: "filhos_de_penas10", content: "@amor_de_blue @mundo_psita" },
    {
        author: "filhos_de_penas10",
        content: "@cantinho_das_aves_mg @theo_o_calopsita",
    },
    { author: "filhos_de_penas10", content: "@dino_tex_pets @turma.do.buero" },
    {
        author: "filhos_de_penas10",
        content: "@calopsita_thoor @theo_o_calopsita",
    },
    { author: "filhos_de_penas10", content: "@leticiaalvees20 @filhosdepenas3" },
    { author: "filhos_de_penas10", content: "@calopsitassuzuki @srluks17" },
    { author: "filhos_de_penas10", content: "@lucianosilva3597 @shitzu_pan" },
    {
        author: "filhos_de_penas10",
        content: "@safira_passarodoamor @agarponis_jundiai",
    },
    {
        author: "filhos_de_penas10",
        content: "@piueozzy @mundodopulinho_calopsita",
    },
    { author: "filhos_de_penas10", content: "@belpsita @vida_com_psita" },
    { author: "filhos_de_penas10", content: "@lulu_de_lua @peninhasdeamor" },
    { author: "filhos_de_penas10", content: "@harry_psita @psitas_lua_e_juju" },
    { author: "filhos_de_penas10", content: "@pet_rosela @peninhasdeamorpsita" },
    { author: "filhos_de_penas10", content: "@harry_psita @psitas_lua_e_juju" },
    { author: "filhos_de_penas10", content: "@lulu_de_lua @peninhasdeamor" },
    { author: "filhos_de_penas10", content: "@belpsita @vida_com_psita" },
    { author: "filhos_de_penas10", content: "@lucianosilva3597 @shitzu_pan" },
    { author: "filhos_de_penas10", content: "@calopsitassuzuki @srluks17" },
    { author: "filhos_de_penas10", content: "@amor_de_blue @mundo_psita" },
    { author: "filhos_de_penas10", content: "@filhos_de_penas @filhosdepenas3" },
    {
        author: "filhos_de_penas10",
        content: "@familia_cookiando @familiapsitacidea",
    },
    { author: "filhos_de_penas10", content: "@alex__cockatiel @faroldasaves" },
    { author: "filhos_de_penas10", content: "@piu_pipi @papagaiotheozinho" },
    {
        author: "filhos_de_penas10",
        content: "@mariocalopsita @marieagatinhasiames",
    },
    {
        author: "filhos_de_penas10",
        content: "@brunavasconcelos2011hotmailcom @marcelocalopsita",
    },
    {
        author: "filhos_de_penas10",
        content: "@branca8681 @recantodasaves_miriamvieira",
    },
    { author: "filhos_de_penas10", content: "@chiquinhomello @branca8681" },
    { author: "thaismelo112", content: "@amirtonalves @anacamila_myla" },
    { author: "thaismelo112", content: "@amanda__beads @loiola2302" },
    { author: "thaismelo112", content: "@_lauraavitoriaa_ @baby_bencao_2021" },
    { author: "thaismelo112", content: "@marcela.paiva.395 @babypisita2021" },
    {
        author: "thaismelo112",
        content: "@brunavasconcelos2011hotmailcom @perolafilhadepena",
    },
    { author: "thaismelo112", content: "@bialbuque @marcela.paiva.395" },
    { author: "thaismelo112", content: "@filhos_de_penas10 @fabio_lira_123" },
    { author: "thaismelo112", content: "@thaisximenes_tata @thaisalbuquerquex" },
    { author: "thaismelo112", content: "@marcosfelipe_adv @andreiasoares2809" },
    { author: "thaismelo112", content: "@filhos_de_penas10 @fabio_lira_123" },
    { author: "thaismelo112", content: "@leidiane_melo08 @bessa_patricia24" },
    { author: "thaismelo112", content: "@lyalimaa12 @liliane.oliveira32" },
    {
        author: "thaismelo112",
        content: "@brunavasconcelos2011hotmailcom @leticiaalvees20",
    },
    { author: "thaismelo112", content: "@marcelolira771 @marcelo_e_ruth" },
    { author: "thaismelo112", content: "@samia.antonio.77 @marcelo_e_ruth" },
    { author: "thaismelo112", content: "@fabio.gomes.395017 @fabio_lira_123" },
    { author: "bichosdavanessa", content: "@samia_reis @mhelenaxavier" },
    { author: "bichosdavanessa", content: "@poly_med_lp @karlakviana" },
    { author: "bichosdavanessa", content: "@hemimart @floquinho_oficial14" },
    { author: "bichosdavanessa", content: "@coisadecarol @carollianas" },
    { author: "cicasmelo", content: "@abmrafaella @kelvingomes720" },
    {
        author: "eleonora.montanheri",
        content: "@keniamontanheri @laura_pereiira12",
    },
    {
        author: "eleonora.montanheri",
        content: "@keniamontanheri @laura_pereiira12",
    },
    {
        author: "eleonora.montanheri",
        content: "@keniamontanheri @laura_pereiira12",
    },
    {
        author: "eleonora.montanheri",
        content: "@keniamontanheri @laura_pereiira12",
    },
    {
        author: "eleonora.montanheri",
        content: "@keniamontanheri @laura_pereiira12",
    },
    {
        author: "eleonora.montanheri",
        content: "@keniamontanheri @laura_pereiira12",
    },
    {
        author: "eleonora.montanheri",
        content: "@keniamontanheri @laura_pereiira12",
    },
    {
        author: "eleonora.montanheri",
        content: "@keniamontanheri @laura_pereiira12",
    },
    { author: "cidinhaorozco", content: "@orozcopat74 @marianasbonfim" },
    { author: "thaismelo112", content: "@renatavasconcelos06 @renan9271" },
    { author: "thaismelo112", content: "@amanda__beads @amanda_vasconcellos_96" },
    {
        author: "thaismelo112",
        content: "@antoniasousa1525 @antonio__rodrigues002",
    },
    {
        author: "thaismelo112",
        content: "@marcela.paiva.395 @brunavasconcelos2011hotmailcom",
    },
    { author: "thaismelo112", content: "@_lauraavitoriaa_ @babypisita2021" },
    { author: "thaismelo112", content: "@baby__ricky @baby_bencao_2021" },
    {
        author: "thaismelo112",
        content: "@filhos_de_penas10 @marieagatinhasiames",
    },
    { author: "thaismelo112", content: "@andressa.pp @andreyvo9" },
    {
        author: "thaismelo112",
        content: "@princesa_ana_e_mamae @anaflaviaparentt",
    },
    {
        author: "thaismelo112",
        content: "@anna_iris_pessoa @ana_carla_vasconcelos",
    },
    { author: "thaismelo112", content: "@janariamarques @janaina_tupper" },
    {
        author: "thaismelo112",
        content: "@jaqueline.melo296 @jamile.rodrigues.923724",
    },
    { author: "thaismelo112", content: "@janilmamelo @jake___oliveira" },
    { author: "thaismelo112", content: "@fabio.gomes.395017 @chaguinha.m.o" },
    { author: "thaismelo112", content: "@cleitynopitbull @camposelainne" },
    { author: "thaismelo112", content: "@avesdabia @abelcalopsita" },
    { author: "thaismelo112", content: "@marcelo_e_ruth @samia.antonio.77" },
    { author: "thaismelo112", content: "@leticiaalvees20 @liliane.oliveira32" },
    { author: "filhos_de_penas10", content: "@lana_melo_1023 @luno123343" },
    {
        author: "filhos_de_penas10",
        content: "@avesdabia @recantodasaves_miriamvieira",
    },
    { author: "filhos_de_penas10", content: "@marcelo_e_ruth @samia.antonio.77" },
    {
        author: "filhos_de_penas10",
        content: "@marcela.paiva.395 @brunavasconcelos2011hotmailcom",
    },
    {
        author: "filhos_de_penas10",
        content: "@zoeypapagaiadocongo @o_mundodasaves",
    },
    {
        author: "filhos_de_penas10",
        content: "@jaqueline.melo296 @pandora_rosela",
    },
    { author: "filhos_de_penas10", content: "@fa_bio904 @plantelfamiliapaixao" },
    {
        author: "filhos_de_penas10",
        content: "@chaguinha.m.o @fabio.gomes.395017",
    },
    {
        author: "filhos_de_penas10",
        content: "@o_mundodasaves @familia_calopsita_omaki",
    },
    { author: "filhos_de_penas10", content: "@avesdabia @aves.do.amor" },
    { author: "filhos_de_penas10", content: "@pdi.calopsitas @faroldasaves" },
    {
        author: "filhos_de_penas10",
        content: "@marcelocalopsita @calopsitas_da_mah",
    },
    {
        author: "filhos_de_penas10",
        content: "@coelhinho_apolo @coelhos_nina_e_nick",
    },
    { author: "filhos_de_penas10", content: "@calopsita.gaspar @galvao.bird_" },
    { author: "filhos_de_penas10", content: "@lunacalopsita_ @pets_da_dodo_" },
    { author: "filhos_de_penas10", content: "@pet_rosela @pets.damila" },
    { author: "filhos_de_penas10", content: "@belinha_psita_ @psitandogram" },
    {
        author: "filhos_de_penas10",
        content: "@alexandreadrianna @andreiasoares2809",
    },
    { author: "filhos_de_penas10", content: "@thecalopsita @turma.do.buero" },
    {
        author: "filhos_de_penas10",
        content: "@amanda_parrots @calopsita.amarela",
    },
    {
        author: "filhos_de_penas10",
        content: "@theo_o_calopsita @calopsita_thoor",
    },
    {
        author: "filhos_de_penas10",
        content: "@joaoechicafofinhus @joaopedro.calopsita",
    },
    {
        author: "filhos_de_penas10",
        content: "@babynicolas8366 @samia.antonio.77",
    },
    { author: "filhos_de_penas10", content: "@filhosdepenas3 @leticiaalvees20" },
    {
        author: "filhos_de_penas10",
        content: "@lucianosilva3597 @leticiaalvees20",
    },
    { author: "filhos_de_penas10", content: "@anto.bartolomeu @antoniokaua0907" },
    { author: "filhos_de_penas10", content: "@matheuss.euu @mamae_anthonyy" },
    {
        author: "filhos_de_penas10",
        content: "@matheusaraujo366 @marieagatinhasiames",
    },
    { author: "filhos_de_penas10", content: "@babypisita2021 @baby_bencao_2021" },
    { author: "filhos_de_penas10", content: "@lunacalopsita_ @psita.lily" },
    { author: "filhos_de_penas10", content: "@amorinhapsita30 @peninhasdeamor" },
    {
        author: "filhos_de_penas10",
        content: "@lolaporquinha_ @familiapsitacidea",
    },
    { author: "filhos_de_penas10", content: "@layla.hering @lulu_de_lua" },
    { author: "filhos_de_penas10", content: "@alex__cockatiel @mundo_psita" },
    { author: "filhos_de_penas10", content: "@bruce_opastoralemao @brun4mello" },
    {
        author: "filhos_de_penas10",
        content: "@perolafilhadepena @brunavasconcelos2011hotmailcom",
    },
    { author: "filhos_de_penas10", content: "@familia.pius @belpsita" },
    { author: "filhos_de_penas10", content: "@marcela.paiva.395 @tatianemelo97" },
    { author: "filhos_de_penas10", content: "@thaismelo112 @marcelocalopsita" },
    {
        author: "filhos_de_penas10",
        content: "@zoeypapagaiadocongo @zoe_calopsita_",
    },
    { author: "prici.marques", content: "@borinsueli @jeferson_nardelli" },
    { author: "batistadavan", content: "@julia_ferreira.13 @emilia_thayna13" },
    { author: "batistadavan", content: "@julia_ferreira.13 @tony.hamsterr" },
    {
        author: "aanacmarques",
        content: "@marcosdmarques_ @raphaela_sobrancelhas",
    },
    { author: "kiko.brasileiro", content: "@julia_ferreira.13 @emilia_thayna13" },
    { author: "isshimoto", content: "@leucostaj @pandoraaaamstaff_" },
    { author: "kiko.brasileiro", content: "@gabriiel___011 @gaboandre.07" },
    { author: "kiko.brasileiro", content: "@chihuahua.lilipaz20 @lilica_psita" },
    { author: "kiko.brasileiro", content: "@libon55 @lilica_psita" },
    { author: "kiko.brasileiro", content: "@emilia_thayna13 @jack_ring_neck_" },
    { author: "kiko.brasileiro", content: "@scooby_dyou @scotth_pitbul" },
    { author: "kiko.brasileiro", content: "@jonsnowthespitz @jose_luan_244" },
    { author: "kiko.brasileiro", content: "@jonespug1 @jonsnowthespitz" },
    { author: "kiko.brasileiro", content: "@miaucademia @jonsnowthespitz" },
    { author: "kiko.brasileiro", content: "@pomeranian.jon @jon_restorick_art" },
    { author: "kiko.brasileiro", content: "@deaativsadohrnduens @lizzie281020" },
    { author: "kiko.brasileiro", content: "@batistadavan @babyy_minos_" },
    { author: "kiko.brasileiro", content: "@emilia_thayna13 @taniathayna2011" },
    { author: "kiko.brasileiro", content: "@marllyn5573 @budgies_8" },
    { author: "kiko.brasileiro", content: "@myn_cristine @tony.hamsterr" },
    { author: "kiko.brasileiro", content: "@nickinho_apsita @nina_lhasaapso_" },
    { author: "kiko.brasileiro", content: "@nina_dog_20 @nina_tico_calopsitas" },
    { author: "kiko.brasileiro", content: "@nina_dog_20 @ninyca16" },
    {
        author: "kiko.brasileiro",
        content: "@tartaruga_beli_e_bile @tsukitai_hime0",
    },
    {
        author: "kiko.brasileiro",
        content: "@tayguer_2021americanbully @_tangostar_",
    },
    { author: "kiko.brasileiro", content: "@ferret.diego @tadeu.lulu" },
    { author: "kiko.brasileiro", content: "@amorporcalopsita94 @bebepsita" },
    { author: "calopze", content: "@calopsita_messiesol @calop.fofa1nick" },
    { author: "calopze", content: "@calopsita_silver_thoco @tomcandido13" },
    { author: "calopze", content: "@lee_ticiaaah @geni.sales.127" },
    { author: "calopze", content: "@malusfm @juliocesar.marino" },
    { author: "nina.epipoca", content: "@calopsita.18 @catarinasbaby" },
    { author: "nina.epipoca", content: "@calopze @casamaistres" },
    {
        author: "nina.epipoca",
        content: "@calopsitas_vitoria_es @calopsitas_mansa",
    },
    { author: "nina.epipoca", content: "@messicalopsita @vida_de_calopsita0" },
    { author: "nina.epipoca", content: "@o_mundodasaves @diario_calopsitas" },
    { author: "nina.epipoca", content: "@fc_messi.e.dudu @mporpeta" },
    { author: "gabrielabocciat", content: "@kesia_vazzzz @lczp_zacchia" },
    { author: "gabrielabocciat", content: "@teixeira_rafs @isa_vrq" },
    { author: "gabrielabocciat", content: "@pedriin__4 @caiosouzak3" },
    { author: "gabrielabocciat", content: "@sofiaalizama @miin_vict" },
    { author: "andrielekleitzke", content: "@regisleitzke @eduardaa_ewald" },
    { author: "andrielekleitzke", content: "@vaniraknopp @suelenewald" },
    { author: "kiko.brasileiro", content: "@ursoezaiaeshelby @pittyeursinha" },
    { author: "kiko.brasileiro", content: "@chowchowbsbsbsb @one_crazy_doodle" },
    { author: "kiko.brasileiro", content: "@yorks_and_the_west @winnie.baby_" },
    { author: "estherfitti", content: "@jacquelinefalmeida @sergiofonseca8588" },
    { author: "estherfitti", content: "@tamirisfitt @fittipaldi_henrique" },
    { author: "estherfitti", content: "@cristianofittipald @sylvia.fittipaldi" },
    { author: "estherfitti", content: "@luiza.fittipaldi @felipe.monteiro.562" },
    {
        author: "isabelapedrosodasilva",
        content: "@ringneck_messi @messicalopsita",
    },
    { author: "isabelapedrosodasilva", content: "@psitamel @lulu_de_lua" },
    {
        author: "isabelapedrosodasilva",
        content: "@gabrielaalmeidagpedroso @cecilia.nogueira687",
    },
    { author: "emilia_thayna13", content: "@maroc_arodrigues @paulofhellipe" },
    { author: "emilia_thayna13", content: "@arthurbarbosa2019 @kiko.brasileiro" },
    { author: "emilia_thayna13", content: "@arthurbarbosa2019 @kiko.brasileiro" },
    { author: "emilia_thayna13", content: "@190_veronica @fernandaa06" },
    { author: "emilia_thayna13", content: "@alinne__gs @romariorocha06" },
    { author: "emilia_thayna13", content: "@aliceraiane2 @romariorocha06" },
    { author: "emilia_thayna13", content: "@josericardo6984 @josy__bp" },
    {
        author: "emilia_thayna13",
        content: "@joaopedromartins083 @jose_thiaguinho",
    },
    {
        author: "emilia_thayna13",
        content: "@janailson.joao @joaopedromartins083",
    },
    {
        author: "emilia_thayna13",
        content: "@lucelia.bolos_e_docesdecorados @samuel_vinicius2457",
    },
    { author: "emilia_thayna13", content: "@kiko.brasileiro @_brn_alves" },
    { author: "emilia_thayna13", content: "@peliculasmariza @romeu_meulindo" },
    { author: "emilia_thayna13", content: "@bruce_wayne1903 @pandorah.50" },
    {
        author: "emilia_thayna13",
        content: "@amandaaraujo6470 @arthurbarbosa2019",
    },
    { author: "emilia_thayna13", content: "@helloysan @heloacostta" },
    { author: "emilia_thayna13", content: "@ellen_lorena25 @anny_kallyne20" },
    { author: "emilia_thayna13", content: "@_dd7oficial @____textos123____" },
    { author: "emilia_thayna13", content: "@_dud1inhax @_anaceciliaalvees" },
    { author: "emilia_thayna13", content: "@_brn_alves @islennbeatriz" },
    {
        author: "emilia_thayna13",
        content: "@victor_gabriell44a @juliana.ferreira.jgcj",
    },
    { author: "emilia_thayna13", content: "@maryanaa.bs @maryanaa_bs" },
    {
        author: "emilia_thayna13",
        content: "@kawany.vitoria.16144606 @anny_kallyne20",
    },
    {
        author: "emilia_thayna13",
        content: "@maraparecida2672 @david_luan_araujo",
    },
    { author: "kiko.brasileiro", content: "@romeu.babyboy @romariorocha06" },
    { author: "kiko.brasileiro", content: "@ringneck_messi @okame_rin_shinamon" },
    { author: "kiko.brasileiro", content: "@aliceraiane2 @romariorocha06" },
    { author: "kiko.brasileiro", content: "@bruninhaa_alveez @aliceraiane2" },
    { author: "kiko.brasileiro", content: "@romeuejulieta967 @meg.rodrigues01" },
    { author: "kiko.brasileiro", content: "@bella.e_lua028 @don_frida_e_lola" },
    { author: "kiko.brasileiro", content: "@anny_kallyne20 @emilia_thayna13" },
    { author: "kiko.brasileiro", content: "@anny_kallyne20 @ellen_lorena25" },
    { author: "kiko.brasileiro", content: "@helloysan @heroi.1311" },
    { author: "kiko.brasileiro", content: "@theboxerdog.india @familia_curtina" },
    { author: "kiko.brasileiro", content: "@tony.hamsterr @emilia_thayna13" },
    { author: "kiko.brasileiro", content: "@julia_ferreira.13 @tony.hamsterr" },
    { author: "kiko.brasileiro", content: "@190_veronica @julia_ferreira.13" },
    { author: "kiko.brasileiro", content: "@cislley @puku_bird" },
    { author: "kiko.brasileiro", content: "@emilia_thayna13 @helloysan" },
    { author: "kiko.brasileiro", content: "@arthurbarbosa2019 @emilia_thayna13" },
    { author: "kiko.brasileiro", content: "@batistadavan @taniathayna2011" },
    { author: "kiko.brasileiro", content: "@batistadavam @taniathayna2011" },
    { author: "marina_cristina.pilz", content: "@gabipykocz @naluaraa" },
    {
        author: "_marisanogueira",
        content: "@rrroseskt_ted_e_lolo_yorkshire , @sabrina.mello27",
    },
    { author: "_marisanogueira", content: "@gabrielaargeu, @marciaargeu" },
    { author: "sun.piusitas", content: "@giigumiero @jorge_eduardo_neris" },
    { author: "sun.piusitas", content: "@giigumiero @jorge_eduardo_neris" },
    { author: "amandamoniche", content: "@veramoreira5950 @naty_moniche" },
    { author: "amandamoniche", content: "@rafamoniche @anabeatriz_amorim12" },
    { author: "_biah.bijuss", content: "@marcelopier" },
    { author: "laura.tinti", content: "@tharsis.f @nabiamaria" },
    { author: "idealizzarepresentes", content: "@elizete4509 @maurovergani76" },
    {
        author: "idealizzarepresentes",
        content: "@roberta_nutricao_terapias @flaviorobertovergani",
    },
    {
        author: "idealizzarepresentes",
        content: "@marzaneferreira @embuttenbender",
    },
    {
        author: "idealizzarepresentes",
        content: "@christian_d_martini @bbuttenbender",
    },
    {
        author: "niceziapatricia",
        content: "@jonashipolito021 @ligiamara.depaula",
    },
    { author: "isa_k_14", content: "@rql_14_" },
    { author: "isa_k_14", content: "@fonsecaalyne" },
    { author: "isa_k_14", content: "@thythygabi" },
    { author: "isa_k_14", content: "@teixeirasofis" },
    { author: "isa_k_14", content: "@suellem_oliveira_57" },
    { author: "isa_k_14", content: "@alessandra1822021" },
    { author: "jose_bessa", content: "@thammy_caroliine @diogobdon" },
    { author: "jose_bessa", content: "@nrbessa @neziabatista" },
    { author: "flavnin", content: "@larissa.stefany.teles @taynarafernaandees" },
    { author: "flavnin", content: "@wbyte_ @livre.artetattoo" },
    { author: "flavnin", content: "@matheu5_henriqu3 @memillybs" },
    { author: "be_macedo", content: "@cookie_calopsita_ @viniciusjoaquimpania" },
    { author: "be_macedo", content: "@to_riavi @bassolife" },
    { author: "be_macedo", content: "@sarasouza_43 @victor117x" },
    { author: "be_macedo", content: "@duda_macedo01 @aline02sou" },
    { author: "isa_breitbarg", content: "@ree_cohen @belaliberman" },
    { author: "kira_jolie.york", content: "@lila_gio\n@vieiraaliandra" },
    { author: "paulodbraga_", content: "@kelyanededeusvieira @celsoedbraga" },
    { author: "blue____s2", content: "@zoodanath @brunasunshine" },
    {
        author: "mariaclarinhagalo12",
        content: "@sandradrguedes @sandraguedes1985",
    },
    {
        author: "mariaclarinhagalo12",
        content: "@sandraguedes1985 @sandradrguedes",
    },
    {
        author: "mariaclarinhagalo12",
        content: "@rodrigo_luciano_vaz @sandradrguedes",
    },
    { author: "mariaclarinhagalo12", content: "@rodrigo_luciano_vaz @show.petz" },
    {
        author: "mariaclarinhagalo12",
        content: "@sandraguedes1985 @sandradrguedes",
    },
    { author: "carolinemunielly", content: "@umcertolucas @mariadasilva2850" },
    {
        author: "carolinemunielly",
        content: "@crystal._calopsita @benjamimcalopsita_",
    },
    { author: "caiocalou", content: "@rafacorreia2530 @edna_cassia" },
    { author: "carolinemunielly", content: "@lilian.isabell @trindadelaila" },
    { author: "crystal._calopsita", content: "@trindadelaila @umcertolucas" },
    {
        author: "rafacorreia2530",
        content: "@laisecrisalmeida @neuzeirborgesdasilva",
    },
    { author: "rafacorreia2530", content: "@beatrzcorrea @lisianemartinez" },
    { author: "marcellamoraisf", content: "@starletleticia @elaine_paoli" },
    { author: "marcellamoraisf", content: "@ritadecassiamorais9 @tettisilva" },
    { author: "marcellamoraisf", content: "@starletleticia @elaine_paoli" },
    { author: "isadora.fabricio.77", content: "@mario234711" },
    { author: "isadora.fabricio.77", content: "@isado.ra2456" },
    { author: "paaty_almeida_", content: "@joyceemdfreitas @bruhbertoni" },
    { author: "paaty_almeida_", content: "@henrique.rosin @karinna_per" },
    { author: "stelagald", content: "@samillagoncalves53" },
    { author: "stelagald", content: "@gabigaldinob" },
    { author: "stelagald", content: "@samillagoncalves53" },
    { author: "stelagald", content: "@isabellagald" },
    { author: "stelagald", content: "@manuellagaldinoleao" },
    { author: "lu.__.nna", content: "@https_skarz @priv_da_laraa1" },
    { author: "lu.__.nna", content: "Eu perdi minhas 2 calopsitas" },
    { author: "lu.__.nna", content: "@diariodamel10 @lu_fernandes_san" },
    { author: "gabrielabocciat", content: "@mariane.xs @valentinazenere" },
    { author: "gabrielabocciat", content: "@larissa_queiroz.9 @bernardo29_sz" },
    { author: "gabrielabocciat", content: "@rhuanarantes24 @kaue_silva777" },
    { author: "gabrielabocciat", content: "@gtorezan @dulcepilissaro" },
    { author: "vitiregina", content: "@simone_alenski @si.mone.arte" },
    { author: "gabrielabocciat", content: "@lolita_pit @wlguimaraess" },
    { author: "vitiregina", content: "@dudamicavasconcelos @bebescabio" },
    { author: "vitiregina", content: "@flapelegrini @carolpilim" },
    { author: "vitiregina", content: "@nathy_broglieto @helennice5" },
    { author: "vitiregina", content: "@brupelegrini @caesargv" },
    { author: "nicolysantos19", content: "@marci.658 @calopsitalua" },
    { author: "arthuurxi04", content: "@homeroximenes @flavianeximenes" },
    { author: "vitorgabriel.barbosa.503", content: "@matheusskkk" },
    { author: "vitorgabriel.barbosa.503", content: "@lilah_santos51" },
    { author: "vitorgabriel.barbosa.503", content: "@ellen_lohh" },
    { author: "vitorgabriel.barbosa.503", content: "@rafaelmende_" },
    {
        author: "lindomarosvaldop.kanzler",
        content: "@maria_gabi2009 @tatyangela",
    },
    { author: "edna_daineze", content: "@_estela_bd_ @andreleandrodaineze" },
    { author: "_estela_bd_", content: "@edna_daineze @dainezeandreleandro" },
    { author: "laisdecosta", content: "@juju.bortoluzzi @daniela.bertoldi" },
    { author: "laisdecosta", content: "@paola_decosta @daiimayer" },
    { author: "paulacmb", content: "@andrerinco_ f @giovnnaftas" },
    { author: "paulacmb", content: "@emilia_thayna13 @claravicsora" },
    { author: "calopsitta_gigi", content: "@sergiohba @its.giovanna10" },
    {
        author: "bearruda",
        content: "@erikaeid e @cruzhjuliana Uma ideia linda para presentear os nossos embaixadores. O que acham? 😍",
    },
    {
        author: "luanagomesfeliciano",
        content: "@liviagomesfeliciano @emileinefeliciano",
    },
    { author: "vaniaventola", content: "@dorotyevangelista @dorlicanova" },
    { author: "claudiarabello_", content: "@blue_tuna01 @po.vig" },
    { author: "claudiarabello_", content: "@kenynha_r @patchukaa123" },
    { author: "calopsitas_apollo", content: "@wm_misanga @_.calopsitas._" },
    { author: "calopsitas_apollo", content: "@milou2665 @pipoca._.cacau" },
    {
        author: "calopsitas_apollo",
        content: "@babi_2403_ @freddyncocothecockatiels",
    },
    {
        author: "calopsitas_apollo",
        content: "@mango_and_chopper @zeca_calopista",
    },
    { author: "calopsitas_apollo", content: "@picita_cininho @filopsitaa" },
    { author: "calopsitas_apollo", content: "@nina_e_pituco_ @queso_the_tiel" },
    {
        author: "calopsitas_apollo",
        content: "@marcelo_e_fernanda_calopsitas @cacau_o_passarinho",
    },
    { author: "cinco_psitas", content: "@pipoco_santos @lulu_de_lua" },
    {
        author: "calopsitas_apollo",
        content: "@sol_.calopsita @calopsitafloquinho",
    },
    { author: "calopsitas_apollo", content: "@psitachico_ @torresmo_calopsita" },
    {
        author: "cinco_psitas",
        content: "@elisabeterodr1gues_ @fred_nina_zeca_chico",
    },
    { author: "calopsitas_apollo", content: "@calopsisters @koko64799" },
    {
        author: "calopsitas_apollo",
        content: "@amor_por_uma_psita @billiejean.calopsita",
    },
    { author: "calopsitas_apollo", content: "@pikachukiwi @alegria_em_penas" },
    { author: "cinco_psitas", content: "@o_mundodasaves @psittafamily" },
    { author: "cinco_psitas", content: "@psita_fenix @mcalopsita" },
    { author: "calopsitas_apollo", content: "@chico.psita01 @ticocalopsita_" },
    { author: "leticiabessaf", content: "@daanneevs_11 @gabriella_bessa" },
    {
        author: "calopsitas_apollo",
        content: "@psitas_whiteesunflower @criancao20",
    },
    { author: "cinco_psitas", content: "@psitas_lua_e_juju @harry_psita" },
    {
        author: "calopsitas_apollo",
        content: "@psita_luna_e_theo @princesa_psita_",
    },
    {
        author: "cinco_psitas",
        content: "@adrianasilva1188 @maurocesar.silva.501",
    },
    { author: "cinco_psitas", content: "@lunapenabranca @lian_lalika" },
    { author: "calopsitas_apollo", content: "@romeu_a.l @irmaosdinosaur" },
    {
        author: "calopsitas_apollo",
        content: "@josemiguel040711 @pipoca.ocalopsita",
    },
    {
        author: "calopsitas_apollo",
        content: "@juliamaria.calopsita @_euheuresco",
    },
    { author: "calopsitas_apollo", content: "@calopsitas.cha.bene @7923lo" },
    {
        author: "calopsitas_apollo",
        content: "@nina_psita03 @as_malucas_de_topete_ofc",
    },
    { author: "calopsitas_apollo", content: "@calopsitata @calopsitatica_" },
    { author: "calopsitas_apollo", content: "@mundoocalopsita @calopsita.goa" },
    {
        author: "maria_gabi2009",
        content: "@dianafeltrinkanzler @lindomarosvaldop.kanzler",
    },
    {
        author: "lucaas_teixeira",
        content: "@lerissa_fernanda @biancamodestobarbosa",
    },
    { author: "matosmoreiraandrea", content: "❤️" },
    { author: "heloisa.brand", content: "@heli.brand @anavolpatobrand" },
    { author: "daay.delfino", content: "@tm.lanza @edvangoulart" },
    { author: "isa_breitbarg", content: "@rodrigofleiss @belaliberman" },
    { author: "sobczaack", content: "@anac.coorrea @artesanocki" },
    { author: "sobczaack", content: "@julia.schumachers @gabi._.grein" },
    { author: "xsb_maryy", content: "@_.calopsitas_ @_wytdxxz" },
    { author: "sobczaack", content: "@luziaelisa_w @galvao_vanessa" },
    { author: "laraenes3", content: "@laraneenes @pipocaeamarelinha" },
    { author: "hemilly_ofc_", content: ".." },
    { author: "hemilly_ofc_", content: "." },
    { author: "hemilly_ofc_", content: "." },
    { author: "hemilly_ofc_", content: "." },
    { author: "hemilly_ofc_", content: "." },
    { author: "hemilly_ofc_", content: "Amo suas artes🙌❤️" },
    { author: "jessis.lopes", content: "@p.l.o.p.e.s @renata.ap.silva2" },
    { author: "jessis.lopes", content: "@debora_marquess_ @humbertolavinder" },
    { author: "jessis.lopes", content: "@deboracamposcp @na__luiza" },
    { author: "sueslem_paula", content: "@julianasilva5692 @jady.ferreira.18" },
    { author: "sueslem_paula", content: "@jucyar_a @nataliejsilva" },
    { author: "larhyca", content: "@leleu.s @luanagsr" },
    { author: "jessis.lopes", content: "@joyce.a.lopes @gabrielplutao" },
    { author: "monicasmelo", content: "@rdmlx @anayuuky" },
    { author: "monicasmelo", content: "@isamelo31 @adriano.floresta" },
    { author: "isagiandomenico", content: "@almir.cp @biaaa.andrade" },
    { author: "emilia_thayna13", content: "@kiko.brasileiro @arthurbarbosa2019" },
    { author: "emilia_thayna13", content: "@kiko.brasileiro @arthurbarbosa2019" },
    { author: "emilia_thayna13", content: "@alanafbispo @aliceraiane2" },
    { author: "emilia_thayna13", content: "@ivanilson138 @ivanidoleal" },
    { author: "emilia_thayna13", content: "@julia_ferreira.13 @kiko.brasileiro" },
    { author: "emilia_thayna13", content: "@emiilyvitoriiaa @emily_mota28" },
    {
        author: "emilia_thayna13",
        content: "@_dd7oficial @lucelia.bolos_e_docesdecorados",
    },
    { author: "emilia_thayna13", content: "@tony.hamsterr @tamirespaula_" },
    { author: "emilia_thayna13", content: "@josy__bp @josericardo6984" },
    { author: "emilia_thayna13", content: "@jose_thiaguinho @jose_thiaguinho" },
    {
        author: "emilia_thayna13",
        content: "@mano_el145 @joao_pedro_martins_sobral083",
    },
    {
        author: "emilia_thayna13",
        content: "@janailson.joao @joaopedromartins083",
    },
    { author: "emilia_thayna13", content: "@adrian.rha @johnnatah_silvaa" },
    { author: "emilia_thayna13", content: "@naiane_mnt @fernandaa06" },
    { author: "emilia_thayna13", content: "@nadia_luany @anny_kallyne20" },
    { author: "emilia_thayna13", content: "@marllonrochagomes @mano_el145" },
    { author: "emilia_thayna13", content: "@romariorocha06 @roosevelt.heria" },
    { author: "emilia_thayna13", content: "@josericardo3503 @ricadinho2011" },
    { author: "emilia_thayna13", content: "@josericardo6984 @ricardofilho107" },
    { author: "emilia_thayna13", content: "@roosevelt.heria @roosevelt.heria" },
    { author: "dudaxx__0", content: "@michellycristinamartins @mariachandelly" },
    { author: "emilia_thayna13", content: "@kiko.brasileiro @batistadavan" },
    { author: "emilia_thayna13", content: "@mariana_alvees19 @bruninhaa_alveez" },
    { author: "emilia_thayna13", content: "@mariana_alvees19 @bruninhaa_alveez" },
    {
        author: "emilia_thayna13",
        content: "@elianearaujodefarias @arthurbarbosa2019",
    },
    {
        author: "emilia_thayna13",
        content: "@arthurbarbosa2019 @elianearaujodefarias",
    },
    { author: "emilia_thayna13", content: "@amandaaraujo6470 @ketllyap" },
    { author: "emilia_thayna13", content: "@amandaaraujo6470 @ketllyap" },
    { author: "mayarapostal", content: "@ricardormendes_ @kaina.dutra" },
    { author: "emilia_thayna13", content: "@ellen_lorena25 @taniathayna2011" },
    { author: "emilia_thayna13", content: "@nadia_luany @ellen_lorena25" },
    { author: "emilia_thayna13", content: "@julia_ferreira.13 @190_veronica" },
    { author: "emilia_thayna13", content: "@190_veronica @veronica_3137" },
    { author: "emilia_thayna13", content: "@ellen_lorena25 @cpsantaluzia" },
    { author: "claravicsora", content: "@mirelatelless2.0 @ribinskiclarissa" },
    { author: "emilia_thayna13", content: "@ellen_lorena25 @nadialuany" },
    { author: "emilia_thayna13", content: "@rafaelarocha2625 @alexramon000" },
    { author: "emilia_thayna13", content: "@dixx_raparigueiros01 @aliceraiane2" },
    { author: "emilia_thayna13", content: "@rafaellaoam @monikyraianebrabosa" },
    { author: "emilia_thayna13", content: "@monicalima946 @monteiro.gas" },
    { author: "emilia_thayna13", content: "@taniathayna2011 @tamires_alvesz_" },
    { author: "zeca_psita_", content: "@freddy_and_mango @fredsilva4445" },
    { author: "emilia_thayna13", content: "@heloacostta @helloysan" },
    { author: "zeca_psita_", content: "@mariocalopsita @lonso.cath" },
    {
        author: "emilia_thayna13",
        content: "@anny_kallyne20 @kawany.vitoria.16144606",
    },
    {
        author: "emilia_thayna13",
        content: "@jose_thiaguinho @joao_pedro_martins_sobral083",
    },
    {
        author: "emilia_thayna13",
        content: "@julia_ferreira.13 @julia_ferreira1414",
    },
    { author: "zeca_psita_", content: "@chiclete_ea_kira.s2 @cockatiel.sanmao" },
    { author: "zeca_psita_", content: "@calopsitapetfeliz @amorporcalopsita94" },
    { author: "zeca_psita_", content: "@blue_calopsit @l_psitas" },
    { author: "zeca_psita_", content: "@amorinhaacalopsita @psitamel" },
    { author: "zeca_psita_", content: "@anto.bartolomeu @calopsitas_apollo" },
    { author: "zeca_psita_", content: "@dudaoliiveiraa__ @_stephanysilv" },
    { author: "zeca_psita_", content: "@costa_ana_paula15 @al3038796" },
    { author: "mairafrv", content: "@danielornelasribeiro @epagonzaga" },
    { author: "lulypontel", content: "@thaispontel @thainaa.13 @pontariaa_" },
    {
        author: "oswaldinho_chihuahua",
        content: "@mila_lhasaapso @thor_o_chiuaua",
    },
    { author: "oswaldinho_chihuahua", content: "@filipe.nasc @kaagalhardo" },
    { author: "oswaldinho_chihuahua", content: "@vanessapass.s @renatasheeny" },
    { author: "mihh__rodrigues", content: "@izabelabotelho @victor_pacifico" },
    { author: "alinunessz", content: "@danpadial @rebeca__nunes" },
    { author: "alinunessz", content: "@claralubs @clarandcc" },
    { author: "paulacmb", content: "@karinadesiqueiran @yaas_mim061" },
    { author: "paulacmb", content: "@_lucastxr @sthantomas" },
    { author: "paulacmb", content: "@natipadua @p_alv3s" },
    { author: "paulacmb", content: "@mauricio.marques_nt @ana_loliv" },
    { author: "paulacmb", content: "@quesiamorais @misquitaaa" },
    { author: "paulacmb", content: "@babi_rosal @rafael_4ntonio" },
];