const database = [
    { author: "mimi_crocheeatelie", content: "@donaeva_souza @jucolem" },
    {
        author: "mimi_crocheeatelie",
        content: "@juliasouza6522 @atelierlucrocheebijus",
    },
    { author: "mimi_crocheeatelie", content: "@evorinha @juliagramt" },
    { author: "mimi_crocheeatelie", content: "@nanath_assis @esdrasmourao" },
    {
        author: "mimi_crocheeatelie",
        content: "@maxizainesouzade @lana_souza_reis",
    },
    { author: "mimi_crocheeatelie", content: "@_gabis_souza_ @zelia6401" },
    { author: "mimi_crocheeatelie", content: "@mimirmiranda @michelesa27" },
    { author: "_gabis_souza_", content: "@zelia6401 @mimi_crocheeatelie" },
    { author: "mihh__rodrigues", content: "@cris_inaciio @lorenasilvavaz" },
    { author: "mihh__rodrigues", content: "@izabelabotelho @victor_pacifico" },
    { author: "jessis.lopes", content: "@deboracamposcp @na__luiza" },
    { author: "isa_breitbarg", content: "@silvialichand @fernandobreit" },
    { author: "laraenes3", content: "@laraneenes @pipocaeamarelinha" },
    { author: "isagiandomenico", content: "@thainacanario @thanicanario" },
    { author: "isagiandomenico", content: "@lohranmoraes @rosimeiremoraessilva" },
    { author: "lulypontel", content: "@thaispontel @thainaa.13 @pontariaa_" },
    { author: "emilia_thayna13", content: "@hellen123322 @cpsantaluzia" },
    { author: "emilia_thayna13", content: "@po.liana736 @maria._.julia._.14" },
    { author: "emilia_thayna13", content: "@carlos_gabriel.26 @cislley" },
    { author: "emilia_thayna13", content: "@tony.hamsterr @tony_hamste" },
    { author: "xsb_maryy", content: "@_.calopsitas_ @_wytdxxz" },
    { author: "mayarapostal", content: "@ricardormendes_ @kaina.dutra" },
    { author: "dudaxx__0", content: "@missxx_00 @kira_e_juju" },
    { author: "emilia_thayna13", content: "@rafaellaoam @monikyraianebrabosa" },
    { author: "emilia_thayna13", content: "@ivanilson138 @ivanidoleal" },
    { author: "emilia_thayna13", content: "@ivanilson138 @ivanidoleal" },
    { author: "sueslem_paula", content: "@julianasilva5692 @jady.ferreira.18" },
    { author: "xsb_maryy", content: "@isabellymedeiros._ @xbs.wyara" },
    { author: "emilia_thayna13", content: "@cislley @genival285" },
    { author: "emilia_thayna13", content: "@batistadavan @romariorocha06" },
    { author: "emilia_thayna13", content: "@190_veronica @helloysan" },
    { author: "emilia_thayna13", content: "@kiko.brasileiro @romariorocha06" },
    { author: "emilia_thayna13", content: "@190_veronica @veronica_3137" },
    { author: "mairafrv", content: "@edil_junior @thaysexavier" },
    { author: "emilia_thayna13", content: "@mano_el145 @marllonrochagomes" },
    { author: "emilia_thayna13", content: "@ellen_lorena25 @nadialuany" },
    {
        author: "liviagomesfeliciano",
        content: "@luanagomesfeliciano @emileinefeliciano",
    },
    { author: "emilia_thayna13", content: "@ellen_lorena25 @cpsantaluzia" },
    { author: "emilia_thayna13", content: "@romariorocha06 @roosevelt.heria" },
    {
        author: "hemilly_ofc_",
        content: "@joselma.goudard @wellingtonfonsecafonseca",
    },
    { author: "leticiabessaf", content: "@gabriella_bessa @edilainy45" },
    { author: "emilia_thayna13", content: "@julia_ferreira.13 @190_veronica" },
    {
        author: "emilia_thayna13",
        content: "@ellen_lorena25 @elianearaujodefarias",
    },
    { author: "emilia_thayna13", content: "@josericardo3503 @mariajbcorreia" },
    { author: "emilia_thayna13", content: "@marllonrochagomes @mano_el145" },
    { author: "hemilly_ofc_", content: "@julia_ribeiro_br @mariacardoso4_" },
    { author: "emilia_thayna13", content: "@josericardo3503 @ricadinho2011" },
    { author: "calopsitas_apollo", content: "@pet.kiko @mel.mmelinda" },
    { author: "emilia_thayna13", content: "@jose_thiaguinho @mariia_eduuarda07" },
    { author: "emilia_thayna13", content: "@anny_kallyne20 @helloysan" },
    { author: "sobczaack", content: "@_fernanda.agnes @laizoca__" },
    { author: "sobczaack", content: "@helevenberger @eduarda_vazz" },
    { author: "sobczaack", content: "@luanoski @fernando.jmartins" },
    { author: "calopsitas_apollo", content: "@tedcalopsita_ @bilu_hulk" },
    { author: "claravicsora", content: "@mirelatelless2.0 @ribinskiclarissa" },
    { author: "calopsitas_apollo", content: "@avesciths @psitaamendoim_" },
    { author: "calopsitas_apollo", content: "@picita_cininho @filopsitaa" },
    { author: "oswaldinho_chihuahua", content: "@lllfreitas @luckperezz" },
    { author: "calopsitas_apollo", content: "@calopsitata @calopsitatica_" },
    { author: "calopsitas_apollo", content: "@sextetodeasas @marceloninojr" },
    { author: "calopsitas_apollo", content: "@raven.ringneck @vitoriabibi_" },
    { author: "oswaldinho_chihuahua", content: "@rafacdantas @nair0611" },
    { author: "calopsitas_apollo", content: "@_griseplata_ @calopsitabryan" },
    { author: "calopsitas_apollo", content: "@psitachico_ @torresmo_calopsita" },
    { author: "calopsitas_apollo", content: "@soylunalunitaa @apolocallopsita" },
    { author: "emilia_thayna13", content: "@cislley @maraparecida2672" },
    { author: "emilia_thayna13", content: "@taniathayna2011 @tony.hamsterr" },
    {
        author: "oswaldinho_chihuahua",
        content: "@mila_lhasaapso @thor_o_chiuaua",
    },
    {
        author: "calopsitas_apollo",
        content: "@sol_.calopsita @calopsitafloquinho",
    },
    {
        author: "calopsitas_apollo",
        content: "@didyogalvao @josemiguel_saxofonista",
    },
    { author: "emilia_thayna13", content: "@tony.hamsterr @taniathayna2011" },
    {
        author: "emilia_thayna13",
        content: "@arthurbarbosa2019 @elianearaujodefarias",
    },
    { author: "calopsitas_apollo", content: "@pitucoo_acalopsita @mariana.m.s1" },
    {
        author: "calopsitas_apollo",
        content: "@calopsitas_e_periquitos @ninozinhopsita",
    },
    {
        author: "calopsitas_apollo",
        content: "@babi_2403_ @freddyncocothecockatiels",
    },
    { author: "emilia_thayna13", content: "@ellen_lorena25 @taniathayna2011" },
    { author: "emilia_thayna13", content: "@aliceraiane2 @mariagabryella13" },
    {
        author: "emilia_thayna13",
        content: "@mano_el145 @joao_pedro_martins_sobral083",
    },
    {
        author: "emilia_thayna13",
        content: "@elianearaujodefarias @arthurbarbosa2019",
    },
    { author: "paulacmb", content: "@pedronutch @camillyuchoa" },
    { author: "paulacmb", content: "@opaulovicta @nataliaoliveira.6" },
    {
        author: "robsilvmaraninchi",
        content: "@dayaneschmidt @lucianasilveira___",
    },
    { author: "paulacmb", content: "@danichaseliov @carlinhadiiaas" },
    { author: "zeca_psita_", content: "@blue_calopsit @l_psitas" },
    { author: "paulacmb", content: "@vinao0 @estefanny_braga" },
    { author: "calopsitas_apollo", content: "@mundoocalopsita @calopsita.goa" },
    { author: "calopsitas_apollo", content: "@pikachukiwi @alegria_em_penas" },
    { author: "calopsitas_apollo", content: "@calopsitas.cha.bene @7923lo" },
    { author: "zeca_psita_", content: "@anto.bartolomeu @calopsitas_apollo" },
    { author: "zeca_psita_", content: "@freddy_and_mango @fredsilva4445" },
    { author: "zeca_psita_", content: "@calopsitapetfeliz @amorporcalopsita94" },
    { author: "zeca_psita_", content: "@costa_ana_paula15 @al3038796" },
    {
        author: "calopsitas_apollo",
        content: "@calopsitaternurinha @calopsitaternurinha",
    },
    { author: "cinco_psitas", content: "@pipoco_santos @lulu_de_lua" },
    { author: "cinco_psitas", content: "@lunapenabranca @lian_lalika" },
    { author: "cinco_psitas", content: "@o_mundodasaves @psittafamily" },
    { author: "cinco_psitas", content: "@marcelocalopsita @ringneck_messi" },
    { author: "cinco_psitas", content: "@cecilia.nogueira687 @juliananunes114" },
    { author: "emilia_thayna13", content: "@mariajulianafreitas8 @pvd.maarys" },
    {
        author: "cinco_psitas",
        content: "@elisabeterodr1gues_ @fred_nina_zeca_chico",
    },
    { author: "hemilly_ofc_", content: ".." },
    { author: "hemilly_ofc_", content: "." },
    { author: "hemilly_ofc_", content: "." },
    { author: "hemilly_ofc_", content: "." },
    { author: "hemilly_ofc_", content: "." },
    { author: "hemilly_ofc_", content: "." },
    { author: "hemilly_ofc_", content: "." },
    { author: "hemilly_ofc_", content: "." },
    { author: "calopsitas_apollo", content: "@milou2665 @pipoca._.cacau" },
    {
        author: "calopsitas_apollo",
        content: "@lua_calopsitaa @calopsita_princeso",
    },
    { author: "calopsitata", content: "@alicenazato @annajulia.bfonseca" },
    { author: "calopsitas_apollo", content: "@calopicita.nick @romeuu_cg" },
    {
        author: "calopsitas_apollo",
        content: "@minha_cria_passaros_e_hamster @tucco_calopsita",
    },
    { author: "calopsitas_apollo", content: "@quinmiran @elvis_psita_ofc" },
    { author: "calopsitas_apollo", content: "@wm_misanga @_.calopsitas._" },
    { author: "calopsitas_apollo", content: "@nicco_opicurita @crisenino" },
    { author: "calopsitas_apollo", content: "@mundoocalopsita @calopsita.goa" },
    { author: "claudiarabello_", content: "@kenynha_r @patchukaa123" },
    { author: "claudiarabello_", content: "@__ac3rola__ @adalgizasilva" },
    { author: "vaniaventola", content: "@gabrielavmarra @raquel.ventola" },
    {
        author: "bearruda",
        content: "@erikaeid e @cruzhjuliana Uma ideia linda para presentear os nossos embaixadores. O que acham? 😍",
    },
    { author: "paulacmb", content: "@emilia_thayna13 @claravicsora" },
    { author: "paulacmb", content: "@andrerinco_ f @giovnnaftas" },
    { author: "laisdecosta", content: "@juju.bortoluzzi @daniela.bertoldi" },
    { author: "edna_daineze", content: "@_estela_bd_ @andreleandrodaineze" },
    {
        author: "lindomarosvaldop.kanzler",
        content: "@maria_gabi2009 @tatyangela",
    },
    { author: "vitorgabriel.barbosa.503", content: "@ellen_lohh" },
    { author: "vitorgabriel.barbosa.503", content: "@lilah_santos51" },
    { author: "vitorgabriel.barbosa.503", content: "@matheusskkk" },
    { author: "arthuurxi04", content: "@homeroximenes @flavianeximenes" },
    { author: "vitiregina", content: "@cahmica_ @daphnits" },
    { author: "gabrielabocciat", content: "@cinthiarba @luttx_" },
    { author: "gabrielabocciat", content: "@yagostephano @_gguedees" },
    { author: "gabrielabocciat", content: "@gtorezan @dulcepilissaro" },
    { author: "vitiregina", content: "@nando_sm10 @vickyninafamily" },
    {
        author: "adrianavasconcellosp",
        content: "@messicalopsita @calopsitas_mansa",
    },
    {
        author: "adrianavasconcellosp",
        content: "@calopsitaboss @calopsita_thoor",
    },
    { author: "lu.__.nna", content: "@maisa_cerqueira_ @uplucian" },
    { author: "lu.__.nna", content: "@lara31303 @_lisgabrielle" },
    { author: "lu.__.nna", content: "@lene_764 @lojaisamel12" },
    { author: "angelica_fsouza", content: "@angferreira @leonicardosodesouza" },
    { author: "stelagald", content: "@manuellagaldinoleao" },
    { author: "stelagald", content: "@isabellagald" },
    { author: "stelagald", content: "@samillagoncalves53" },
    { author: "stelagald", content: "@gabigaldinob" },
    {
        author: "idealizzarepresentes",
        content: "@danirmartinijunior @grasielakrumenauer",
    },
    { author: "teddy_o_chede", content: "@rafagastaldello @apolo_caopanheiro" },
    { author: "teddy_o_chede", content: "@thaynagarbellotti @historiadecao" },
    {
        author: "sabrinafernandesdesantana",
        content: "@geovanaa_zz @taliita_cerqueira",
    },
    { author: "sabrinafernandesdesantana", content: "❤️" },
    { author: "sabrinafernandesdesantana", content: "❤️" },
    { author: "laura.tinti", content: "@tharsis.f @nabiamaria" },
    { author: "laura.tinti", content: "@dubarbosa.arq @ferpenna" },
    { author: "zoeypapagaiadocongo", content: "@diariodeaves @cacauacacatua" },
    { author: "laura.tinti", content: "@marinatinti @tintirosangela" },
    { author: "emanueledou", content: "@roneymarani @cute.lil.kitten7" },
    { author: "rosimerebatista555", content: "@val_campos15" },
    { author: "rosimerebatista555", content: "@victorhugohugo108" },
    {
        author: "bunnyxxmilly",
        content: "@julia_kjkkl @hyozin_.miojin quero uma da lolita véi",
    },
    { author: "_biah.bijuss", content: "@beatriz_pier312" },
    { author: "_biah.bijuss", content: "@elainebperez" },
    { author: "sun.piusitas", content: "@giigumiero @jorge_eduardo_neris" },
    { author: "sun.piusitas", content: "@giigumiero @jorge_eduardo_neris" },
    { author: "sun.piusitas", content: "@giigumiero @jorge_eduardo_neris" },
    { author: "sun.piusitas", content: "@giigumiero @jorge_eduardo_neris" },
    { author: "sun.piusitas", content: "@silvia.lobo.940 @_marisanogueira" },
    { author: "sun.piusitas", content: "@silvia.lobo.940 @_marisanogueira" },
    { author: "sun.piusitas", content: "@_juliana_proenca @th_tasteofhoney" },
    { author: "sun.piusitas", content: "@_juliana_proenca @th_tasteofhoney" },
    { author: "_marisanogueira", content: "@cacaualecrim , @irinanogueira" },
    {
        author: "_marisanogueira",
        content: "@geovannanogueira , @chelle.nogueira",
    },
    { author: "_marisanogueira", content: "@kitygrejo , @raimi_oficial" },
    { author: "_marisanogueira", content: "@s" },
    {
        author: "marina_cristina.pilz",
        content: "@ricardoluiz.carneiro @grazielaseidel",
    },
    { author: "marina_cristina.pilz", content: "@gabipykocz @naluaraa" },
    { author: "kiko.brasileiro", content: "@kanky_13 @katie_the_bull" },
    { author: "kiko.brasileiro", content: "@anny_kallyne20 @kyrashihtzu_" },
    { author: "kiko.brasileiro", content: "@emilia_thayna13 @wiwuwgevi" },
    { author: "kiko.brasileiro", content: "@emilia_thayna13 @julia_ferreira.13" },
    { author: "kiko.brasileiro", content: "@julia_ferreira.13 @tony.hamsterr" },
    { author: "kiko.brasileiro", content: "@tony.hamsterr @emilia_thayna13" },
    { author: "kiko.brasileiro", content: "@taniathayna2011 @batistadavan" },
    { author: "kiko.brasileiro", content: "@batalhas_e_vitorias @batistadavan" },
    { author: "kiko.brasileiro", content: "@batistadavam @taniathayna2011" },
    { author: "kiko.brasileiro", content: "@emilia_thayna13 @helloysan" },
    { author: "kiko.brasileiro", content: "@cislley @puku_bird" },
    { author: "kiko.brasileiro", content: "@julia_ferreira.13 @tony.hamsterr" },
    { author: "kiko.brasileiro", content: "@arthurbarbosa2019 @emilia_thayna13" },
    { author: "kiko.brasileiro", content: "@taniathayna2011 @batistadavan" },
    { author: "kiko.brasileiro", content: "@batistadavan @taniathayna2011" },
    {
        author: "kiko.brasileiro",
        content: "@mickey.pequines @joaopedroleitedeoliveira2008",
    },
    { author: "kiko.brasileiro", content: "@ellen_lorena25 @nadia_luany" },
    { author: "kiko.brasileiro", content: "@nadia_luany @anny_kallyne20" },
    { author: "kiko.brasileiro", content: "@nadia_luany @ellen_lorena25" },
    { author: "kiko.brasileiro", content: "@bella.e_lua028 @don_frida_e_lola" },
    { author: "kiko.brasileiro", content: "@romeuejulieta967 @meg.rodrigues01" },
    { author: "kiko.brasileiro", content: "@yasx_hk @_bella_e_bruce" },
    { author: "kiko.brasileiro", content: "@bruninhaa_alveez @aliceraiane2" },
    { author: "kiko.brasileiro", content: "@pandorababyrott @romeuejulieta967" },
    { author: "kiko.brasileiro", content: "@emilia_thayna13 @romariorocha06" },
    { author: "emilia_thayna13", content: "@david_luan_araujo @camillymaria__" },
    {
        author: "emilia_thayna13",
        content: "@kawany.vitoria.16144606 @_giselly_kaepstick",
    },
    { author: "emilia_thayna13", content: "@00__amannda @taniathayna2011" },
    {
        author: "emilia_thayna13",
        content: "@taniathayna2011 @raiane.barbosa.16906",
    },
    {
        author: "emilia_thayna13",
        content: "@arthurbarbosa2019 @julia_ferreira.13",
    },
    { author: "emilia_thayna13", content: "@julia_ferreira.13 @tony.hamsterr" },
    { author: "emilia_thayna13", content: "@tony_hamste @periquita_enjoada" },
    { author: "emilia_thayna13", content: "@kiko.brasileiro @_brn_alves" },
    { author: "emilia_thayna13", content: "@kiko.brasileiro @_brn_alves" },
    { author: "emilia_thayna13", content: "@kiko.brasileiro @_brn_alves" },
    { author: "emilia_thayna13", content: "@julia_ferreira.13 @kiko.brasileiro" },
    { author: "emilia_thayna13", content: "@tony.hamsterr @kiko.brasileiro" },
    { author: "emilia_thayna13", content: "@tony_hamste @batistadavan" },
    {
        author: "emilia_thayna13",
        content: "@joaopedromartins083 @jose_thiaguinho",
    },
    { author: "emilia_thayna13", content: "@josericardo6984 @josy__bp" },
    { author: "isabelapedrosodasilva", content: "@bijusdaisa20 @cinco_psitas" },
    {
        author: "isabelapedrosodasilva",
        content: "@bihamaral_ @marianasoutosantana",
    },
    {
        author: "isabelapedrosodasilva",
        content: "@adrianasilva1188 @maurocesar.silva.501",
    },
    {
        author: "isabelapedrosodasilva",
        content: "@gaudencio_agp @juliananunes114",
    },
    { author: "emilia_thayna13", content: "@emiilyvitoriiaa @aliceraiane2" },
    { author: "emilia_thayna13", content: "@aliceraiane2 @romariorocha06" },
    { author: "emilia_thayna13", content: "@janetef020 @021_felipee__" },
    { author: "emilia_thayna13", content: "@021_felipee__ @janetef020" },
    { author: "emilia_thayna13", content: "@po.liana736 @pose_do_brow2019" },
    { author: "emilia_thayna13", content: "@arthurbarbosa2019 @kiko.brasileiro" },
    {
        author: "isabelapedrosodasilva",
        content: "@psita.senior @psitas_lua_e_juju",
    },
    { author: "isabelapedrosodasilva", content: "@anto.bartolomeu @psita_fenix" },
    { author: "isabelapedrosodasilva", content: "@lunapenabranca @psitashouse" },
    {
        author: "isabelapedrosodasilva",
        content: "@pituco_pisita @pequenograndeboris_",
    },
    { author: "isabelapedrosodasilva", content: "@tatis.psitas @isa.psitas" },
    { author: "isabelapedrosodasilva", content: "@sextetodeasas @harry_psita" },
    { author: "estherfitti", content: "@cristianofittipald @sylvia.fittipaldi" },
    { author: "estherfitti", content: "@genipedrosafittipaldi @pedrosa.katia" },
    { author: "kiko.brasileiro", content: "@su_koki__ @periquita_enjoada" },
    { author: "kiko.brasileiro", content: "@su_koki__ @periquita_enjoada" },
    { author: "kiko.brasileiro", content: "@su_koki_ @periquita_enjoada" },
    { author: "kiko.brasileiro", content: "@periquita_enjoada @mickey.pequines" },
    { author: "kiko.brasileiro", content: "@su_koki__ @sublime.natureza" },
    { author: "kiko.brasileiro", content: "@pandorababyrott @romario_aks" },
    { author: "kiko.brasileiro", content: "@wellizimmer @puku_bird" },
    {
        author: "kiko.brasileiro",
        content: "@ursinhos____carinhosos @uragano_dea",
    },
    { author: "kiko.brasileiro", content: "@ursoezaiaeshelby @pittyeursinha" },
    { author: "kiko.brasileiro", content: "@ursinhaamoraa @ursinhachowchow" },
    {
        author: "kiko.brasileiro",
        content: "@criadouro.mandarim @criadourosantacristina",
    },
    { author: "andrielekleitzke", content: "@vaniraknopp @suelenewald" },
    { author: "andrielekleitzke", content: "@cristian_knopp @krolownatalia" },
    { author: "gabrielabocciat", content: "@bernardo29_sz @luttx_" },
    { author: "gabrielabocciat", content: "@soares_caroline00 @anninha_l.r" },
    { author: "gabrielabocciat", content: "@bragagiuu @ogbielzxn" },
    { author: "rafaellaoam", content: "@diego_diur @yduayer" },
    { author: "rafaellaoam", content: "@yarabvs @immoonl" },
    { author: "rafaellaoam", content: "@luiza_carvalho8 @_ojuliana" },
    { author: "nina.epipoca", content: "@calopsita_thoor @calo.psitalindas" },
    { author: "nina.epipoca", content: "@calopsita.18 @catarinasbaby" },
    {
        author: "nina.epipoca",
        content: "@bolinha_e_caio @calopsita_diegoemanoel",
    },
    { author: "calopze", content: "@guilherme.fari.75839923 @fiona_acalop" },
    { author: "calopze", content: "@roselamulticolorida @ninocalopsita2022" },
    { author: "calopze", content: "@calopsita_messiesol @calop.fofa1nick" },
    { author: "megan.retriever", content: "@flaviamabueno @giijensbz" },
    { author: "megan.retriever", content: "@veh.bueno @jose_bananinha" },
    {
        author: "kiko.brasileiro",
        content: "@calopsitaslolaecharlie @calopscleiton_7l",
    },
    { author: "kiko.brasileiro", content: "@calopscleiton_7l @bebepsita" },
    { author: "kiko.brasileiro", content: "@calopsita._.tico @psitamel" },
    { author: "kiko.brasileiro", content: "@amorporcalopsita94 @bebepsita" },
    { author: "kiko.brasileiro", content: "@ferret.diego @tadeu.lulu" },
    { author: "kiko.brasileiro", content: "@juca_frajolinha @pandorababyrott" },
    {
        author: "kiko.brasileiro",
        content: "@juca_frajolinha @tayguer_2021americanbully",
    },
    {
        author: "kiko.brasileiro",
        content: "@mari.e.tata.ofc @familia_calopsitaa",
    },
    { author: "kiko.brasileiro", content: "@nina_tico_calopsitas @ninyca16" },
    { author: "kiko.brasileiro", content: "@nina_dog_20 @nina_tico_calopsitas" },
    { author: "kiko.brasileiro", content: "@ninacalopst @apollo_jaack" },
    {
        author: "kiko.brasileiro",
        content: "@king_apollored @vida_de_calopsitas_",
    },
    { author: "kiko.brasileiro", content: "@yorks_and_the_west @yasx_hk" },
    { author: "kiko.brasileiro", content: "@yorks_and_the_west @yasx_hk" },
    { author: "kiko.brasileiro", content: "@yellowbirbb @zoey.ragdoll" },
    { author: "kiko.brasileiro", content: "@emilia_thayna13 @nt.norma" },
    { author: "kiko.brasileiro", content: "@zulema_bordie @pandorah.50" },
    { author: "kiko.brasileiro", content: "@emilia_thayna13 @tadeu.lulu" },
    { author: "kiko.brasileiro", content: "@winnie.baby_ @chowchowbsbsbsb" },
    {
        author: "kiko.brasileiro",
        content: "@korella.mix.official @chicletinhodapandora",
    },
    { author: "kiko.brasileiro", content: "@lupita_bastos @bata.ta0309" },
    { author: "kiko.brasileiro", content: "@deaativsadohrnduens @lizzie281020" },
    { author: "kiko.brasileiro", content: "@miaucademia @jonsnowthespitz" },
    { author: "kiko.brasileiro", content: "@jose_luan_244 @lhasa.horacio" },
    { author: "kiko.brasileiro", content: "@hope_maya_dog @scooby.cm" },
    { author: "kiko.brasileiro", content: "@luninha.lindaaa @one_crazy_doodle" },
    { author: "kiko.brasileiro", content: "@lilyadotada @lilica_psita" },
    { author: "kiko.brasileiro", content: "@_shihtzu_liz_ @liz.calopsita1888" },
    { author: "kiko.brasileiro", content: "@carlos_gabriel.26 @gabriiel___011" },
    { author: "kiko.brasileiro", content: "@emilia_thayna13 @kanky_13" },
    { author: "kiko.brasileiro", content: "@emilia_thayna13 @mmanu_ferreira.11" },
    { author: "kiko.brasileiro", content: "@roselamulticolorida @guineaapiig" },
    { author: "ninadestro", content: "@dehcg @tatalvess" },
    {
        author: "kiko.brasileiro",
        content: "@yasx_hk @joaopedroleitedeoliveira2008",
    },
    { author: "kiko.brasileiro", content: "@emilia_thayna13 @one_crazy_doodle" },
    { author: "kiko.brasileiro", content: "@wanessa2609 @one_crazy_doodle" },
    { author: "kiko.brasileiro", content: "@wanessa2609 @one_crazy_doodle" },
    {
        author: "kiko.brasileiro",
        content: "@osbulldogs.fofa_bolota @senhoritadog",
    },
    { author: "kiko.brasileiro", content: "@icarocalopsita @shihtzu_tokyo_20" },
    { author: "kiko.brasileiro", content: "@will__lola @music_ehsasi88" },
    { author: "kiko.brasileiro", content: "@calopsitaslolaecharlie @luizgvs" },
    { author: "kiko.brasileiro", content: "@julia_ferreira.13 @emilia_thayna13" },
    { author: "_nataliaanunes", content: "@carolcnunis @sonia.nunes.7739814" },
    { author: "isa_k_14", content: "@alessandra1822021" },
    { author: "isa_k_14", content: "@brendanacleto_" },
    { author: "nicolepmota_", content: "@jmots_ @gilbertoportapilla" },
    { author: "nicolepmota_", content: "@rosisilvamota @marcolamota" },
    {
        author: "nicolepmota_",
        content: "@luciana_elivelto_monteiro @fernandaaasz3",
    },
    { author: "dudaxx__0", content: "@keanu_reeves_anao @edna.ldo51" },
    { author: "aanacmarques", content: "@carlos.zoo @nataliamarques.eng" },
    { author: "aanacmarques", content: "@raphaelagraciane @gracianejaqueline" },
    { author: "emilia_thayna13", content: "@kiko.brasileiro @julia_ferreira.13" },
    { author: "batistadavan", content: "@emilia_thayna13 @arthurbarbosa2019" },
    { author: "batistadavan", content: "@tony_hamste @tony.hamsterr" },
    { author: "batistadavan", content: "@yoon__a0213 @tony.hamsterr" },
    { author: "batistadavan", content: "@julia_ferreira.13 @emilia_thayna13" },
    {
        author: "rrroseskt_ted_e_lolo_yorkshire",
        content: "@prici.marques @rosangela.mafs",
    },
    { author: "prici.marques", content: "@sofia.yorkfofa @neusarborin" },
    { author: "prici.marques", content: "@borinsueli @jeferson_nardelli" },
    { author: "prici.marques", content: "@gleme99 @luzaccariotto" },
    { author: "tres.psitas", content: "@luanroier @nandadavanzo" },
    { author: "tres.psitas", content: "@evelyncrt @evibvbatista" },
    { author: "tres.psitas", content: "@paulacfortuna @paulagonzatto" },
    { author: "tres.psitas", content: "@karenserafini91 @stefanifavaro" },
    { author: "tres.psitas", content: "@paulofgraffoliveira @erikadavanzo" },
    { author: "tres.psitas", content: "@andreiadavanzo @carla_davanzo" },
    { author: "tres.psitas", content: "@zoeypapagaiadocongo @zoologico_pet" },
    { author: "tres.psitas", content: "@alvocalopsita @calopsitassuzuki" },
    { author: "tres.psitas", content: "@peninhascrazy @peninhasdeamor" },
    { author: "tres.psitas", content: "@caju_psitas @blu.calopsita" },
    { author: "tres.psitas", content: "@araras_blogueirinhas @psitasdabea" },
    { author: "tres.psitas", content: "@cookieoltiel @juca.ringneck" },
    { author: "tres.psitas", content: "@sun.piusitas @calopsitascamaradas" },
    { author: "cookie_calopsita_", content: "@be_macedo @viniciusjoaquimpania" },
    { author: "cookie_calopsita_", content: "@tres.psitas @piupets" },
    {
        author: "filhos_de_penas10",
        content: "@fabio.gomes.395017 @fabio_lira_123",
    },
    { author: "filhos_de_penas10", content: "@amorinhapsita30 @amor_de_blue" },
    { author: "filhos_de_penas10", content: "@chiquinhomello @turma.do.buero" },
    {
        author: "filhos_de_penas10",
        content: "@amigo.depenasepelos @amendoimbicotinha",
    },
    { author: "filhos_de_penas10", content: "@samia.antonio.77 @marcelo_e_ruth" },
    { author: "filhos_de_penas10", content: "@luluzinhacalopsita @loves.psitas" },
    { author: "filhos_de_penas10", content: "@messicalopsita @kiwi.mestre" },
    {
        author: "filhos_de_penas10",
        content: "@matheusaraujo366 @marieagatinhasiames",
    },
    {
        author: "filhos_de_penas10",
        content: "@cantinho_das_aves_mg @rinthegalah",
    },
    { author: "filhos_de_penas10", content: "@ringneck_messi @ringspet_love" },
    { author: "filhos_de_penas10", content: "@ricoperiquito @rio.calops" },
    { author: "filhos_de_penas10", content: "@pipa_teteu_calops @harry_psita" },
    {
        author: "filhos_de_penas10",
        content: "@lusineteximenes123 @gislane_ximenees",
    },
    {
        author: "filhos_de_penas10",
        content: "@renatamelo.mesquita @tamirispaiva44",
    },
    { author: "filhos_de_penas10", content: "@thaismelo584 @thaismello121" },
    { author: "filhos_de_penas10", content: "@criadouro_r.s @criadourowings" },
    {
        author: "filhos_de_penas10",
        content: "@leandraloiola2013 @calopsitas_lelo.branco",
    },
    { author: "filhos_de_penas10", content: "@amazona_verde @amarelinha6454" },
    { author: "filhos_de_penas10", content: "@piueozzy @olaf_calopsita_1" },
    { author: "filhos_de_penas10", content: "@_saras2109 @janilmamelo" },
    { author: "filhos_de_penas10", content: "@abelcalopsita @leno_abel" },
    { author: "filhos_de_penas10", content: "@belinha_psita_ @psitandogram" },
    {
        author: "filhos_de_penas10",
        content: "@bela_e_falcao_calopsita @belchior_calopsita",
    },
    { author: "filhos_de_penas10", content: "@calopsita.gaspar @galvao.bird_" },
    { author: "filhos_de_penas10", content: "@coelha_sophia @floquinho.coelho" },
    {
        author: "filhos_de_penas10",
        content: "@marcelocalopsita @calopsitas_da_mah",
    },
    { author: "filhos_de_penas10", content: "@mporpeta @clhoe_maya" },
    { author: "filhos_de_penas10", content: "@jhon.lua @alvocalopsita" },
    { author: "filhos_de_penas10", content: "@psitashouse @caju_psitas" },
    {
        author: "filhos_de_penas10",
        content: "@_criadouro_o_mundo_das_aves @cantinho_das_aves_mg",
    },
    { author: "filhos_de_penas10", content: "@kfelixart @ringneck.kiwi" },
    {
        author: "filhos_de_penas10",
        content: "@zoeypapagaiadocongo @o_mundodasaves",
    },
    {
        author: "filhos_de_penas10",
        content: "@marcela.paiva.395 @brunavasconcelos2011hotmailcom",
    },
    { author: "filhos_de_penas10", content: "@marcelo_e_ruth @samia.antonio.77" },
    { author: "filhos_de_penas10", content: "@lana_melo_1023 @luno123343" },
    {
        author: "filhos_de_penas10",
        content: "@theo_o_calopsita @calopsita_thoor",
    },
    {
        author: "filhos_de_penas10",
        content: "@avesdabia @recantodasaves_miriamvieira",
    },
    {
        author: "filhos_de_penas10",
        content: "@jaqueline.melo296 @pandora_rosela",
    },
    { author: "filhos_de_penas10", content: "@fa_bio904 @plantelfamiliapaixao" },
    {
        author: "filhos_de_penas10",
        content: "@chaguinha.m.o @fabio.gomes.395017",
    },
    {
        author: "filhos_de_penas10",
        content: "@o_mundodasaves @familia_calopsita_omaki",
    },
    { author: "filhos_de_penas10", content: "@avesdabia @aves.do.amor" },
    { author: "filhos_de_penas10", content: "@pdi.calopsitas @faroldasaves" },
    {
        author: "filhos_de_penas10",
        content: "@coelhinho_apolo @coelhos_nina_e_nick",
    },
    { author: "filhos_de_penas10", content: "@lunacalopsita_ @pets_da_dodo_" },
    { author: "filhos_de_penas10", content: "@pet_rosela @pets.damila" },
    {
        author: "filhos_de_penas10",
        content: "@alexandreadrianna @andreiasoares2809",
    },
    { author: "filhos_de_penas10", content: "@thecalopsita @turma.do.buero" },
    {
        author: "filhos_de_penas10",
        content: "@amanda_parrots @calopsita.amarela",
    },
    {
        author: "filhos_de_penas10",
        content: "@theo_o_calopsita @calopsita_thoor",
    },
    {
        author: "filhos_de_penas10",
        content: "@joaoechicafofinhus @joaopedro.calopsita",
    },
    {
        author: "filhos_de_penas10",
        content: "@babynicolas8366 @samia.antonio.77",
    },
    { author: "filhos_de_penas10", content: "@filhosdepenas3 @leticiaalvees20" },
    {
        author: "filhos_de_penas10",
        content: "@lucianosilva3597 @leticiaalvees20",
    },
    { author: "filhos_de_penas10", content: "@anto.bartolomeu @antoniokaua0907" },
    { author: "filhos_de_penas10", content: "@matheuss.euu @mamae_anthonyy" },
    { author: "filhos_de_penas10", content: "@babypisita2021 @baby_bencao_2021" },
    { author: "filhos_de_penas10", content: "@lunacalopsita_ @psita.lily" },
    { author: "filhos_de_penas10", content: "@amorinhapsita30 @peninhasdeamor" },
    {
        author: "filhos_de_penas10",
        content: "@vida_com_psita @familia_penudinhos",
    },
    {
        author: "filhos_de_penas10",
        content: "@lolaporquinha_ @familiapsitacidea",
    },
    { author: "filhos_de_penas10", content: "@layla.hering @lulu_de_lua" },
    { author: "filhos_de_penas10", content: "@antonia094156 @lana_melo_1023" },
    { author: "filhos_de_penas10", content: "@alex__cockatiel @mundo_psita" },
    { author: "filhos_de_penas10", content: "@bruce_opastoralemao @brun4mello" },
    {
        author: "filhos_de_penas10",
        content: "@perolafilhadepena @brunavasconcelos2011hotmailcom",
    },
    { author: "filhos_de_penas10", content: "@familia.pius @belpsita" },
    { author: "filhos_de_penas10", content: "@marcela.paiva.395 @tatianemelo97" },
    { author: "filhos_de_penas10", content: "@thaismelo112 @marcelocalopsita" },
    {
        author: "filhos_de_penas10",
        content: "@zoeypapagaiadocongo @zoe_calopsita_",
    },
    { author: "batistadavan", content: "@julia_ferreira.13 @tony.hamsterr" },
    {
        author: "aanacmarques",
        content: "@marcosdmarques_ @raphaela_sobrancelhas",
    },
    { author: "kiko.brasileiro", content: "@julia_ferreira.13 @emilia_thayna13" },
    { author: "isshimoto", content: "@leucostaj @pandoraaaamstaff_" },
    { author: "kiko.brasileiro", content: "@gabriiel___011 @gaboandre.07" },
    { author: "kiko.brasileiro", content: "@chihuahua.lilipaz20 @lilica_psita" },
    { author: "kiko.brasileiro", content: "@emilia_thayna13 @jack_ring_neck_" },
    { author: "kiko.brasileiro", content: "@jonsnowthespitz @jose_luan_244" },
    { author: "kiko.brasileiro", content: "@pomeranian.jon @jon_restorick_art" },
    { author: "kiko.brasileiro", content: "@emilia_thayna13 @taniathayna2011" },
    { author: "kiko.brasileiro", content: "@marllyn5573 @budgies_8" },
    { author: "kiko.brasileiro", content: "@myn_cristine @tony.hamsterr" },
    { author: "kiko.brasileiro", content: "@nickinho_apsita @nina_lhasaapso_" },
    { author: "kiko.brasileiro", content: "@nina_dog_20 @ninyca16" },
    {
        author: "kiko.brasileiro",
        content: "@tartaruga_beli_e_bile @tsukitai_hime0",
    },
    {
        author: "kiko.brasileiro",
        content: "@tayguer_2021americanbully @_tangostar_",
    },
    { author: "calopze", content: "@calopsita_silver_thoco @tomcandido13" },
    { author: "calopze", content: "@lee_ticiaaah @geni.sales.127" },
    { author: "calopze", content: "@malusfm @juliocesar.marino" },
    { author: "nina.epipoca", content: "@calopze @casamaistres" },
    {
        author: "nina.epipoca",
        content: "@calopsitas_vitoria_es @calopsitas_mansa",
    },
    { author: "nina.epipoca", content: "@messicalopsita @vida_de_calopsita0" },
    { author: "nina.epipoca", content: "@o_mundodasaves @diario_calopsitas" },
    { author: "nina.epipoca", content: "@fc_messi.e.dudu @mporpeta" },
    { author: "gabrielabocciat", content: "@kesia_vazzzz @lczp_zacchia" },
    { author: "gabrielabocciat", content: "@teixeira_rafs @isa_vrq" },
    { author: "gabrielabocciat", content: "@pedriin__4 @caiosouzak3" },
    { author: "gabrielabocciat", content: "@sofiaalizama @miin_vict" },
    { author: "andrielekleitzke", content: "@regisleitzke @eduardaa_ewald" },
    {
        author: "emilia_thayna13",
        content: "@lucelia.bolos_e_docesdecorados @samuel_vinicius2457",
    },
    { author: "emilia_thayna13", content: "@bruce_wayne1903 @pandorah.50" },
    { author: "emilia_thayna13", content: "@helloysan @heloacostta" },
    { author: "emilia_thayna13", content: "@ellen_lorena25 @anny_kallyne20" },
    { author: "emilia_thayna13", content: "@_dd7oficial @____textos123____" },
    { author: "emilia_thayna13", content: "@_dud1inhax @_anaceciliaalvees" },
    { author: "emilia_thayna13", content: "@_brn_alves @islennbeatriz" },
    {
        author: "emilia_thayna13",
        content: "@victor_gabriell44a @juliana.ferreira.jgcj",
    },
    { author: "emilia_thayna13", content: "@maryanaa.bs @maryanaa_bs" },
    {
        author: "emilia_thayna13",
        content: "@kawany.vitoria.16144606 @anny_kallyne20",
    },
    {
        author: "emilia_thayna13",
        content: "@maraparecida2672 @david_luan_araujo",
    },
    { author: "kiko.brasileiro", content: "@romeu.babyboy @romariorocha06" },
    { author: "kiko.brasileiro", content: "@ringneck_messi @okame_rin_shinamon" },
    { author: "kiko.brasileiro", content: "@aliceraiane2 @romariorocha06" },
    { author: "kiko.brasileiro", content: "@bruninhaa_alveez @aliceraiane2" },
    { author: "kiko.brasileiro", content: "@anny_kallyne20 @emilia_thayna13" },
    { author: "kiko.brasileiro", content: "@anny_kallyne20 @ellen_lorena25" },
    { author: "kiko.brasileiro", content: "@helloysan @heroi.1311" },
    { author: "kiko.brasileiro", content: "@theboxerdog.india @familia_curtina" },
    { author: "kiko.brasileiro", content: "@tony.hamsterr @emilia_thayna13" },
    { author: "kiko.brasileiro", content: "@190_veronica @julia_ferreira.13" },
    { author: "kiko.brasileiro", content: "@arthurbarbosa2019 @emilia_thayna13" },
    { author: "kiko.brasileiro", content: "@batistadavan @taniathayna2011" },
    {
        author: "_marisanogueira",
        content: "@rrroseskt_ted_e_lolo_yorkshire , @sabrina.mello27",
    },
    { author: "_marisanogueira", content: "@gabrielaargeu, @marciaargeu" },
    { author: "sun.piusitas", content: "@giigumiero @jorge_eduardo_neris" },
    { author: "amandamoniche", content: "@veramoreira5950 @naty_moniche" },
    { author: "amandamoniche", content: "@rafamoniche @anabeatriz_amorim12" },
    { author: "_biah.bijuss", content: "@marcelopier" },
    { author: "idealizzarepresentes", content: "@elizete4509 @maurovergani76" },
    {
        author: "idealizzarepresentes",
        content: "@roberta_nutricao_terapias @flaviorobertovergani",
    },
    { author: "idealizzarepresentes", content: "@douglas.lucini @alinerischter" },
    {
        author: "idealizzarepresentes",
        content: "@marzaneferreira @embuttenbender",
    },
    {
        author: "idealizzarepresentes",
        content: "@christian_d_martini @bbuttenbender",
    },
    {
        author: "ana.karolina71",
        content: "@me_sophia_gabriela_ @luizagabrielly_1425",
    },
    {
        author: "niceziapatricia",
        content: "@jonashipolito021 @ligiamara.depaula",
    },
    { author: "isa_k_14", content: "@rql_14_" },
    { author: "isa_k_14", content: "@_itsbrabx_" },
    { author: "isa_k_14", content: "@isabellykeler" },
    { author: "isa_k_14", content: "@rosana.alves.3386585" },
    { author: "isa_k_14", content: "@fonsecaalyne" },
    { author: "isa_k_14", content: "@jorgejuniorrsena" },
    { author: "isa_k_14", content: "@thythygabi" },
    { author: "isa_k_14", content: "@gabriel_rsena" },
    { author: "isa_k_14", content: "@teixeirasofis" },
    { author: "isa_k_14", content: "@suellem_oliveira_57" },
    { author: "isa_k_14", content: "@otil.ia2555" },
    { author: "isa_k_14", content: "@eliannekeller" },
    { author: "isa_k_14", content: "@graziely.samara" },
    { author: "isa_k_14", content: "@brendanacleto_" },
    { author: "isa_k_14", content: "@alessandra1822021" },
    { author: "jose_bessa", content: "@thammy_caroliine @diogobdon" },
    { author: "jose_bessa", content: "@nrbessa @neziabatista" },
    { author: "flavnin", content: "@larissa.stefany.teles @taynarafernaandees" },
    { author: "flavnin", content: "@wbyte_ @livre.artetattoo" },
    { author: "flavnin", content: "@matheu5_henriqu3 @memillybs" },
    { author: "be_macedo", content: "@cookie_calopsita_ @viniciusjoaquimpania" },
    { author: "be_macedo", content: "@to_riavi @bassolife" },
    { author: "be_macedo", content: "@sarasouza_43 @victor117x" },
    { author: "be_macedo", content: "@duda_macedo01 @aline02sou" },
    { author: "isa_breitbarg", content: "@ree_cohen @belaliberman" },
    { author: "kira_jolie.york", content: "@lila_gio\\n@vieiraaliandra" },
    { author: "paulodbraga_", content: "@kelyanededeusvieira @celsoedbraga" },
    { author: "blue____s2", content: "@zoodanath @brunasunshine" },
    {
        author: "mariaclarinhagalo12",
        content: "@sandradrguedes @sandraguedes1985",
    },
    {
        author: "mariaclarinhagalo12",
        content: "@sandraguedes1985 @sandradrguedes",
    },
    {
        author: "mariaclarinhagalo12",
        content: "@rodrigo_luciano_vaz @sandradrguedes",
    },
    { author: "mariaclarinhagalo12", content: "@rodrigo_luciano_vaz @show.petz" },
    {
        author: "mariaclarinhagalo12",
        content: "@sandraguedes1985 @sandradrguedes",
    },
    { author: "rafacorreia2530", content: "@nayfeliciana @tainara.rosa1997" },
    { author: "carolinemunielly", content: "@umcertolucas @mariadasilva2850" },
    {
        author: "carolinemunielly",
        content: "@lulu_almeida_08 @nanda_almeida_012",
    },
    {
        author: "carolinemunielly",
        content: "@crystal._calopsita @benjamimcalopsita_",
    },
    { author: "caiocalou", content: "@rafacorreia2530 @edna_cassia" },
    { author: "carolinemunielly", content: "@lilian.isabell @trindadelaila" },
    { author: "crystal._calopsita", content: "@trindadelaila @umcertolucas" },
    {
        author: "crystal._calopsita",
        content: "@lulu_almeida_08 @nanda_almeida_012",
    },
    {
        author: "crystal._calopsita",
        content: "@carolinemunielly @benjamincalopsita_",
    },
    {
        author: "rafacorreia2530",
        content: "@laisecrisalmeida @neuzeirborgesdasilva",
    },
    { author: "rafacorreia2530", content: "@beatrzcorrea @lisianemartinez" },
    { author: "rafacorreia2530", content: "@caiocalou @edna_cassia" },
    { author: "marcellamoraisf", content: "@starletleticia @elaine_paoli" },
    { author: "marcellamoraisf", content: "@ritadecassiamorais9 @tettisilva" },
    { author: "marcellamoraisf", content: "@starletleticia @elaine_paoli" },
    { author: "isadora.fabricio.77", content: "@mario234711" },
    { author: "isadora.fabricio.77", content: "@isado.ra2456" },
    { author: "paaty_almeida_", content: "@eeve_xtina @mayseretta" },
    { author: "paaty_almeida_", content: "@joyceemdfreitas @bruhbertoni" },
    { author: "paaty_almeida_", content: "@henrique.rosin @karinna_per" },
    { author: "paaty_almeida_", content: "@rumildabarbosa @elisrosin" },
    { author: "ingridwsouza", content: "@_tiiago_00 @vanessa.a.jj" },
    { author: "stelagald", content: "@gabigaldinob" },
    { author: "stelagald", content: "@gabigaldinob" },
    { author: "stelagald", content: "@samillagoncalves53" },
    { author: "stelagald", content: "@isabellagald" },
    { author: "stelagald", content: "@manuellagaldinoleao" },
    { author: "angelica_fsouza", content: "@angferreira @leonicardosodesouza" },
    { author: "lu.__.nna", content: "@lene_764 @lojaisamel12" },
    { author: "lu.__.nna", content: "@https_skarz @priv_da_laraa1" },
    { author: "lu.__.nna", content: "@lara31303 @_lisgabrielle" },
    { author: "lu.__.nna", content: "Eu perdi minhas 2 calopsitas" },
    { author: "lu.__.nna", content: "@maisa_cerqueira_ @uplucian" },
    { author: "lu.__.nna", content: "@diariodamel10 @lu_fernandes_san" },
    { author: "gabrielabocciat", content: "@alinunessz @edivinityz" },
    {
        author: "adrianavasconcellosp",
        content: "@calopsitaboss @calopsita_thoor",
    },
    {
        author: "adrianavasconcellosp",
        content: "@calopsitas.brasil @psitashouse",
    },
    {
        author: "adrianavasconcellosp",
        content: "@messicalopsita @calopsitas_mansa",
    },
    { author: "gabrielabocciat", content: "@mariane.xs @valentinazenere" },
    { author: "adrianavasconcellosp", content: "@diario_calopsitas @mporpeta" },
    { author: "gabrielabocciat", content: "@larissa_queiroz.9 @bernardo29_sz" },
    { author: "gabrielabocciat", content: "@rhuanarantes24 @kaue_silva777" },
    { author: "vitiregina", content: "@nando_sm10 @vickyninafamily" },
    { author: "gabrielabocciat", content: "@gtorezan @dulcepilissaro" },
    { author: "vitiregina", content: "@ivanybentomarques @bibizinhamt" },
    { author: "vitiregina", content: "@simone_alenski @si.mone.arte" },
    { author: "gabrielabocciat", content: "@lolita_pit @wlguimaraess" },
    { author: "vitiregina", content: "@dudamicavasconcelos @bebescabio" },
    { author: "vitiregina", content: "@celia.m.oliveira.98 @guilherme.mica" },
    { author: "vitiregina", content: "@flapelegrini @carolpilim" },
    { author: "vitiregina", content: "@nathy_broglieto @helennice5" },
    { author: "vitiregina", content: "@brupelegrini @caesargv" },
    { author: "nicolysantos19", content: "@marci.658 @calopsitalua" },
    { author: "vitorgabriel.barbosa.503", content: "@rafaelmende_" },
    { author: "_estela_bd_", content: "@edna_daineze @dainezeandreleandro" },
    { author: "laisdecosta", content: "@drbertoldi @sufelippini" },
    { author: "laisdecosta", content: "@paola_decosta @daiimayer" },
    { author: "calopsitta_gigi", content: "@sergiohba @its.giovanna10" },
    { author: "camillytawany853", content: "@petter_miranha @emy_rocha_" },
    {
        author: "luanagomesfeliciano",
        content: "@liviagomesfeliciano @emileinefeliciano",
    },
    {
        author: "vaniaventola",
        content: "@vivianefagundes27 @karlamolinarimundim",
    },
    { author: "vaniaventola", content: "@anapaula.v.rossi @pri_fchaves" },
    { author: "vaniaventola", content: "@dorotyevangelista @dorlicanova" },
    { author: "isa.bonim", content: "@isinha.rivas @gi_cavenaghi" },
    { author: "isa.bonim", content: "@morais_paty @raphaela_crestani" },
    { author: "claudiarabello_", content: "@blue_tuna01 @po.vig" },
    { author: "isa.bonim", content: "@helo.bonim @fe.bonim" },
    {
        author: "claudiarabello_",
        content: "@roberta_palhares @amorsocrescevblp4",
    },
    { author: "claudiarabello_", content: "@__ac3rola__ @adalgizasilva" },
    { author: "claudiarabello_", content: "@kenynha_r @patchukaa123" },
    { author: "calopsitas_apollo", content: "@mundoocalopsita @calopsita.goa" },
    { author: "calopsitas_apollo", content: "@nicco_opicurita @crisenino" },
    { author: "calopsitas_apollo", content: "@wm_misanga @_.calopsitas._" },
    { author: "calopsitas_apollo", content: "@quinmiran @elvis_psita_ofc" },
    {
        author: "calopsitas_apollo",
        content: "@minha_cria_passaros_e_hamster @tucco_calopsita",
    },
    {
        author: "calopsitas_apollo",
        content: "@minha_cria_veterinarios @eu.filipa.psita",
    },
    { author: "calopsitas_apollo", content: "@calopicita.nick @romeuu_cg" },
    { author: "calopsitata", content: "@alicenazato @annajulia.bfonseca" },
    {
        author: "calopsitas_apollo",
        content: "@lua_calopsitaa @calopsita_princeso",
    },
    { author: "calopsitas_apollo", content: "@milou2665 @pipoca._.cacau" },
    {
        author: "calopsitas_apollo",
        content: "@babi_2403_ @freddyncocothecockatiels",
    },
    {
        author: "calopsitas_apollo",
        content: "@mango_and_chopper @zeca_calopista",
    },
    { author: "calopsitas_apollo", content: "@picita_cininho @filopsitaa" },
    { author: "calopsitas_apollo", content: "@nina_e_pituco_ @queso_the_tiel" },
    {
        author: "calopsitas_apollo",
        content: "@marcelo_e_fernanda_calopsitas @cacau_o_passarinho",
    },
    { author: "cinco_psitas", content: "@pipoco_santos @lulu_de_lua" },
    {
        author: "calopsitas_apollo",
        content: "@sol_.calopsita @calopsitafloquinho",
    },
    { author: "calopsitas_apollo", content: "@calopsisters @koko64799" },
    {
        author: "calopsitas_apollo",
        content: "@amor_por_uma_psita @billiejean.calopsita",
    },
    { author: "cinco_psitas", content: "@psitashouse @companheirosdeasas" },
    { author: "cinco_psitas", content: "@familia.pius @tatis.psitas" },
    { author: "cinco_psitas", content: "@psita_fenix @mcalopsita" },
    { author: "cinco_psitas", content: "@isa.psitas @diario.das.4.jabutis" },
    { author: "calopsitas_apollo", content: "@chico.psita01 @ticocalopsita_" },
    { author: "leticiabessaf", content: "@daanneevs_11 @gabriella_bessa" },
    {
        author: "calopsitas_apollo",
        content: "@psitas_whiteesunflower @criancao20",
    },
    { author: "cinco_psitas", content: "@psita.senior @pituco_pisita" },
    { author: "cinco_psitas", content: "@psitas_lua_e_juju @harry_psita" },
    { author: "cinco_psitas", content: "@gaudencio_agp @euoelvispsita" },
    {
        author: "calopsitas_apollo",
        content: "@calopsitas_charlie_e_lola @budgteils",
    },
    { author: "calopsitas_apollo", content: "@kikoesuaturma19 @nego_psita1" },
    {
        author: "calopsitas_apollo",
        content: "@psita_luna_e_theo @princesa_psita_",
    },
    { author: "cinco_psitas", content: "@cecilia.nogueira687 @juliananunes114" },
    {
        author: "cinco_psitas",
        content: "@adrianasilva1188 @maurocesar.silva.501",
    },
    {
        author: "liviagomesfeliciano",
        content: "@luanagomesfeliciano @emileinefeliciano",
    },
    { author: "calopsitas_apollo", content: "@babyyy_elijah @pituco_florzinha" },
    { author: "cinco_psitas", content: "@lunapenabranca @lian_lalika" },
    { author: "calopsitas_apollo", content: "@_griseplata_ @calopsitabryan" },
    { author: "cinco_psitas", content: "@_fredcalopsita_ @anto.bartolomeu" },
    {
        author: "calopsitas_apollo",
        content: "@didyogalvao @josemiguel_saxofonista",
    },
    { author: "calopsitas_apollo", content: "@raven.ringneck @vitoriabibi_" },
    { author: "calopsitas_apollo", content: "@tedcalopsita_ @bilu_hulk" },
    { author: "calopsitas_apollo", content: "@sextetodeasas @marceloninojr" },
    {
        author: "calopsitas_apollo",
        content: "@calopsitas_e_periquitos @ninozinhopsita",
    },
    { author: "calopsitas_apollo", content: "@romeu_a.l @irmaosdinosaur" },
    {
        author: "calopsitas_apollo",
        content: "@josemiguel040711 @pipoca.ocalopsita",
    },
    { author: "calopsitas_apollo", content: "@avesciths @psitaamendoim_" },
    { author: "calopsitas_apollo", content: "@pitucoo_acalopsita @mariana.m.s1" },
    {
        author: "calopsitas_apollo",
        content: "@calopsitta_gigi @catarina_helena_calopsita",
    },
    {
        author: "calopsitas_apollo",
        content: "@psitas_limfas @amorinhaacalopsita",
    },
    { author: "calopsitas_apollo", content: "@soylunalunitaa @apolocallopsita" },
    {
        author: "calopsitas_apollo",
        content: "@hannah.doguinha_ @clarlie_y_lolla",
    },
    {
        author: "calopsitas_apollo",
        content: "@juliamaria.calopsita @_euheuresco",
    },
    { author: "calopsitas_apollo", content: "@calopsitas.cha.bene @7923lo" },
    {
        author: "calopsitas_apollo",
        content: "@nina_psita03 @as_malucas_de_topete_ofc",
    },
    {
        author: "calopsitas_apollo",
        content: "@pequeno.titoo @piriquito254calopicita",
    },
    { author: "calopsitas_apollo", content: "@calopsitata @calopsitatica_" },
    { author: "calopsitas_apollo", content: "@mundoocalopsita @calopsita.goa" },
    {
        author: "calopsitas_apollo",
        content: "@calopsitaternurinha @calopsitaternurinha",
    },
    {
        author: "calopsitas_apollo",
        content: "@calopsitas_ze_e_amora @calopsita_tiquinh0",
    },
    { author: "helo.bonim", content: "@fe.bonim @isa.bonim" },
    {
        author: "calopsitas_apollo",
        content: "@calopsitabibinhaebananinha @the_5_birdmigos",
    },
    { author: "edu_flores89", content: "@maria_gabi2009 Bonequinha..❤️❤️" },
    { author: "maria_gabi2009", content: "@limaa.stee @roberta_leticya_moraes" },
    {
        author: "maria_gabi2009",
        content: "@josethegomesdealmeida @josi_vini_almeida",
    },
    { author: "maria_gabi2009", content: "@karenmarta_15 @rafaelricardomarta" },
    {
        author: "maria_gabi2009",
        content: "@dianafeltrinkanzler @lindomarosvaldop.kanzler",
    },
    {
        author: "lucaas_teixeira",
        content: "@lerissa_fernanda @biancamodestobarbosa",
    },
    { author: "maria_gabi2009", content: "@tatydocecake @edu_flores89" },
    { author: "maria_gabi2009", content: "@pa.lopes_ @ths.minyas" },
    { author: "matosmoreiraandrea", content: "❤️" },
    {
        author: "robsilvmaraninchi",
        content: "@dayaneschmidt @lucianasilveira___",
    },
    { author: "heloisa.brand", content: "@robsilvmaraninchi @izadorapf" },
    { author: "heloisa.brand", content: "@heli.brand @anavolpatobrand" },
    { author: "daay.delfino", content: "@tm.lanza @edvangoulart" },
    { author: "isa_breitbarg", content: "@rodrigofleiss @belaliberman" },
    { author: "sobczaack", content: "@anac.coorrea @artesanocki" },
    { author: "sobczaack", content: "@julia.schumachers @gabi._.grein" },
    { author: "xsb_maryy", content: "@_.calopsitas_ @_wytdxxz" },
    { author: "sobczaack", content: "@rcarla.satto @sattolola" },
    { author: "sobczaack", content: "@luziaelisa_w @galvao_vanessa" },
    { author: "sobczaack", content: "@shirosatto @pamelasatto" },
    { author: "mimitokuda", content: "@gabitkda @ineskeiko" },
    { author: "mimitokuda", content: "@gabitkda @ineskeiko" },
    { author: "mimitokuda", content: "@gabitkda @ineskeiko" },
    { author: "hemilly_ofc_", content: ".." },
    { author: "hemilly_ofc_", content: "." },
    { author: "hemilly_ofc_", content: "." },
    { author: "hemilly_ofc_", content: "." },
    { author: "hemilly_ofc_", content: "." },
    { author: "hemilly_ofc_", content: "." },
    { author: "hemilly_ofc_", content: "Amo suas artes🙌❤️" },
    { author: "jessis.lopes", content: "@p.l.o.p.e.s @renata.ap.silva2" },
    { author: "jessis.lopes", content: "@debora_marquess_ @humbertolavinder" },
    { author: "jessis.lopes", content: "@deboracamposcp @na__luiza" },
    { author: "jessis.lopes", content: "@bella.albuquerque.rosa @flavnin" },
    { author: "sueslem_paula", content: "@jucyar_a @nataliejsilva" },
    { author: "larhyca", content: "@leleu.s @luanagsr" },
    { author: "jessis.lopes", content: "@joyce.a.lopes @gabrielplutao" },
    { author: "sueslem_paula", content: "@su_sueline @j.reis30" },
    { author: "monicasmelo", content: "@rdmlx @anayuuky" },
    { author: "monicasmelo", content: "@isamelo31 @adriano.floresta" },
    {
        author: "lhbelina",
        content: "@moboratto @rafaelaamboni @bailey_bassethound",
    },
    { author: "isagiandomenico", content: "@almir.cp @biaaa.andrade" },
    { author: "emilia_thayna13", content: "@camillymaria__ @millasofia395" },
    { author: "mel.guolo", content: "@simoneguolo @gabriel.alves23" },
    { author: "emilia_thayna13", content: "@kiko.brasileiro @arthurbarbosa2019" },
    { author: "emilia_thayna13", content: "@kiko.brasileiro @arthurbarbosa2019" },
    { author: "joanaxpoa", content: "@guzinskiana @linaritter" },
    { author: "emilia_thayna13", content: "@aliceraiane2 @mariagabryella13" },
    { author: "joanaxpoa", content: "@gtanikad8 @drub1n" },
    { author: "emilia_thayna13", content: "@alanafbispo @aliceraiane2" },
    { author: "emilia_thayna13", content: "@ivanilson138 @ivanidoleal" },
    { author: "emilia_thayna13", content: "@ivanilson138 @ivanidoleal" },
    { author: "emilia_thayna13", content: "@julia_ferreira.13 @kiko.brasileiro" },
    { author: "emilia_thayna13", content: "@emiilyvitoriiaa @emily_mota28" },
    { author: "emilia_thayna13", content: "@hellen123322 @cpsantaluzia" },
    { author: "emilia_thayna13", content: "@190_veronica @helloysan" },
    {
        author: "emilia_thayna13",
        content: "@_dd7oficial @lucelia.bolos_e_docesdecorados",
    },
    { author: "emilia_thayna13", content: "@tony.hamsterr @tamirespaula_" },
    { author: "emilia_thayna13", content: "@tony.hamsterr @taniathayna2011" },
    { author: "emilia_thayna13", content: "@taniathayna2011 @tony.hamsterr" },
    { author: "emilia_thayna13", content: "@josericardo3503 @mariajbcorreia" },
    { author: "emilia_thayna13", content: "@josy__bp @josericardo6984" },
    { author: "emilia_thayna13", content: "@jose_thiaguinho @mariia_eduuarda07" },
    { author: "emilia_thayna13", content: "@jose_thiaguinho @jose_thiaguinho" },
    {
        author: "emilia_thayna13",
        content: "@mano_el145 @joao_pedro_martins_sobral083",
    },
    {
        author: "emilia_thayna13",
        content: "@janailson.joao @joaopedromartins083",
    },
    { author: "emilia_thayna13", content: "@adrian.rha @johnnatah_silvaa" },
    { author: "emilia_thayna13", content: "@naiane_mnt @fernandaa06" },
    { author: "emilia_thayna13", content: "@nadia_luany @anny_kallyne20" },
    {
        author: "emilia_thayna13",
        content: "@periquita_enjoada @periquito.fofinho",
    },
    { author: "emilia_thayna13", content: "@mariajulianafreitas8 @pvd.maarys" },
    { author: "isamelo31", content: "@rdmlx @adriano.floresta" },
    { author: "paola_decosta", content: "@laisdecosta @carolsfronza" },
    { author: "emilia_thayna13", content: "@marllonrochagomes @mano_el145" },
    { author: "dudaxx__0", content: "@missxx_00 @kira_e_juju" },
    { author: "emilia_thayna13", content: "@romariorocha06 @roosevelt.heria" },
    { author: "isamelo31", content: "@luiztorri @monicasmelo" },
    { author: "emilia_thayna13", content: "@josericardo3503 @ricadinho2011" },
    { author: "emilia_thayna13", content: "@josericardo6984 @ricardofilho107" },
    { author: "emilia_thayna13", content: "@roosevelt.heria @roosevelt.heria" },
    { author: "dudaxx__0", content: "@michellycristinamartins @mariachandelly" },
    { author: "emilia_thayna13", content: "@mano_el145 @marllonrochagomes" },
    { author: "emilia_thayna13", content: "@kiko.brasileiro @romariorocha06" },
    { author: "emilia_thayna13", content: "@batistadavan @romariorocha06" },
    { author: "emilia_thayna13", content: "@kiko.brasileiro @batistadavan" },
    { author: "emilia_thayna13", content: "@mariana_alvees19 @bruninhaa_alveez" },
    { author: "emilia_thayna13", content: "@mariana_alvees19 @bruninhaa_alveez" },
    {
        author: "emilia_thayna13",
        content: "@arthurbarbosa2019 @elianearaujodefarias",
    },
    { author: "emilia_thayna13", content: "@amandaaraujo6470 @ketllyap" },
    { author: "emilia_thayna13", content: "@amandaaraujo6470 @ketllyap" },
    { author: "emilia_thayna13", content: "@silvanapaiva873 @00__amannda" },
    { author: "mayarapostal", content: "@thaislynebittarello @jessicawilian" },
    { author: "mayarapostal", content: "@ricardormendes_ @kaina.dutra" },
    { author: "mayarapostal", content: "@kahoana @cleidepostal" },
    { author: "claravicsora", content: "@w3b_eloize @pedrotsora" },
    { author: "emilia_thayna13", content: "@nadia_luany @ellen_lorena25" },
    { author: "emilia_thayna13", content: "@julia_ferreira.13 @190_veronica" },
    { author: "emilia_thayna13", content: "@190_veronica @veronica_3137" },
    { author: "claravicsora", content: "@mirelatelless2.0 @ribinskiclarissa" },
    { author: "emilia_thayna13", content: "@rafaelarocha2625 @alexramon000" },
    { author: "emilia_thayna13", content: "@dixx_raparigueiros01 @aliceraiane2" },
    { author: "emilia_thayna13", content: "@raiane.barbosa.16906 @r4faela.n" },
    { author: "emilia_thayna13", content: "@dixx_eu_raiane @pvd_raianezinha" },
    { author: "emilia_thayna13", content: "@rafaellaoam @monikyraianebrabosa" },
    { author: "emilia_thayna13", content: "@monicalima946 @monteiro.gas" },
    { author: "emilia_thayna13", content: "@taniathayna2011 @tamires_alvesz_" },
    { author: "zeca_psita_", content: "@cookieoltiel @periquita_enjoada" },
    { author: "emilia_thayna13", content: "@heloacostta @helloysan" },
    { author: "zeca_psita_", content: "@mariocalopsita @lonso.cath" },
    {
        author: "emilia_thayna13",
        content: "@anny_kallyne20 @kawany.vitoria.16144606",
    },
    { author: "zeca_psita_", content: "@criadourodupaes @psitas.daleiry" },
    {
        author: "emilia_thayna13",
        content: "@jose_thiaguinho @joao_pedro_martins_sobral083",
    },
    { author: "zeca_psita_", content: "@dopamina.saboaria @daniicosta12" },
    { author: "emilia_thayna13", content: "@jaquelinegr2588 @janailson.joao" },
    { author: "zeca_psita_", content: "@lisa.calopsitas @criadouro_mw" },
    {
        author: "emilia_thayna13",
        content: "@julia_ferreira.13 @julia_ferreira1414",
    },
    { author: "zeca_psita_", content: "@chiclete_ea_kira.s2 @cockatiel.sanmao" },
    { author: "emilia_thayna13", content: "@tony.hamsterr @tony_hamste" },
    { author: "zeca_psita_", content: "@beautiful_cute_lady_ @bolinha_e_dodo" },
    {
        author: "zeca_psita_",
        content: "@bulldogfrancesjack @biel_nenem_lele_linguica",
    },
    { author: "zeca_psita_", content: "@ticoebarto @belinho0206" },
    { author: "zeca_psita_", content: "@amorinhaacalopsita @psitamel" },
    { author: "zeca_psita_", content: "@mariaduda6894 @melpsita1414" },
    { author: "zeca_psita_", content: "@dudaoliiveiraa__ @_stephanysilv" },
    { author: "zeca_psita_", content: "@costa_ana_paula15 @al3038796" },
    { author: "zeca_psita_", content: "@philipesilv @_vmaaia" },
    { author: "mairafrv", content: "@valeriafbrandaop @mariliafveiga" },
    { author: "mairafrv", content: "@danielornelasribeiro @epagonzaga" },
    { author: "mairafrv", content: "@edil_junior @thaysexavier" },
    { author: "ringneck.kiwi", content: "@josianit @tillarissa" },
    { author: "ringneck.kiwi", content: "@piusdayasmin @mingauringneck" },
    { author: "ringneck.kiwi", content: "@anjinhosdacarminha @carminhakoenig" },
    { author: "ringneck.kiwi", content: "@klausphotograph @giovannaf_b" },
    { author: "ringneck.kiwi", content: "@pliniothebird @jornaldopassarinho" },
    { author: "anamprosa", content: "@lulypontel 😍" },
    { author: "lulypontel", content: "@thaispontel @thainaa.13 @pontariaa_" },
    { author: "lulypontel", content: "@anamprosa @adriane.rosa.969" },
    {
        author: "oswaldinho_chihuahua",
        content: "@peixethedog @bruce.john_chihuahuas",
    },
    { author: "oswaldinho_chihuahua", content: "@thatapchaves @amandasnc" },
    { author: "oswaldinho_chihuahua", content: "@filipe.nasc @kaagalhardo" },
    { author: "oswaldinho_chihuahua", content: "@vanessapass.s @renatasheeny" },
    { author: "rafaellaoam", content: "@ivojackk @monnye_gomide" },
    { author: "isa_breitbarg", content: "@silvialichand @fernandobreit" },
    { author: "rafaellaoam", content: "@yagalorrane @zaragadan" },
    { author: "rafaellaoam", content: "@aurea_carol_ @_sahsxx" },
    { author: "rafaellaoam", content: "@mariaclara_og @dansalvess" },
    { author: "rafaellaoam", content: "@mihh__rodrigues @mariaclarabdo" },
    {
        author: "rafaellaoam",
        content: "@joao_carlos_coronelpmmg @matosmoreiraandrea",
    },
    { author: "mihh__rodrigues", content: "@cris_inaciio @lorenasilvavaz" },
    { author: "mihh__rodrigues", content: "@izabelabotelho @victor_pacifico" },
    { author: "rafaellaoam", content: "@thaisnm_ @luizakarez" },
    { author: "rafaellaoam", content: "@pvdyduayer @alexandreroque13" },
    { author: "rafaellaoam", content: "@nayaraamed @dansalvess" },
    { author: "rafaellaoam", content: "@gabilvrs @wanessa2609" },
    { author: "alinunessz", content: "@danpadial @rebeca__nunes" },
    { author: "alinunessz", content: "@claralubs @clarandcc" },
    { author: "ferracimlarissa", content: "@joselucasressoni @joao_ressoni" },
    { author: "paulacmb", content: "@karinadesiqueiran @yaas_mim061" },
    { author: "paulacmb", content: "@_lucastxr @sthantomas" },
    { author: "paulacmb", content: "@vinao0 @estefanny_braga" },
    { author: "paulacmb", content: "@danichaseliov @carlinhadiiaas" },
    { author: "paulacmb", content: "@pedronutch @camillyuchoa" },
    { author: "paulacmb", content: "@natipadua @p_alv3s" },
    { author: "paulacmb", content: "@mauricio.marques_nt @ana_loliv" },
    { author: "paulacmb", content: "@opaulovicta @nataliaoliveira.6" },
    { author: "paulacmb", content: "@licssan @antoninhoo" },
    { author: "paulacmb", content: "@quesiamorais @misquitaaa" },
    { author: "paulacmb", content: "@babi_rosal @rafael_4ntonio" },
    {
        author: "wanessa2609",
        content: "Sua linda, minha artista fantástica, phodastica",
    },
    { author: "wanessa2609", content: "@rafaellaoam e @gabilvrs" },
];