const database = [
    { author: "isamelo31", content: "@luiztorri @monicasmelo" },
    { author: "isamelo31", content: "@rdmlx @adriano.floresta" },
    { author: "wanessa2609", content: "@rafaellaoam e @gabilvrs" },
    { author: "rafaellaoam", content: "@ivojackk @monnye_gomide" },
    { author: "rafaellaoam", content: "@thaisnm_ @luizakarez" },
    { author: "rafaellaoam", content: "@nayaraamed @dansalvess" },
    {
        author: "wanessa2609",
        content: "Sua linda, minha artista fantástica, phodastica",
    },
    {
        author: "rafaellaoam",
        content: "@joao_carlos_coronelpmmg @matosmoreiraandrea",
    },
    { author: "rafaellaoam", content: "@yagalorrane @zaragadan" },
    { author: "rafaellaoam", content: "@aurea_carol_ @_sahsxx" },
    { author: "rafaellaoam", content: "@mihh__rodrigues @mariaclarabdo" },
    { author: "rafaellaoam", content: "@mariaclara_og @dansalvess" },
    { author: "rafaellaoam", content: "@pvdyduayer @alexandreroque13" },
    { author: "rafaellaoam", content: "@gabilvrs @wanessa2609" },
    { author: "rafaellaoam", content: "@diego_diur @yduayer" },
    { author: "rafaellaoam", content: "@yarabvs @immoonl" },
    { author: "rafaellaoam", content: "@luiza_carvalho8 @_ojuliana" },
    { author: "_gabis_souza_", content: "@zelia6401 @mimi_crocheeatelie" },
    { author: "mimi_crocheeatelie", content: "@_gabis_souza_ @zelia6401" },
    { author: "mimi_crocheeatelie", content: "@nanath_assis @esdrasmourao" },
    {
        author: "mimi_crocheeatelie",
        content: "@maxizainesouzade @lana_souza_reis",
    },
    { author: "mimi_crocheeatelie", content: "@evorinha @juliagramt" },
    { author: "mimi_crocheeatelie", content: "@donaeva_souza @jucolem" },
    {
        author: "mimi_crocheeatelie",
        content: "@juliasouza6522 @atelierlucrocheebijus",
    },
    { author: "mimi_crocheeatelie", content: "@mimirmiranda @michelesa27" },
    { author: "_nataliaanunes", content: "@carolcnunis @sonia.nunes.7739814" },
    { author: "tres.psitas", content: "@luanroier @nandadavanzo" },
    { author: "tres.psitas", content: "@evelyncrt @evibvbatista" },
    { author: "tres.psitas", content: "@paulacfortuna @paulagonzatto" },
    { author: "tres.psitas", content: "@karenserafini91 @stefanifavaro" },
    { author: "tres.psitas", content: "@paulofgraffoliveira @erikadavanzo" },
    { author: "tres.psitas", content: "@andreiadavanzo @carla_davanzo" },
    { author: "tres.psitas", content: "@zoeypapagaiadocongo @zoologico_pet" },
    { author: "tres.psitas", content: "@alvocalopsita @calopsitassuzuki" },
    { author: "tres.psitas", content: "@peninhascrazy @peninhasdeamor" },
    { author: "tres.psitas", content: "@caju_psitas @blu.calopsita" },
    { author: "tres.psitas", content: "@araras_blogueirinhas @psitasdabea" },
    { author: "tres.psitas", content: "@cookieoltiel @juca.ringneck" },
    { author: "tres.psitas", content: "@sun.piusitas @calopsitascamaradas" },
    { author: "ringneck.kiwi", content: "@josianit @tillarissa" },
    { author: "ringneck.kiwi", content: "@klausphotograph @giovannaf_b" },
    { author: "ringneck.kiwi", content: "@piusdayasmin @mingauringneck" },
    {
        author: "bearruda",
        content: "@erikaeid e @cruzhjuliana Uma ideia linda para presentear os nossos embaixadores. O que acham? 😍",
    },
    { author: "vitorgabriel.barbosa.503", content: "@ellen_lohh" },
    { author: "ringneck.kiwi", content: "@pliniothebird @jornaldopassarinho" },
    { author: "ringneck.kiwi", content: "@anjinhosdacarminha @carminhakoenig" },
    { author: "vitorgabriel.barbosa.503", content: "@lilah_santos51" },
    { author: "arthuurxi04", content: "@homeroximenes @flavianeximenes" },
    { author: "isa.bonim", content: "@isinha.rivas @gi_cavenaghi" },
    { author: "heloisa.brand", content: "@robsilvmaraninchi @izadorapf" },
    { author: "vaniaventola", content: "@anapaula.v.rossi @pri_fchaves" },
    { author: "isa.bonim", content: "@helo.bonim @fe.bonim" },
    { author: "lulypontel", content: "@anamprosa @adriane.rosa.969" },
    { author: "isa.bonim", content: "@morais_paty @raphaela_crestani" },
    {
        author: "vaniaventola",
        content: "@vivianefagundes27 @karlamolinarimundim",
    },
    { author: "paaty_almeida_", content: "@eeve_xtina @mayseretta" },
    { author: "paaty_almeida_", content: "@rumildabarbosa @elisrosin" },
    { author: "isa_breitbarg", content: "@silvialichand @fernandobreit" },
    { author: "vaniaventola", content: "@gabrielavmarra @raquel.ventola" },
    { author: "laisdecosta", content: "@drbertoldi @sufelippini" },
    {
        author: "claudiarabello_",
        content: "@roberta_palhares @amorsocrescevblp4",
    },
    { author: "oswaldinho_chihuahua", content: "@thatapchaves @amandasnc" },
    {
        author: "lhbelina",
        content: "@moboratto @rafaelaamboni @bailey_bassethound",
    },
    { author: "helo.bonim", content: "@fe.bonim @isa.bonim" },
    { author: "ingridwsouza", content: "@_tiiago_00 @vanessa.a.jj" },
    { author: "ferracimlarissa", content: "@joselucasressoni @joao_ressoni" },
    {
        author: "liviagomesfeliciano",
        content: "@luanagomesfeliciano @emileinefeliciano",
    },
    { author: "mayarapostal", content: "@kahoana @cleidepostal" },
    { author: "marcellamoraisf", content: "@starletleticia @elaine_paoli" },
    { author: "marcellamoraisf", content: "@starletleticia @elaine_paoli" },
    { author: "oswaldinho_chihuahua", content: "@lllfreitas @luckperezz" },
    {
        author: "oswaldinho_chihuahua",
        content: "@peixethedog @bruce.john_chihuahuas",
    },
    { author: "lu.__.nna", content: "@maisa_cerqueira_ @uplucian" },
    { author: "paaty_almeida_", content: "@joyceemdfreitas @bruhbertoni" },
    { author: "stelagald", content: "@gabigaldinob" },
    { author: "stelagald", content: "@isabellagald" },
    {
        author: "oswaldinho_chihuahua",
        content: "@mila_lhasaapso @thor_o_chiuaua",
    },
    { author: "mayarapostal", content: "@thaislynebittarello @jessicawilian" },
    { author: "laisdecosta", content: "@juju.bortoluzzi @daniela.bertoldi" },
    { author: "stelagald", content: "@manuellagaldinoleao" },
    {
        author: "calopsitas_apollo",
        content: "@calopsitta_gigi @catarina_helena_calopsita",
    },
    { author: "lu.__.nna", content: "@lara31303 @_lisgabrielle" },
    { author: "jessis.lopes", content: "@bella.albuquerque.rosa @flavnin" },
    { author: "claudiarabello_", content: "@__ac3rola__ @adalgizasilva" },
    { author: "lu.__.nna", content: "@lene_764 @lojaisamel12" },
    { author: "mimitokuda", content: "@gabitkda @ineskeiko" },
    { author: "mimitokuda", content: "@gabitkda @ineskeiko" },
    { author: "mimitokuda", content: "@gabitkda @ineskeiko" },
    { author: "mairafrv", content: "@valeriafbrandaop @mariliafveiga" },
    { author: "oswaldinho_chihuahua", content: "@rafacdantas @nair0611" },
    { author: "camillytawany853", content: "@petter_miranha @emy_rocha_" },
    { author: "zeca_psita_", content: "@beautiful_cute_lady_ @bolinha_e_dodo" },
    { author: "mel.guolo", content: "@simoneguolo @gabriel.alves23" },
    { author: "joanaxpoa", content: "@gtanikad8 @drub1n" },
    { author: "mihh__rodrigues", content: "@cris_inaciio @lorenasilvavaz" },
    { author: "mayarapostal", content: "@ricardormendes_ @kaina.dutra" },
    { author: "angelica_fsouza", content: "@angferreira @leonicardosodesouza" },
    { author: "joanaxpoa", content: "@guzinskiana @linaritter" },
    { author: "rafacorreia2530", content: "@caiocalou @edna_cassia" },
    { author: "mairafrv", content: "@edil_junior @thaysexavier" },
    { author: "edna_daineze", content: "@_estela_bd_ @andreleandrodaineze" },
    {
        author: "calopsitas_apollo",
        content: "@minha_cria_veterinarios @eu.filipa.psita",
    },
    {
        author: "calopsitas_apollo",
        content: "@hannah.doguinha_ @clarlie_y_lolla",
    },
    { author: "maria_gabi2009", content: "@tatydocecake @edu_flores89" },
    {
        author: "lindomarosvaldop.kanzler",
        content: "@maria_gabi2009 @tatyangela",
    },
    {
        author: "robsilvmaraninchi",
        content: "@dayaneschmidt @lucianasilveira___",
    },
    { author: "vitiregina", content: "@ivanybentomarques @bibizinhamt" },
    { author: "paola_decosta", content: "@laisdecosta @carolsfronza" },
    { author: "vitiregina", content: "@cahmica_ @daphnits" },
    { author: "xsb_maryy", content: "@isabellymedeiros._ @xbs.wyara" },
    { author: "sobczaack", content: "@shirosatto @pamelasatto" },
    { author: "zeca_psita_", content: "@philipesilv @_vmaaia" },
    { author: "zeca_psita_", content: "@lisa.calopsitas @criadouro_mw" },
    { author: "zeca_psita_", content: "@cookieoltiel @periquita_enjoada" },
    { author: "zeca_psita_", content: "@criadourodupaes @psitas.daleiry" },
    { author: "zeca_psita_", content: "@ticoebarto @belinho0206" },
    { author: "isagiandomenico", content: "@thainacanario @thanicanario" },
    { author: "leticiabessaf", content: "@gabriella_bessa @edilainy45" },
    { author: "calopsitata", content: "@alicenazato @annajulia.bfonseca" },
    { author: "isagiandomenico", content: "@lohranmoraes @rosimeiremoraessilva" },
    {
        author: "zeca_psita_",
        content: "@bulldogfrancesjack @biel_nenem_lele_linguica",
    },
    { author: "sobczaack", content: "@rcarla.satto @sattolola" },
    {
        author: "calopsitas_apollo",
        content: "@calopsitabibinhaebananinha @the_5_birdmigos",
    },
    { author: "zeca_psita_", content: "@dopamina.saboaria @daniicosta12" },
    { author: "vitiregina", content: "@nando_sm10 @vickyninafamily" },
    { author: "sobczaack", content: "@_fernanda.agnes @laizoca__" },
    { author: "vitiregina", content: "@celia.m.oliveira.98 @guilherme.mica" },
    { author: "sobczaack", content: "@helevenberger @eduarda_vazz" },
    { author: "sobczaack", content: "@luanoski @fernando.jmartins" },
    { author: "zeca_psita_", content: "@mariaduda6894 @melpsita1414" },
    { author: "paulacmb", content: "@licssan @antoninhoo" },
    { author: "adrianavasconcellosp", content: "@diario_calopsitas @mporpeta" },
    {
        author: "adrianavasconcellosp",
        content: "@calopsitas.brasil @psitashouse",
    },
    { author: "hemilly_ofc_", content: "@julia_ribeiro_br @mariacardoso4_" },
    {
        author: "calopsitas_apollo",
        content: "@pequeno.titoo @piriquito254calopicita",
    },
    {
        author: "adrianavasconcellosp",
        content: "@calopsitaboss @calopsita_thoor",
    },
    {
        author: "calopsitas_apollo",
        content: "@lua_calopsitaa @calopsita_princeso",
    },
    { author: "calopsitas_apollo", content: "@pitucoo_acalopsita @mariana.m.s1" },
    {
        author: "adrianavasconcellosp",
        content: "@messicalopsita @calopsitas_mansa",
    },
    { author: "calopsitas_apollo", content: "@babyyy_elijah @pituco_florzinha" },
    {
        author: "calopsitas_apollo",
        content: "@calopsitaternurinha @calopsitaternurinha",
    },
    {
        author: "calopsitas_apollo",
        content: "@psitas_limfas @amorinhaacalopsita",
    },
    { author: "sueslem_paula", content: "@su_sueline @j.reis30" },
    {
        author: "calopsitas_apollo",
        content: "@calopsitas_charlie_e_lola @budgteils",
    },
    { author: "isadora.fabricio.77", content: "@isado.ra2456" },
    { author: "gabrielabocciat", content: "@alinunessz @edivinityz" },
    { author: "gabrielabocciat", content: "@gtorezan @dulcepilissaro" },
    { author: "gabrielabocciat", content: "@cinthiarba @luttx_" },
    { author: "gabrielabocciat", content: "@yagostephano @_gguedees" },
    { author: "paulacmb", content: "@andrerinco_ f @giovnnaftas" },
    { author: "calopsitas_apollo", content: "@nicco_opicurita @crisenino" },
    { author: "calopsitas_apollo", content: "@mundoocalopsita @calopsita.goa" },
    {
        author: "calopsitas_apollo",
        content: "@minha_cria_passaros_e_hamster @tucco_calopsita",
    },
    { author: "calopsitas_apollo", content: "@quinmiran @elvis_psita_ofc" },
    { author: "calopsitas_apollo", content: "@calopicita.nick @romeuu_cg" },
    { author: "calopsitas_apollo", content: "@milou2665 @pipoca._.cacau" },
    {
        author: "calopsitas_apollo",
        content: "@babi_2403_ @freddyncocothecockatiels",
    },
    { author: "cinco_psitas", content: "@pipoco_santos @lulu_de_lua" },
    {
        author: "calopsitas_apollo",
        content: "@sol_.calopsita @calopsitafloquinho",
    },
    { author: "cinco_psitas", content: "@psitashouse @companheirosdeasas" },
    { author: "cinco_psitas", content: "@isa.psitas @diario.das.4.jabutis" },
    { author: "cinco_psitas", content: "@familia.pius @tatis.psitas" },
    { author: "cinco_psitas", content: "@o_mundodasaves @psittafamily" },
    { author: "cinco_psitas", content: "@gaudencio_agp @euoelvispsita" },
    { author: "calopsitas_apollo", content: "@pet.kiko @mel.mmelinda" },
    { author: "cinco_psitas", content: "@psita.senior @pituco_pisita" },
    { author: "cinco_psitas", content: "@marcelocalopsita @ringneck_messi" },
    { author: "calopsitas_apollo", content: "@kikoesuaturma19 @nego_psita1" },
    { author: "cinco_psitas", content: "@cecilia.nogueira687 @juliananunes114" },
    { author: "calopsitas_apollo", content: "@_griseplata_ @calopsitabryan" },
    { author: "cinco_psitas", content: "@_fredcalopsita_ @anto.bartolomeu" },
    { author: "calopsitas_apollo", content: "@tedcalopsita_ @bilu_hulk" },
    { author: "calopsitas_apollo", content: "@raven.ringneck @vitoriabibi_" },
    {
        author: "calopsitas_apollo",
        content: "@didyogalvao @josemiguel_saxofonista",
    },
    { author: "calopsitas_apollo", content: "@sextetodeasas @marceloninojr" },
    {
        author: "calopsitas_apollo",
        content: "@calopsitas_e_periquitos @ninozinhopsita",
    },
    { author: "calopsitas_apollo", content: "@avesciths @psitaamendoim_" },
    { author: "calopsitas_apollo", content: "@soylunalunitaa @apolocallopsita" },
    {
        author: "calopsitas_apollo",
        content: "@calopsitas_ze_e_amora @calopsita_tiquinh0",
    },
    {
        author: "maria_gabi2009",
        content: "@josethegomesdealmeida @josi_vini_almeida",
    },
    { author: "maria_gabi2009", content: "@limaa.stee @roberta_leticya_moraes" },
    { author: "maria_gabi2009", content: "@karenmarta_15 @rafaelricardomarta" },
    { author: "maria_gabi2009", content: "@pa.lopes_ @ths.minyas" },
    { author: "hemilly_ofc_", content: "." },
    { author: "hemilly_ofc_", content: "." },
    { author: "hemilly_ofc_", content: "." },
    {
        author: "hemilly_ofc_",
        content: "@joselma.goudard @wellingtonfonsecafonseca",
    },
    { author: "hemilly_ofc_", content: "." },
    { author: "emilia_thayna13", content: "@cislley @genival285" },
    { author: "emilia_thayna13", content: "@cislley @maraparecida2672" },
    { author: "emilia_thayna13", content: "@carlos_gabriel.26 @cislley" },
    { author: "emilia_thayna13", content: "@camillymaria__ @millasofia395" },
    { author: "emilia_thayna13", content: "@aliceraiane2 @mariagabryella13" },
    { author: "emilia_thayna13", content: "@jose_thiaguinho @mariia_eduuarda07" },
    { author: "emilia_thayna13", content: "@190_veronica @helloysan" },
    { author: "emilia_thayna13", content: "@josericardo3503 @mariajbcorreia" },
    { author: "emilia_thayna13", content: "@hellen123322 @cpsantaluzia" },
    { author: "emilia_thayna13", content: "@taniathayna2011 @tony.hamsterr" },
    { author: "emilia_thayna13", content: "@ivanilson138 @ivanidoleal" },
    { author: "emilia_thayna13", content: "@tony.hamsterr @taniathayna2011" },
    { author: "emilia_thayna13", content: "@mariajulianafreitas8 @pvd.maarys" },
    {
        author: "emilia_thayna13",
        content: "@periquita_enjoada @periquito.fofinho",
    },
    { author: "dudaxx__0", content: "@missxx_00 @kira_e_juju" },
    { author: "emilia_thayna13", content: "@kiko.brasileiro @romariorocha06" },
    { author: "emilia_thayna13", content: "@batistadavan @romariorocha06" },
    { author: "emilia_thayna13", content: "@mano_el145 @marllonrochagomes" },
    { author: "emilia_thayna13", content: "@josericardo3503 @ricadinho2011" },
    { author: "emilia_thayna13", content: "@po.liana736 @maria._.julia._.14" },
    {
        author: "emilia_thayna13",
        content: "@ellen_lorena25 @elianearaujodefarias",
    },
    { author: "claravicsora", content: "@mirelatelless2.0 @ribinskiclarissa" },
    { author: "emilia_thayna13", content: "@silvanapaiva873 @00__amannda" },
    { author: "emilia_thayna13", content: "@ellen_lorena25 @taniathayna2011" },
    { author: "claravicsora", content: "@w3b_eloize @pedrotsora" },
    { author: "emilia_thayna13", content: "@julia_ferreira.13 @190_veronica" },
    { author: "emilia_thayna13", content: "@190_veronica @veronica_3137" },
    { author: "emilia_thayna13", content: "@rafaellaoam @monikyraianebrabosa" },
    { author: "emilia_thayna13", content: "@anny_kallyne20 @helloysan" },
    { author: "emilia_thayna13", content: "@dixx_eu_raiane @pvd_raianezinha" },
    { author: "emilia_thayna13", content: "@jaquelinegr2588 @janailson.joao" },
    { author: "emilia_thayna13", content: "@raiane.barbosa.16906 @r4faela.n" },
    { author: "emilia_thayna13", content: "@tony.hamsterr @tony_hamste" },
    { author: "paulacmb", content: "@vinao0 @estefanny_braga" },
    { author: "paulacmb", content: "@danichaseliov @carlinhadiiaas" },
    { author: "paulacmb", content: "@pedronutch @camillyuchoa" },
    { author: "paulacmb", content: "@opaulovicta @nataliaoliveira.6" },
    {
        author: "rafacorreia2530",
        content: "@laisecrisalmeida @neuzeirborgesdasilva",
    },
    {
        author: "crystal._calopsita",
        content: "@carolinemunielly @benjamincalopsita_",
    },
    {
        author: "crystal._calopsita",
        content: "@lulu_almeida_08 @nanda_almeida_012",
    },
    { author: "crystal._calopsita", content: "@trindadelaila @umcertolucas" },
    { author: "carolinemunielly", content: "@lilian.isabell @trindadelaila" },
    {
        author: "carolinemunielly",
        content: "@crystal._calopsita @benjamimcalopsita_",
    },
    {
        author: "carolinemunielly",
        content: "@lulu_almeida_08 @nanda_almeida_012",
    },
    { author: "rafacorreia2530", content: "@nayfeliciana @tainara.rosa1997" },
    {
        author: "mariaclarinhagalo12",
        content: "@sandraguedes1985 @sandradrguedes",
    },
    { author: "mariaclarinhagalo12", content: "@rodrigo_luciano_vaz @show.petz" },
    {
        author: "mariaclarinhagalo12",
        content: "@sandraguedes1985 @sandradrguedes",
    },
    { author: "be_macedo", content: "@sarasouza_43 @victor117x" },
    { author: "be_macedo", content: "@to_riavi @bassolife" },
    { author: "flavnin", content: "@larissa.stefany.teles @taynarafernaandees" },
    { author: "jose_bessa", content: "@thammy_caroliine @diogobdon" },
    { author: "isa_k_14", content: "@brendanacleto_" },
    { author: "isa_k_14", content: "@graziely.samara" },
    { author: "isa_k_14", content: "@eliannekeller" },
    { author: "isa_k_14", content: "@otil.ia2555" },
    { author: "isa_k_14", content: "@gabriel_rsena" },
    { author: "isa_k_14", content: "@jorgejuniorrsena" },
    { author: "isa_k_14", content: "@rosana.alves.3386585" },
    { author: "isa_k_14", content: "@isabellykeler" },
    { author: "isa_k_14", content: "@_itsbrabx_" },
    {
        author: "ana.karolina71",
        content: "@me_sophia_gabriela_ @luizagabrielly_1425",
    },
    { author: "idealizzarepresentes", content: "@douglas.lucini @alinerischter" },
    {
        author: "idealizzarepresentes",
        content: "@danirmartinijunior @grasielakrumenauer",
    },
    { author: "teddy_o_chede", content: "@rafagastaldello @apolo_caopanheiro" },
    { author: "teddy_o_chede", content: "@thaynagarbellotti @historiadecao" },
    {
        author: "sabrinafernandesdesantana",
        content: "@geovanaa_zz @taliita_cerqueira",
    },
    { author: "sabrinafernandesdesantana", content: "❤️" },
    { author: "sabrinafernandesdesantana", content: "❤️" },
    { author: "laura.tinti", content: "@dubarbosa.arq @ferpenna" },
    { author: "zoeypapagaiadocongo", content: "@diariodeaves @cacauacacatua" },
    { author: "laura.tinti", content: "@marinatinti @tintirosangela" },
    { author: "emanueledou", content: "@roneymarani @cute.lil.kitten7" },
    { author: "rosimerebatista555", content: "@val_campos15" },
    { author: "rosimerebatista555", content: "@victorhugohugo108" },
    {
        author: "bunnyxxmilly",
        content: "@julia_kjkkl @hyozin_.miojin quero uma da lolita véi",
    },
    { author: "_biah.bijuss", content: "@beatriz_pier312" },
    { author: "_biah.bijuss", content: "@elainebperez" },
    { author: "sun.piusitas", content: "@giigumiero @jorge_eduardo_neris" },
    { author: "sun.piusitas", content: "@giigumiero @jorge_eduardo_neris" },
    { author: "sun.piusitas", content: "@giigumiero @jorge_eduardo_neris" },
    { author: "sun.piusitas", content: "@silvia.lobo.940 @_marisanogueira" },
    { author: "sun.piusitas", content: "@silvia.lobo.940 @_marisanogueira" },
    { author: "sun.piusitas", content: "@_juliana_proenca @th_tasteofhoney" },
    { author: "sun.piusitas", content: "@_juliana_proenca @th_tasteofhoney" },
    { author: "_marisanogueira", content: "@cacaualecrim , @irinanogueira" },
    {
        author: "_marisanogueira",
        content: "@geovannanogueira , @chelle.nogueira",
    },
    { author: "_marisanogueira", content: "@kitygrejo , @raimi_oficial" },
    { author: "_marisanogueira", content: "@s" },
    {
        author: "marina_cristina.pilz",
        content: "@ricardoluiz.carneiro @grazielaseidel",
    },
    { author: "kiko.brasileiro", content: "@kanky_13 @katie_the_bull" },
    { author: "kiko.brasileiro", content: "@anny_kallyne20 @kyrashihtzu_" },
    { author: "kiko.brasileiro", content: "@emilia_thayna13 @wiwuwgevi" },
    { author: "kiko.brasileiro", content: "@emilia_thayna13 @julia_ferreira.13" },
    { author: "kiko.brasileiro", content: "@julia_ferreira.13 @tony.hamsterr" },
    { author: "kiko.brasileiro", content: "@tony.hamsterr @emilia_thayna13" },
    { author: "kiko.brasileiro", content: "@taniathayna2011 @batistadavan" },
    { author: "kiko.brasileiro", content: "@batalhas_e_vitorias @batistadavan" },
    { author: "kiko.brasileiro", content: "@arthurbarbosa2019 @emilia_thayna13" },
    { author: "kiko.brasileiro", content: "@taniathayna2011 @batistadavan" },
    { author: "kiko.brasileiro", content: "@batistadavan @taniathayna2011" },
    {
        author: "kiko.brasileiro",
        content: "@mickey.pequines @joaopedroleitedeoliveira2008",
    },
    { author: "kiko.brasileiro", content: "@ellen_lorena25 @nadia_luany" },
    { author: "kiko.brasileiro", content: "@nadia_luany @anny_kallyne20" },
    { author: "kiko.brasileiro", content: "@nadia_luany @ellen_lorena25" },
    { author: "kiko.brasileiro", content: "@yasx_hk @_bella_e_bruce" },
    { author: "kiko.brasileiro", content: "@bruninhaa_alveez @aliceraiane2" },
    { author: "kiko.brasileiro", content: "@pandorababyrott @romeuejulieta967" },
    { author: "kiko.brasileiro", content: "@emilia_thayna13 @romariorocha06" },
    { author: "emilia_thayna13", content: "@david_luan_araujo @camillymaria__" },
    {
        author: "emilia_thayna13",
        content: "@kawany.vitoria.16144606 @_giselly_kaepstick",
    },
    { author: "emilia_thayna13", content: "@00__amannda @taniathayna2011" },
    {
        author: "emilia_thayna13",
        content: "@taniathayna2011 @raiane.barbosa.16906",
    },
    {
        author: "emilia_thayna13",
        content: "@arthurbarbosa2019 @julia_ferreira.13",
    },
    { author: "emilia_thayna13", content: "@julia_ferreira.13 @tony.hamsterr" },
    { author: "emilia_thayna13", content: "@tony_hamste @periquita_enjoada" },
    { author: "emilia_thayna13", content: "@kiko.brasileiro @_brn_alves" },
    { author: "emilia_thayna13", content: "@kiko.brasileiro @_brn_alves" },
    { author: "emilia_thayna13", content: "@kiko.brasileiro @_brn_alves" },
    { author: "emilia_thayna13", content: "@julia_ferreira.13 @kiko.brasileiro" },
    { author: "emilia_thayna13", content: "@tony.hamsterr @kiko.brasileiro" },
    { author: "emilia_thayna13", content: "@tony_hamste @batistadavan" },
    { author: "isabelapedrosodasilva", content: "@bijusdaisa20 @cinco_psitas" },
    {
        author: "isabelapedrosodasilva",
        content: "@bihamaral_ @marianasoutosantana",
    },
    {
        author: "isabelapedrosodasilva",
        content: "@adrianasilva1188 @maurocesar.silva.501",
    },
    {
        author: "isabelapedrosodasilva",
        content: "@gaudencio_agp @juliananunes114",
    },
    { author: "emilia_thayna13", content: "@emiilyvitoriiaa @aliceraiane2" },
    { author: "emilia_thayna13", content: "@aliceraiane2 @romariorocha06" },
    { author: "emilia_thayna13", content: "@janetef020 @021_felipee__" },
    { author: "emilia_thayna13", content: "@021_felipee__ @janetef020" },
    { author: "emilia_thayna13", content: "@po.liana736 @pose_do_brow2019" },
    {
        author: "isabelapedrosodasilva",
        content: "@psita.senior @psitas_lua_e_juju",
    },
    { author: "isabelapedrosodasilva", content: "@anto.bartolomeu @psita_fenix" },
    { author: "isabelapedrosodasilva", content: "@lunapenabranca @psitashouse" },
    {
        author: "isabelapedrosodasilva",
        content: "@pituco_pisita @pequenograndeboris_",
    },
    { author: "isabelapedrosodasilva", content: "@tatis.psitas @isa.psitas" },
    { author: "isabelapedrosodasilva", content: "@sextetodeasas @harry_psita" },
    { author: "estherfitti", content: "@genipedrosafittipaldi @pedrosa.katia" },
    { author: "kiko.brasileiro", content: "@su_koki__ @periquita_enjoada" },
    { author: "kiko.brasileiro", content: "@su_koki__ @periquita_enjoada" },
    { author: "kiko.brasileiro", content: "@su_koki_ @periquita_enjoada" },
    { author: "kiko.brasileiro", content: "@periquita_enjoada @mickey.pequines" },
    { author: "kiko.brasileiro", content: "@su_koki__ @sublime.natureza" },
    { author: "kiko.brasileiro", content: "@pandorababyrott @romario_aks" },
    { author: "kiko.brasileiro", content: "@wellizimmer @puku_bird" },
    {
        author: "kiko.brasileiro",
        content: "@ursinhos____carinhosos @uragano_dea",
    },
    { author: "kiko.brasileiro", content: "@ursinhaamoraa @ursinhachowchow" },
    {
        author: "kiko.brasileiro",
        content: "@criadouro.mandarim @criadourosantacristina",
    },
    { author: "andrielekleitzke", content: "@cristian_knopp @krolownatalia" },
    { author: "gabrielabocciat", content: "@bernardo29_sz @luttx_" },
    { author: "gabrielabocciat", content: "@soares_caroline00 @anninha_l.r" },
    { author: "gabrielabocciat", content: "@bragagiuu @ogbielzxn" },
    { author: "nina.epipoca", content: "@calopsita_thoor @calo.psitalindas" },
    {
        author: "nina.epipoca",
        content: "@bolinha_e_caio @calopsita_diegoemanoel",
    },
    { author: "calopze", content: "@guilherme.fari.75839923 @fiona_acalop" },
    { author: "calopze", content: "@roselamulticolorida @ninocalopsita2022" },
    { author: "megan.retriever", content: "@flaviamabueno @giijensbz" },
    { author: "megan.retriever", content: "@veh.bueno @jose_bananinha" },
    {
        author: "kiko.brasileiro",
        content: "@calopsitaslolaecharlie @calopscleiton_7l",
    },
    { author: "kiko.brasileiro", content: "@calopscleiton_7l @bebepsita" },
    { author: "kiko.brasileiro", content: "@calopsita._.tico @psitamel" },
    { author: "kiko.brasileiro", content: "@juca_frajolinha @pandorababyrott" },
    {
        author: "kiko.brasileiro",
        content: "@juca_frajolinha @tayguer_2021americanbully",
    },
    {
        author: "kiko.brasileiro",
        content: "@mari.e.tata.ofc @familia_calopsitaa",
    },
    { author: "kiko.brasileiro", content: "@nina_tico_calopsitas @ninyca16" },
    { author: "kiko.brasileiro", content: "@ninacalopst @apollo_jaack" },
    {
        author: "kiko.brasileiro",
        content: "@king_apollored @vida_de_calopsitas_",
    },
    { author: "kiko.brasileiro", content: "@yorks_and_the_west @yasx_hk" },
    { author: "kiko.brasileiro", content: "@yorks_and_the_west @yasx_hk" },
    { author: "kiko.brasileiro", content: "@yellowbirbb @zoey.ragdoll" },
    { author: "kiko.brasileiro", content: "@emilia_thayna13 @nt.norma" },
    { author: "kiko.brasileiro", content: "@zulema_bordie @pandorah.50" },
    { author: "kiko.brasileiro", content: "@emilia_thayna13 @tadeu.lulu" },
    { author: "kiko.brasileiro", content: "@winnie.baby_ @chowchowbsbsbsb" },
    {
        author: "kiko.brasileiro",
        content: "@korella.mix.official @chicletinhodapandora",
    },
    { author: "kiko.brasileiro", content: "@lupita_bastos @bata.ta0309" },
    { author: "kiko.brasileiro", content: "@jose_luan_244 @lhasa.horacio" },
    { author: "kiko.brasileiro", content: "@hope_maya_dog @scooby.cm" },
    { author: "kiko.brasileiro", content: "@luninha.lindaaa @one_crazy_doodle" },
    { author: "kiko.brasileiro", content: "@lilyadotada @lilica_psita" },
    { author: "kiko.brasileiro", content: "@_shihtzu_liz_ @liz.calopsita1888" },
    { author: "kiko.brasileiro", content: "@carlos_gabriel.26 @gabriiel___011" },
    { author: "kiko.brasileiro", content: "@emilia_thayna13 @kanky_13" },
    { author: "kiko.brasileiro", content: "@emilia_thayna13 @mmanu_ferreira.11" },
    { author: "kiko.brasileiro", content: "@roselamulticolorida @guineaapiig" },
    { author: "ninadestro", content: "@dehcg @tatalvess" },
    {
        author: "kiko.brasileiro",
        content: "@yasx_hk @joaopedroleitedeoliveira2008",
    },
    { author: "kiko.brasileiro", content: "@emilia_thayna13 @one_crazy_doodle" },
    { author: "kiko.brasileiro", content: "@wanessa2609 @one_crazy_doodle" },
    { author: "kiko.brasileiro", content: "@wanessa2609 @one_crazy_doodle" },
    {
        author: "kiko.brasileiro",
        content: "@osbulldogs.fofa_bolota @senhoritadog",
    },
    { author: "kiko.brasileiro", content: "@icarocalopsita @shihtzu_tokyo_20" },
    { author: "kiko.brasileiro", content: "@will__lola @music_ehsasi88" },
    { author: "kiko.brasileiro", content: "@calopsitaslolaecharlie @luizgvs" },
    { author: "kiko.brasileiro", content: "@julia_ferreira.13 @emilia_thayna13" },
    { author: "isa_k_14", content: "@alessandra1822021" },
    { author: "isa_k_14", content: "@brendanacleto_" },
    { author: "nicolepmota_", content: "@jmots_ @gilbertoportapilla" },
    { author: "nicolepmota_", content: "@rosisilvamota @marcolamota" },
    {
        author: "nicolepmota_",
        content: "@luciana_elivelto_monteiro @fernandaaasz3",
    },
    { author: "dudaxx__0", content: "@keanu_reeves_anao @edna.ldo51" },
    { author: "aanacmarques", content: "@carlos.zoo @nataliamarques.eng" },
    { author: "aanacmarques", content: "@raphaelagraciane @gracianejaqueline" },
    { author: "emilia_thayna13", content: "@kiko.brasileiro @julia_ferreira.13" },
    { author: "batistadavan", content: "@emilia_thayna13 @arthurbarbosa2019" },
    { author: "batistadavan", content: "@tony_hamste @tony.hamsterr" },
    { author: "batistadavan", content: "@yoon__a0213 @tony.hamsterr" },
    {
        author: "rrroseskt_ted_e_lolo_yorkshire",
        content: "@prici.marques @rosangela.mafs",
    },
    { author: "prici.marques", content: "@sofia.yorkfofa @neusarborin" },
    { author: "prici.marques", content: "@gleme99 @luzaccariotto" },
    { author: "cookie_calopsita_", content: "@be_macedo @viniciusjoaquimpania" },
    { author: "cookie_calopsita_", content: "@tres.psitas @piupets" },
    {
        author: "filhos_de_penas10",
        content: "@fabio.gomes.395017 @fabio_lira_123",
    },
    { author: "filhos_de_penas10", content: "@amorinhapsita30 @amor_de_blue" },
    { author: "filhos_de_penas10", content: "@chiquinhomello @turma.do.buero" },
    {
        author: "filhos_de_penas10",
        content: "@amigo.depenasepelos @amendoimbicotinha",
    },
    { author: "filhos_de_penas10", content: "@samia.antonio.77 @marcelo_e_ruth" },
    { author: "filhos_de_penas10", content: "@antonia094156 @lana_melo_1023" },
    { author: "filhos_de_penas10", content: "@luluzinhacalopsita @loves.psitas" },
    {
        author: "filhos_de_penas10",
        content: "@vida_com_psita @familia_penudinhos",
    },
    { author: "filhos_de_penas10", content: "@messicalopsita @kiwi.mestre" },
    {
        author: "filhos_de_penas10",
        content: "@cantinho_das_aves_mg @rinthegalah",
    },
    { author: "filhos_de_penas10", content: "@ringneck_messi @ringspet_love" },
    { author: "filhos_de_penas10", content: "@ricoperiquito @rio.calops" },
    { author: "filhos_de_penas10", content: "@pipa_teteu_calops @harry_psita" },
    {
        author: "filhos_de_penas10",
        content: "@lusineteximenes123 @gislane_ximenees",
    },
    {
        author: "filhos_de_penas10",
        content: "@renatamelo.mesquita @tamirispaiva44",
    },
    { author: "filhos_de_penas10", content: "@thaismelo584 @thaismello121" },
    { author: "filhos_de_penas10", content: "@criadouro_r.s @criadourowings" },
    {
        author: "filhos_de_penas10",
        content: "@leandraloiola2013 @calopsitas_lelo.branco",
    },
    { author: "filhos_de_penas10", content: "@amazona_verde @amarelinha6454" },
    { author: "filhos_de_penas10", content: "@piueozzy @olaf_calopsita_1" },
    { author: "filhos_de_penas10", content: "@_saras2109 @janilmamelo" },
    { author: "filhos_de_penas10", content: "@abelcalopsita @leno_abel" },
    {
        author: "filhos_de_penas10",
        content: "@bela_e_falcao_calopsita @belchior_calopsita",
    },
    { author: "filhos_de_penas10", content: "@coelha_sophia @floquinho.coelho" },
    { author: "filhos_de_penas10", content: "@mporpeta @clhoe_maya" },
    { author: "filhos_de_penas10", content: "@jhon.lua @alvocalopsita" },
    { author: "filhos_de_penas10", content: "@psitashouse @caju_psitas" },
    {
        author: "filhos_de_penas10",
        content: "@_criadouro_o_mundo_das_aves @cantinho_das_aves_mg",
    },
    { author: "filhos_de_penas10", content: "@kfelixart @ringneck.kiwi" },
    {
        author: "filhos_de_penas10",
        content: "@theo_o_calopsita @calopsita_thoor",
    },
    { author: "thaismelo112", content: "@tatianemelo97 @suelen_martins_lira" },
    { author: "thaismelo112", content: "@lyalimaa12 @leidiane_melo08" },
    { author: "thaismelo112", content: "@marcosfelipe_adv @andreiasoares2809" },
    { author: "thaismelo112", content: "@antonioricardomesquita @bialbuque" },
    { author: "thaismelo112", content: "@renan_mouta739 @mariaritaoliveiira_" },
    {
        author: "thaismelo112",
        content: "@cantinho_das_aves_mg @riziaalvesfeijao",
    },
    {
        author: "thaismelo112",
        content: "@thaisximenes_tata @peninhasdeamorpsita",
    },
    { author: "thaismelo112", content: "@messicalopsita @mesquitaalex784" },
    { author: "thaismelo112", content: "@marcelo_e_ruth @marcelolira771" },
    {
        author: "thaismelo112",
        content: "@samia.antonio.77 @antonioricardomesquita",
    },
    {
        author: "thaismelo112",
        content: "@antonia.elineuda.7 @antoniamariapereiravasconcelos",
    },
    { author: "thaismelo112", content: "@ronaldomesquita954 @renatomelo111" },
    { author: "thaismelo112", content: "@rebasilio00 @renatamelo.mesquita" },
    { author: "thaismelo112", content: "@renata.mesquita.3388 @renatopaiva6" },
    {
        author: "eleonora.montanheri",
        content: "@keniamontanheri @laura_pereiira12",
    },
    { author: "barbara_camboim", content: "@joaop.felix @_bruna.melo29" },
    { author: "barbara_camboim", content: "@itsgideo @monteirogleydson" },
    { author: "barbara_camboim", content: "@natieleholanda @jehmcalheiros" },
    { author: "barbara_camboim", content: "@tizziana1 @diegocamboim" },
    { author: "barbara_camboim", content: "@krol.gsantos @budaemcaos" },
    {
        author: "barbara_camboim",
        content: "@bichosdavanessa @isabel.fernandes63",
    },
    { author: "bichosdavanessa", content: "@goodjr9 @micamercia" },
    { author: "bichosdavanessa", content: "@jorgeandreps @tinacastro43" },
    { author: "bichosdavanessa", content: "@sarah_barros82 @isabel.fernandes63" },
    { author: "bichosdavanessa", content: "@tyfontan @lorenamaiapsi" },
    { author: "bichosdavanessa", content: "@donamariapaiva @adolfaferry" },
    { author: "bichosdavanessa", content: "@alexrocha__ @saulodetarso_" },
    { author: "bichosdavanessa", content: "@priscila7764 @everson.alyson" },
    { author: "bichosdavanessa", content: "@natieleholanda @natanny_luizjr" },
    { author: "bichosdavanessa", content: "@iamjulietslayer @kellymoraes09" },
    { author: "bichosdavanessa", content: "@kelcymary @keylabraboadv" },
    { author: "bichosdavanessa", content: "@betasaiac @larabmd" },
    { author: "bichosdavanessa", content: "@anafiguereido @biulynha" },
    { author: "bichosdavanessa", content: "@edlainny_claudia @jamycarvalho" },
    {
        author: "bichosdavanessa",
        content: "@psicologoeriferreira @italoferreirapsi",
    },
    { author: "bichosdavanessa", content: "@piuduartesanches @daianarosecc" },
    { author: "bichosdavanessa", content: "@emanuela.ferry @flora_fandes" },
    { author: "bichosdavanessa", content: "@gatodionisio @cintiam1" },
    { author: "bichosdavanessa", content: "@roseanefortunatoc @estefaneollima" },
    { author: "bichosdavanessa", content: "@negapretahu @cidocagalvaosaulino" },
    { author: "bichosdavanessa", content: "@layonmelo_ @larissaferry2" },
    { author: "sarah_barros82", content: "@bichosdavanessa @isabel.fernandes63" },
    { author: "bichosdavanessa", content: "@iamjulietslayer @bhn3t0" },
    { author: "bichosdavanessa", content: "@helenamoraes1088 @roberliagomes" },
    { author: "thaismelo112", content: "@rafaelly.9040 @roger_maiaa" },
    { author: "thaismelo112", content: "@turma.do.buero @thaisximenes_tata" },
    { author: "thaismelo112", content: "@paiva.toinha @thayara_95" },
    {
        author: "thaismelo112",
        content: "@brunavasconcelos2011hotmailcom @marcela.paiva.395",
    },
    { author: "thaismelo112", content: "@samia.antonio.77 @marcelo_e_ruth" },
    { author: "thaismelo112", content: "@anna_iris_pessoa @_inaratm" },
    { author: "thaismelo112", content: "@isis_miaa @irmaos_de_asas" },
    { author: "thaismelo112", content: "@suelen_martins_lira @chaguinha.m.o" },
    { author: "thaismelo112", content: "@niellyaraujoo @ramir_ralison" },
    { author: "thaismelo112", content: "@turma.do.buero @lyalimaa12" },
    { author: "thaismelo112", content: "@toinogato2 @talespaiva16" },
    { author: "thaismelo112", content: "@abelcalopsita @riziaalvesfeijao" },
    { author: "thaismelo112", content: "@andressa.pp @andreyvo9" },
    {
        author: "filhos_de_penas10",
        content: "@fabio.gomes.395017 @fabio_lira_123",
    },
    { author: "filhos_de_penas10", content: "@marcelo_e_ruth @antonia094156" },
    { author: "filhos_de_penas10", content: "@anto.bartolomeu @lana_melo_1023" },
    { author: "filhos_de_penas10", content: "@zoeypapagaiadocongo @flap_pet" },
    { author: "filhos_de_penas10", content: "@thaismelo112 @fabio_lira_123" },
    { author: "filhos_de_penas10", content: "@andreiasoares2809 @_saras2109" },
    {
        author: "filhos_de_penas10",
        content: "@cantinho_das_aves_mg @theo_o_calopsita",
    },
    { author: "filhos_de_penas10", content: "@dino_tex_pets @turma.do.buero" },
    {
        author: "filhos_de_penas10",
        content: "@calopsita_thoor @theo_o_calopsita",
    },
    { author: "filhos_de_penas10", content: "@leticiaalvees20 @filhosdepenas3" },
    {
        author: "filhos_de_penas10",
        content: "@safira_passarodoamor @agarponis_jundiai",
    },
    {
        author: "filhos_de_penas10",
        content: "@piueozzy @mundodopulinho_calopsita",
    },
    { author: "filhos_de_penas10", content: "@pet_rosela @peninhasdeamorpsita" },
    { author: "thaismelo112", content: "@amirtonalves @anacamila_myla" },
    { author: "thaismelo112", content: "@amanda__beads @loiola2302" },
    { author: "thaismelo112", content: "@thaisximenes_tata @thaisalbuquerquex" },
    { author: "thaismelo112", content: "@anderson_silva_mel0 @camposelainne" },
    { author: "thaismelo112", content: "@marcosfelipe_adv @andreiasoares2809" },
    { author: "thaismelo112", content: "@cantinho_das_aves_mg @tatianemelo97" },
    { author: "thaismelo112", content: "@zoeemanuelleof @wanessasouzaof" },
    { author: "thaismelo112", content: "@saimu_lima @sabrinna__vasconcelos" },
    { author: "thaismelo112", content: "@filhos_de_penas10 @fabio_lira_123" },
    { author: "thaismelo112", content: "@amanda__beads @_dyegonogueira" },
    { author: "thaismelo112", content: "@thamy.lima28 @_thayscordeiro" },
    { author: "thaismelo112", content: "@_thayscordeiro @thayara_95" },
    { author: "thaismelo112", content: "@baby_bencao_2021 @babypisita2021" },
    {
        author: "thaismelo112",
        content: "@brinquedoscalopsita @claraloiola.sobrancelhas",
    },
    { author: "thaismelo112", content: "@leidiane_melo08 @bessa_patricia24" },
    { author: "thaismelo112", content: "@lyalimaa12 @liliane.oliveira32" },
    {
        author: "thaismelo112",
        content: "@brunavasconcelos2011hotmailcom @leticiaalvees20",
    },
    { author: "thaismelo112", content: "@marcelolira771 @marcelo_e_ruth" },
    { author: "thaismelo112", content: "@samia.antonio.77 @marcelo_e_ruth" },
    { author: "thaismelo112", content: "@fabio.gomes.395017 @fabio_lira_123" },
    { author: "bichosdavanessa", content: "@samia_reis @mhelenaxavier" },
    { author: "bichosdavanessa", content: "@poly_med_lp @karlakviana" },
    { author: "bichosdavanessa", content: "@hemimart @floquinho_oficial14" },
];